// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: giphy/v1/giphy.proto

package giphypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Gif represents a single GIF object from the Giphy API.
type Gif struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique Giphy identifier for this GIF (e.g., "xT9IgzoKnwFNmISR8I").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The URL to the Giphy page for this GIF.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// The title of the GIF.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// The content rating (g, pg, pg-13, r).
	Rating string `protobuf:"bytes,4,opt,name=rating,proto3" json:"rating,omitempty"`
	// The date this GIF was imported to Giphy (ISO 8601 format).
	ImportDatetime string `protobuf:"bytes,5,opt,name=import_datetime,json=importDatetime,proto3" json:"import_datetime,omitempty"`
	// The date this GIF started trending, if applicable.
	TrendingDatetime string `protobuf:"bytes,6,opt,name=trending_datetime,json=trendingDatetime,proto3" json:"trending_datetime,omitempty"`
	// The source URL where this GIF was originally found.
	Source string `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	// A short URL for sharing (e.g., "https://gph.is/abc123").
	BitlyUrl string `protobuf:"bytes,8,opt,name=bitly_url,json=bitlyUrl,proto3" json:"bitly_url,omitempty"`
	// The embed URL for iframe embedding.
	EmbedUrl string `protobuf:"bytes,9,opt,name=embed_url,json=embedUrl,proto3" json:"embed_url,omitempty"`
	// The username of the Giphy user who uploaded this GIF.
	Username string `protobuf:"bytes,10,opt,name=username,proto3" json:"username,omitempty"`
	// The URL to the original full-size image.
	OriginalUrl string `protobuf:"bytes,11,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	// Width of the original image in pixels.
	OriginalWidth string `protobuf:"bytes,12,opt,name=original_width,json=originalWidth,proto3" json:"original_width,omitempty"`
	// Height of the original image in pixels.
	OriginalHeight string `protobuf:"bytes,13,opt,name=original_height,json=originalHeight,proto3" json:"original_height,omitempty"`
	// URL of the fixed-width (200px) rendition.
	FixedWidthUrl string `protobuf:"bytes,14,opt,name=fixed_width_url,json=fixedWidthUrl,proto3" json:"fixed_width_url,omitempty"`
	// URL of the fixed-height (200px) rendition.
	FixedHeightUrl string `protobuf:"bytes,15,opt,name=fixed_height_url,json=fixedHeightUrl,proto3" json:"fixed_height_url,omitempty"`
	// URL of the downsized rendition (under 2MB for previews).
	DownsizedUrl string `protobuf:"bytes,16,opt,name=downsized_url,json=downsizedUrl,proto3" json:"downsized_url,omitempty"`
	// URL of the preview rendition (under 50KB, small dimensions).
	PreviewUrl string `protobuf:"bytes,17,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	// The slug portion of the GIF's Giphy URL.
	Slug string `protobuf:"bytes,18,opt,name=slug,proto3" json:"slug,omitempty"`
	// The type of content ("gif" or "sticker").
	Type          string `protobuf:"bytes,19,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gif) Reset() {
	*x = Gif{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gif) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gif) ProtoMessage() {}

func (x *Gif) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gif.ProtoReflect.Descriptor instead.
func (*Gif) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{0}
}

func (x *Gif) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gif) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Gif) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Gif) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *Gif) GetImportDatetime() string {
	if x != nil {
		return x.ImportDatetime
	}
	return ""
}

func (x *Gif) GetTrendingDatetime() string {
	if x != nil {
		return x.TrendingDatetime
	}
	return ""
}

func (x *Gif) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Gif) GetBitlyUrl() string {
	if x != nil {
		return x.BitlyUrl
	}
	return ""
}

func (x *Gif) GetEmbedUrl() string {
	if x != nil {
		return x.EmbedUrl
	}
	return ""
}

func (x *Gif) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Gif) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *Gif) GetOriginalWidth() string {
	if x != nil {
		return x.OriginalWidth
	}
	return ""
}

func (x *Gif) GetOriginalHeight() string {
	if x != nil {
		return x.OriginalHeight
	}
	return ""
}

func (x *Gif) GetFixedWidthUrl() string {
	if x != nil {
		return x.FixedWidthUrl
	}
	return ""
}

func (x *Gif) GetFixedHeightUrl() string {
	if x != nil {
		return x.FixedHeightUrl
	}
	return ""
}

func (x *Gif) GetDownsizedUrl() string {
	if x != nil {
		return x.DownsizedUrl
	}
	return ""
}

func (x *Gif) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *Gif) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Gif) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Pagination holds paging metadata for list responses.
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of results available.
	TotalCount int32 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Number of results returned in this response.
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Position offset of the first result in this response.
	Offset        int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Pagination) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Category represents a GIF content category.
type Category struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The category name (e.g., "Animals", "Actions").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A representative GIF for this category.
	Gif           *Gif `protobuf:"bytes,2,opt,name=gif,proto3" json:"gif,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{2}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetGif() *Gif {
	if x != nil {
		return x.Gif
	}
	return nil
}

// Request for Search RPC.
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The search query string (e.g., "funny cats", "thumbs up", "mind blown").
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Maximum number of GIFs to return (1-50). Defaults to 25.
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Results offset for pagination. Defaults to 0.
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Content rating filter: "g", "pg", "pg-13", or "r". Defaults to no filter.
	Rating string `protobuf:"bytes,4,opt,name=rating,proto3" json:"rating,omitempty"`
	// Language code in ISO 639-1 format (e.g., "en", "es", "fr"). Defaults to "en".
	Lang          string `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *SearchRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// Response for Search RPC.
type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of GIFs matching the search query.
	Data []*Gif `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Pagination metadata.
	Pagination    *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetData() []*Gif {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Request for Trending RPC.
type TrendingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of GIFs to return (1-50). Defaults to 25.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Results offset for pagination. Defaults to 0.
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Content rating filter: "g", "pg", "pg-13", or "r". Defaults to no filter.
	Rating        string `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingRequest) Reset() {
	*x = TrendingRequest{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingRequest) ProtoMessage() {}

func (x *TrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingRequest.ProtoReflect.Descriptor instead.
func (*TrendingRequest) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{5}
}

func (x *TrendingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TrendingRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TrendingRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

// Response for Trending RPC.
type TrendingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of currently trending GIFs.
	Data []*Gif `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Pagination metadata.
	Pagination    *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingResponse) Reset() {
	*x = TrendingResponse{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingResponse) ProtoMessage() {}

func (x *TrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingResponse.ProtoReflect.Descriptor instead.
func (*TrendingResponse) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{6}
}

func (x *TrendingResponse) GetData() []*Gif {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TrendingResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Request for GetGifById RPC.
type GetGifByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Giphy GIF ID to look up (e.g., "xT9IgzoKnwFNmISR8I").
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGifByIdRequest) Reset() {
	*x = GetGifByIdRequest{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGifByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGifByIdRequest) ProtoMessage() {}

func (x *GetGifByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGifByIdRequest.ProtoReflect.Descriptor instead.
func (*GetGifByIdRequest) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{7}
}

func (x *GetGifByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response for GetGifById RPC.
type GetGifByIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested GIF object.
	Data          *Gif `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGifByIdResponse) Reset() {
	*x = GetGifByIdResponse{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGifByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGifByIdResponse) ProtoMessage() {}

func (x *GetGifByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGifByIdResponse.ProtoReflect.Descriptor instead.
func (*GetGifByIdResponse) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{8}
}

func (x *GetGifByIdResponse) GetData() *Gif {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request for GetGifsByIds RPC.
type GetGifsByIdsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of Giphy GIF IDs to look up. Maximum 50 IDs per request.
	Ids           []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGifsByIdsRequest) Reset() {
	*x = GetGifsByIdsRequest{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGifsByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGifsByIdsRequest) ProtoMessage() {}

func (x *GetGifsByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGifsByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetGifsByIdsRequest) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{9}
}

func (x *GetGifsByIdsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// Response for GetGifsByIds RPC.
type GetGifsByIdsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of GIF objects for the requested IDs.
	Data          []*Gif `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGifsByIdsResponse) Reset() {
	*x = GetGifsByIdsResponse{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGifsByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGifsByIdsResponse) ProtoMessage() {}

func (x *GetGifsByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGifsByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetGifsByIdsResponse) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{10}
}

func (x *GetGifsByIdsResponse) GetData() []*Gif {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request for Random RPC.
type RandomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional tag/keyword to filter the random selection (e.g., "cats", "happy").
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// Content rating filter: "g", "pg", "pg-13", or "r". Defaults to no filter.
	Rating        string `protobuf:"bytes,2,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomRequest) Reset() {
	*x = RandomRequest{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomRequest) ProtoMessage() {}

func (x *RandomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomRequest.ProtoReflect.Descriptor instead.
func (*RandomRequest) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{11}
}

func (x *RandomRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RandomRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

// Response for Random RPC.
type RandomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The randomly selected GIF.
	Data          *Gif `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomResponse) Reset() {
	*x = RandomResponse{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomResponse) ProtoMessage() {}

func (x *RandomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomResponse.ProtoReflect.Descriptor instead.
func (*RandomResponse) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{12}
}

func (x *RandomResponse) GetData() *Gif {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request for SearchStickers RPC.
type SearchStickersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The search query string for stickers.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Maximum number of stickers to return (1-50). Defaults to 25.
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Results offset for pagination. Defaults to 0.
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Content rating filter: "g", "pg", "pg-13", or "r". Defaults to no filter.
	Rating string `protobuf:"bytes,4,opt,name=rating,proto3" json:"rating,omitempty"`
	// Language code in ISO 639-1 format (e.g., "en", "es"). Defaults to "en".
	Lang          string `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStickersRequest) Reset() {
	*x = SearchStickersRequest{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStickersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStickersRequest) ProtoMessage() {}

func (x *SearchStickersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStickersRequest.ProtoReflect.Descriptor instead.
func (*SearchStickersRequest) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{13}
}

func (x *SearchStickersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchStickersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchStickersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchStickersRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *SearchStickersRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// Response for SearchStickers RPC.
type SearchStickersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of stickers matching the search query.
	Data []*Gif `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Pagination metadata.
	Pagination    *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStickersResponse) Reset() {
	*x = SearchStickersResponse{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStickersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStickersResponse) ProtoMessage() {}

func (x *SearchStickersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStickersResponse.ProtoReflect.Descriptor instead.
func (*SearchStickersResponse) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{14}
}

func (x *SearchStickersResponse) GetData() []*Gif {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchStickersResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Request for TrendingStickers RPC.
type TrendingStickersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of stickers to return (1-50). Defaults to 25.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Results offset for pagination. Defaults to 0.
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Content rating filter: "g", "pg", "pg-13", or "r". Defaults to no filter.
	Rating        string `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingStickersRequest) Reset() {
	*x = TrendingStickersRequest{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingStickersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingStickersRequest) ProtoMessage() {}

func (x *TrendingStickersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingStickersRequest.ProtoReflect.Descriptor instead.
func (*TrendingStickersRequest) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{15}
}

func (x *TrendingStickersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TrendingStickersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TrendingStickersRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

// Response for TrendingStickers RPC.
type TrendingStickersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of currently trending stickers.
	Data []*Gif `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Pagination metadata.
	Pagination    *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingStickersResponse) Reset() {
	*x = TrendingStickersResponse{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingStickersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingStickersResponse) ProtoMessage() {}

func (x *TrendingStickersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingStickersResponse.ProtoReflect.Descriptor instead.
func (*TrendingStickersResponse) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{16}
}

func (x *TrendingStickersResponse) GetData() []*Gif {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TrendingStickersResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Request for RandomSticker RPC.
type RandomStickerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional tag/keyword to filter the random sticker selection.
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// Content rating filter: "g", "pg", "pg-13", or "r". Defaults to no filter.
	Rating        string `protobuf:"bytes,2,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomStickerRequest) Reset() {
	*x = RandomStickerRequest{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomStickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomStickerRequest) ProtoMessage() {}

func (x *RandomStickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomStickerRequest.ProtoReflect.Descriptor instead.
func (*RandomStickerRequest) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{17}
}

func (x *RandomStickerRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RandomStickerRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

// Response for RandomSticker RPC.
type RandomStickerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The randomly selected sticker.
	Data          *Gif `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomStickerResponse) Reset() {
	*x = RandomStickerResponse{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomStickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomStickerResponse) ProtoMessage() {}

func (x *RandomStickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomStickerResponse.ProtoReflect.Descriptor instead.
func (*RandomStickerResponse) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{18}
}

func (x *RandomStickerResponse) GetData() *Gif {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request for Translate RPC.
type TranslateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text to translate into a GIF (e.g., "I'm so excited", "good morning").
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Weirdness factor from 0 to 10. Higher values return more unexpected GIFs.
	// 0 = most literal match, 10 = most creative/abstract. Defaults to 0.
	Weirdness int32 `protobuf:"varint,2,opt,name=weirdness,proto3" json:"weirdness,omitempty"`
	// Content rating filter: "g", "pg", "pg-13", or "r". Defaults to no filter.
	Rating        string `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{19}
}

func (x *TranslateRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TranslateRequest) GetWeirdness() int32 {
	if x != nil {
		return x.Weirdness
	}
	return 0
}

func (x *TranslateRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

// Response for Translate RPC.
type TranslateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The translated GIF.
	Data          *Gif `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{20}
}

func (x *TranslateResponse) GetData() *Gif {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request for GetCategories RPC.
type GetCategoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of categories to return. Defaults to 25.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Results offset for pagination. Defaults to 0.
	Offset        int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{21}
}

func (x *GetCategoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCategoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Response for GetCategories RPC.
type GetCategoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of GIF categories.
	Data          []*Category `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_giphy_v1_giphy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giphy_v1_giphy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_giphy_v1_giphy_proto_rawDescGZIP(), []int{22}
}

func (x *GetCategoriesResponse) GetData() []*Category {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_giphy_v1_giphy_proto protoreflect.FileDescriptor

const file_giphy_v1_giphy_proto_rawDesc = "" +
	"\n" +
	"\x14giphy/v1/giphy.proto\x12\bgiphy.v1\"\xcc\x04\n" +
	"\x03Gif\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\tR\x06rating\x12'\n" +
	"\x0fimport_datetime\x18\x05 \x01(\tR\x0eimportDatetime\x12+\n" +
	"\x11trending_datetime\x18\x06 \x01(\tR\x10trendingDatetime\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1b\n" +
	"\tbitly_url\x18\b \x01(\tR\bbitlyUrl\x12\x1b\n" +
	"\tembed_url\x18\t \x01(\tR\bembedUrl\x12\x1a\n" +
	"\busername\x18\n" +
	" \x01(\tR\busername\x12!\n" +
	"\foriginal_url\x18\v \x01(\tR\voriginalUrl\x12%\n" +
	"\x0eoriginal_width\x18\f \x01(\tR\roriginalWidth\x12'\n" +
	"\x0foriginal_height\x18\r \x01(\tR\x0eoriginalHeight\x12&\n" +
	"\x0ffixed_width_url\x18\x0e \x01(\tR\rfixedWidthUrl\x12(\n" +
	"\x10fixed_height_url\x18\x0f \x01(\tR\x0efixedHeightUrl\x12#\n" +
	"\rdownsized_url\x18\x10 \x01(\tR\fdownsizedUrl\x12\x1f\n" +
	"\vpreview_url\x18\x11 \x01(\tR\n" +
	"previewUrl\x12\x12\n" +
	"\x04slug\x18\x12 \x01(\tR\x04slug\x12\x12\n" +
	"\x04type\x18\x13 \x01(\tR\x04type\"[\n" +
	"\n" +
	"Pagination\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"?\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\x03gif\x18\x02 \x01(\v2\r.giphy.v1.GifR\x03gif\"\x7f\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\tR\x06rating\x12\x12\n" +
	"\x04lang\x18\x05 \x01(\tR\x04lang\"i\n" +
	"\x0eSearchResponse\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.giphy.v1.GifR\x04data\x124\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.giphy.v1.PaginationR\n" +
	"pagination\"W\n" +
	"\x0fTrendingRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\tR\x06rating\"k\n" +
	"\x10TrendingResponse\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.giphy.v1.GifR\x04data\x124\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.giphy.v1.PaginationR\n" +
	"pagination\"#\n" +
	"\x11GetGifByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x12GetGifByIdResponse\x12!\n" +
	"\x04data\x18\x01 \x01(\v2\r.giphy.v1.GifR\x04data\"'\n" +
	"\x13GetGifsByIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"9\n" +
	"\x14GetGifsByIdsResponse\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.giphy.v1.GifR\x04data\"9\n" +
	"\rRandomRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\tR\x06rating\"3\n" +
	"\x0eRandomResponse\x12!\n" +
	"\x04data\x18\x01 \x01(\v2\r.giphy.v1.GifR\x04data\"\x87\x01\n" +
	"\x15SearchStickersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\tR\x06rating\x12\x12\n" +
	"\x04lang\x18\x05 \x01(\tR\x04lang\"q\n" +
	"\x16SearchStickersResponse\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.giphy.v1.GifR\x04data\x124\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.giphy.v1.PaginationR\n" +
	"pagination\"_\n" +
	"\x17TrendingStickersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\tR\x06rating\"s\n" +
	"\x18TrendingStickersResponse\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.giphy.v1.GifR\x04data\x124\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.giphy.v1.PaginationR\n" +
	"pagination\"@\n" +
	"\x14RandomStickerRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\tR\x06rating\":\n" +
	"\x15RandomStickerResponse\x12!\n" +
	"\x04data\x18\x01 \x01(\v2\r.giphy.v1.GifR\x04data\"^\n" +
	"\x10TranslateRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1c\n" +
	"\tweirdness\x18\x02 \x01(\x05R\tweirdness\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\tR\x06rating\"6\n" +
	"\x11TranslateResponse\x12!\n" +
	"\x04data\x18\x01 \x01(\v2\r.giphy.v1.GifR\x04data\"D\n" +
	"\x14GetCategoriesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"?\n" +
	"\x15GetCategoriesResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.giphy.v1.CategoryR\x04data2\xfd\x05\n" +
	"\fGiphyService\x12;\n" +
	"\x06Search\x12\x17.giphy.v1.SearchRequest\x1a\x18.giphy.v1.SearchResponse\x12A\n" +
	"\bTrending\x12\x19.giphy.v1.TrendingRequest\x1a\x1a.giphy.v1.TrendingResponse\x12G\n" +
	"\n" +
	"GetGifById\x12\x1b.giphy.v1.GetGifByIdRequest\x1a\x1c.giphy.v1.GetGifByIdResponse\x12M\n" +
	"\fGetGifsByIds\x12\x1d.giphy.v1.GetGifsByIdsRequest\x1a\x1e.giphy.v1.GetGifsByIdsResponse\x12;\n" +
	"\x06Random\x12\x17.giphy.v1.RandomRequest\x1a\x18.giphy.v1.RandomResponse\x12S\n" +
	"\x0eSearchStickers\x12\x1f.giphy.v1.SearchStickersRequest\x1a .giphy.v1.SearchStickersResponse\x12Y\n" +
	"\x10TrendingStickers\x12!.giphy.v1.TrendingStickersRequest\x1a\".giphy.v1.TrendingStickersResponse\x12P\n" +
	"\rRandomSticker\x12\x1e.giphy.v1.RandomStickerRequest\x1a\x1f.giphy.v1.RandomStickerResponse\x12D\n" +
	"\tTranslate\x12\x1a.giphy.v1.TranslateRequest\x1a\x1b.giphy.v1.TranslateResponse\x12P\n" +
	"\rGetCategories\x12\x1e.giphy.v1.GetCategoriesRequest\x1a\x1f.giphy.v1.GetCategoriesResponseB\x9b\x01\n" +
	"\fcom.giphy.v1B\n" +
	"GiphyProtoP\x01Z>github.com/jim-technologies/invariantaf/giphy/giphy/v1;giphypb\xa2\x02\x03GXX\xaa\x02\bGiphy.V1\xca\x02\bGiphy\\V1\xe2\x02\x14Giphy\\V1\\GPBMetadata\xea\x02\tGiphy::V1b\x06proto3"

var (
	file_giphy_v1_giphy_proto_rawDescOnce sync.Once
	file_giphy_v1_giphy_proto_rawDescData []byte
)

func file_giphy_v1_giphy_proto_rawDescGZIP() []byte {
	file_giphy_v1_giphy_proto_rawDescOnce.Do(func() {
		file_giphy_v1_giphy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_giphy_v1_giphy_proto_rawDesc), len(file_giphy_v1_giphy_proto_rawDesc)))
	})
	return file_giphy_v1_giphy_proto_rawDescData
}

var file_giphy_v1_giphy_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_giphy_v1_giphy_proto_goTypes = []any{
	(*Gif)(nil),                      // 0: giphy.v1.Gif
	(*Pagination)(nil),               // 1: giphy.v1.Pagination
	(*Category)(nil),                 // 2: giphy.v1.Category
	(*SearchRequest)(nil),            // 3: giphy.v1.SearchRequest
	(*SearchResponse)(nil),           // 4: giphy.v1.SearchResponse
	(*TrendingRequest)(nil),          // 5: giphy.v1.TrendingRequest
	(*TrendingResponse)(nil),         // 6: giphy.v1.TrendingResponse
	(*GetGifByIdRequest)(nil),        // 7: giphy.v1.GetGifByIdRequest
	(*GetGifByIdResponse)(nil),       // 8: giphy.v1.GetGifByIdResponse
	(*GetGifsByIdsRequest)(nil),      // 9: giphy.v1.GetGifsByIdsRequest
	(*GetGifsByIdsResponse)(nil),     // 10: giphy.v1.GetGifsByIdsResponse
	(*RandomRequest)(nil),            // 11: giphy.v1.RandomRequest
	(*RandomResponse)(nil),           // 12: giphy.v1.RandomResponse
	(*SearchStickersRequest)(nil),    // 13: giphy.v1.SearchStickersRequest
	(*SearchStickersResponse)(nil),   // 14: giphy.v1.SearchStickersResponse
	(*TrendingStickersRequest)(nil),  // 15: giphy.v1.TrendingStickersRequest
	(*TrendingStickersResponse)(nil), // 16: giphy.v1.TrendingStickersResponse
	(*RandomStickerRequest)(nil),     // 17: giphy.v1.RandomStickerRequest
	(*RandomStickerResponse)(nil),    // 18: giphy.v1.RandomStickerResponse
	(*TranslateRequest)(nil),         // 19: giphy.v1.TranslateRequest
	(*TranslateResponse)(nil),        // 20: giphy.v1.TranslateResponse
	(*GetCategoriesRequest)(nil),     // 21: giphy.v1.GetCategoriesRequest
	(*GetCategoriesResponse)(nil),    // 22: giphy.v1.GetCategoriesResponse
}
var file_giphy_v1_giphy_proto_depIdxs = []int32{
	0,  // 0: giphy.v1.Category.gif:type_name -> giphy.v1.Gif
	0,  // 1: giphy.v1.SearchResponse.data:type_name -> giphy.v1.Gif
	1,  // 2: giphy.v1.SearchResponse.pagination:type_name -> giphy.v1.Pagination
	0,  // 3: giphy.v1.TrendingResponse.data:type_name -> giphy.v1.Gif
	1,  // 4: giphy.v1.TrendingResponse.pagination:type_name -> giphy.v1.Pagination
	0,  // 5: giphy.v1.GetGifByIdResponse.data:type_name -> giphy.v1.Gif
	0,  // 6: giphy.v1.GetGifsByIdsResponse.data:type_name -> giphy.v1.Gif
	0,  // 7: giphy.v1.RandomResponse.data:type_name -> giphy.v1.Gif
	0,  // 8: giphy.v1.SearchStickersResponse.data:type_name -> giphy.v1.Gif
	1,  // 9: giphy.v1.SearchStickersResponse.pagination:type_name -> giphy.v1.Pagination
	0,  // 10: giphy.v1.TrendingStickersResponse.data:type_name -> giphy.v1.Gif
	1,  // 11: giphy.v1.TrendingStickersResponse.pagination:type_name -> giphy.v1.Pagination
	0,  // 12: giphy.v1.RandomStickerResponse.data:type_name -> giphy.v1.Gif
	0,  // 13: giphy.v1.TranslateResponse.data:type_name -> giphy.v1.Gif
	2,  // 14: giphy.v1.GetCategoriesResponse.data:type_name -> giphy.v1.Category
	3,  // 15: giphy.v1.GiphyService.Search:input_type -> giphy.v1.SearchRequest
	5,  // 16: giphy.v1.GiphyService.Trending:input_type -> giphy.v1.TrendingRequest
	7,  // 17: giphy.v1.GiphyService.GetGifById:input_type -> giphy.v1.GetGifByIdRequest
	9,  // 18: giphy.v1.GiphyService.GetGifsByIds:input_type -> giphy.v1.GetGifsByIdsRequest
	11, // 19: giphy.v1.GiphyService.Random:input_type -> giphy.v1.RandomRequest
	13, // 20: giphy.v1.GiphyService.SearchStickers:input_type -> giphy.v1.SearchStickersRequest
	15, // 21: giphy.v1.GiphyService.TrendingStickers:input_type -> giphy.v1.TrendingStickersRequest
	17, // 22: giphy.v1.GiphyService.RandomSticker:input_type -> giphy.v1.RandomStickerRequest
	19, // 23: giphy.v1.GiphyService.Translate:input_type -> giphy.v1.TranslateRequest
	21, // 24: giphy.v1.GiphyService.GetCategories:input_type -> giphy.v1.GetCategoriesRequest
	4,  // 25: giphy.v1.GiphyService.Search:output_type -> giphy.v1.SearchResponse
	6,  // 26: giphy.v1.GiphyService.Trending:output_type -> giphy.v1.TrendingResponse
	8,  // 27: giphy.v1.GiphyService.GetGifById:output_type -> giphy.v1.GetGifByIdResponse
	10, // 28: giphy.v1.GiphyService.GetGifsByIds:output_type -> giphy.v1.GetGifsByIdsResponse
	12, // 29: giphy.v1.GiphyService.Random:output_type -> giphy.v1.RandomResponse
	14, // 30: giphy.v1.GiphyService.SearchStickers:output_type -> giphy.v1.SearchStickersResponse
	16, // 31: giphy.v1.GiphyService.TrendingStickers:output_type -> giphy.v1.TrendingStickersResponse
	18, // 32: giphy.v1.GiphyService.RandomSticker:output_type -> giphy.v1.RandomStickerResponse
	20, // 33: giphy.v1.GiphyService.Translate:output_type -> giphy.v1.TranslateResponse
	22, // 34: giphy.v1.GiphyService.GetCategories:output_type -> giphy.v1.GetCategoriesResponse
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_giphy_v1_giphy_proto_init() }
func file_giphy_v1_giphy_proto_init() {
	if File_giphy_v1_giphy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_giphy_v1_giphy_proto_rawDesc), len(file_giphy_v1_giphy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_giphy_v1_giphy_proto_goTypes,
		DependencyIndexes: file_giphy_v1_giphy_proto_depIdxs,
		MessageInfos:      file_giphy_v1_giphy_proto_msgTypes,
	}.Build()
	File_giphy_v1_giphy_proto = out.File
	file_giphy_v1_giphy_proto_goTypes = nil
	file_giphy_v1_giphy_proto_depIdxs = nil
}
