// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cryptodotcom/v1/cryptodotcom.proto

package cryptodotcomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInstrumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstrumentsRequest) Reset() {
	*x = GetInstrumentsRequest{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstrumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstrumentsRequest) ProtoMessage() {}

func (x *GetInstrumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstrumentsRequest.ProtoReflect.Descriptor instead.
func (*GetInstrumentsRequest) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{0}
}

type Instrument struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InstrumentName       string                 `protobuf:"bytes,1,opt,name=instrument_name,json=instrumentName,proto3" json:"instrument_name,omitempty"`
	QuoteCurrency        string                 `protobuf:"bytes,2,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	BaseCurrency         string                 `protobuf:"bytes,3,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	PriceDecimals        string                 `protobuf:"bytes,4,opt,name=price_decimals,json=priceDecimals,proto3" json:"price_decimals,omitempty"`
	QuantityDecimals     string                 `protobuf:"bytes,5,opt,name=quantity_decimals,json=quantityDecimals,proto3" json:"quantity_decimals,omitempty"`
	MarginTradingEnabled bool                   `protobuf:"varint,6,opt,name=margin_trading_enabled,json=marginTradingEnabled,proto3" json:"margin_trading_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Instrument) Reset() {
	*x = Instrument{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument) ProtoMessage() {}

func (x *Instrument) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument.ProtoReflect.Descriptor instead.
func (*Instrument) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{1}
}

func (x *Instrument) GetInstrumentName() string {
	if x != nil {
		return x.InstrumentName
	}
	return ""
}

func (x *Instrument) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

func (x *Instrument) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *Instrument) GetPriceDecimals() string {
	if x != nil {
		return x.PriceDecimals
	}
	return ""
}

func (x *Instrument) GetQuantityDecimals() string {
	if x != nil {
		return x.QuantityDecimals
	}
	return ""
}

func (x *Instrument) GetMarginTradingEnabled() bool {
	if x != nil {
		return x.MarginTradingEnabled
	}
	return false
}

type GetInstrumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Instrument          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstrumentsResponse) Reset() {
	*x = GetInstrumentsResponse{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstrumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstrumentsResponse) ProtoMessage() {}

func (x *GetInstrumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstrumentsResponse.ProtoReflect.Descriptor instead.
func (*GetInstrumentsResponse) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{2}
}

func (x *GetInstrumentsResponse) GetData() []*Instrument {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTickersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument name (e.g. "BTC_USDT"). Omit for all tickers.
	InstrumentName *string `protobuf:"bytes,1,opt,name=instrument_name,json=instrumentName,proto3,oneof" json:"instrument_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTickersRequest) Reset() {
	*x = GetTickersRequest{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickersRequest) ProtoMessage() {}

func (x *GetTickersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickersRequest.ProtoReflect.Descriptor instead.
func (*GetTickersRequest) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{3}
}

func (x *GetTickersRequest) GetInstrumentName() string {
	if x != nil && x.InstrumentName != nil {
		return *x.InstrumentName
	}
	return ""
}

type Ticker struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InstrumentName     string                 `protobuf:"bytes,1,opt,name=instrument_name,json=instrumentName,proto3" json:"instrument_name,omitempty"`
	High               string                 `protobuf:"bytes,2,opt,name=high,proto3" json:"high,omitempty"`
	Low                string                 `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	LatestTrade        string                 `protobuf:"bytes,4,opt,name=latest_trade,json=latestTrade,proto3" json:"latest_trade,omitempty"`
	Volume             string                 `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	BestBid            string                 `protobuf:"bytes,6,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`
	BestAsk            string                 `protobuf:"bytes,7,opt,name=best_ask,json=bestAsk,proto3" json:"best_ask,omitempty"`
	PriceChange        string                 `protobuf:"bytes,8,opt,name=price_change,json=priceChange,proto3" json:"price_change,omitempty"`
	PriceChangePercent string                 `protobuf:"bytes,9,opt,name=price_change_percent,json=priceChangePercent,proto3" json:"price_change_percent,omitempty"`
	Timestamp          int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{4}
}

func (x *Ticker) GetInstrumentName() string {
	if x != nil {
		return x.InstrumentName
	}
	return ""
}

func (x *Ticker) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Ticker) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Ticker) GetLatestTrade() string {
	if x != nil {
		return x.LatestTrade
	}
	return ""
}

func (x *Ticker) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Ticker) GetBestBid() string {
	if x != nil {
		return x.BestBid
	}
	return ""
}

func (x *Ticker) GetBestAsk() string {
	if x != nil {
		return x.BestAsk
	}
	return ""
}

func (x *Ticker) GetPriceChange() string {
	if x != nil {
		return x.PriceChange
	}
	return ""
}

func (x *Ticker) GetPriceChangePercent() string {
	if x != nil {
		return x.PriceChangePercent
	}
	return ""
}

func (x *Ticker) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetTickersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Ticker              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickersResponse) Reset() {
	*x = GetTickersResponse{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickersResponse) ProtoMessage() {}

func (x *GetTickersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickersResponse.ProtoReflect.Descriptor instead.
func (*GetTickersResponse) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{5}
}

func (x *GetTickersResponse) GetData() []*Ticker {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetOrderbookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument name (e.g. "BTC_USDT"). Required.
	InstrumentName string `protobuf:"bytes,1,opt,name=instrument_name,json=instrumentName,proto3" json:"instrument_name,omitempty"`
	// Depth of the orderbook (default 10, max 50).
	Depth         *int32 `protobuf:"varint,2,opt,name=depth,proto3,oneof" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderbookRequest) Reset() {
	*x = GetOrderbookRequest{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderbookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderbookRequest) ProtoMessage() {}

func (x *GetOrderbookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderbookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderbookRequest) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderbookRequest) GetInstrumentName() string {
	if x != nil {
		return x.InstrumentName
	}
	return ""
}

func (x *GetOrderbookRequest) GetDepth() int32 {
	if x != nil && x.Depth != nil {
		return *x.Depth
	}
	return 0
}

type OrderbookLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Count         string                 `protobuf:"bytes,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderbookLevel) Reset() {
	*x = OrderbookLevel{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderbookLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderbookLevel) ProtoMessage() {}

func (x *OrderbookLevel) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderbookLevel.ProtoReflect.Descriptor instead.
func (*OrderbookLevel) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{7}
}

func (x *OrderbookLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderbookLevel) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *OrderbookLevel) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

type Orderbook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*OrderbookLevel      `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*OrderbookLevel      `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orderbook) Reset() {
	*x = Orderbook{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orderbook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orderbook) ProtoMessage() {}

func (x *Orderbook) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orderbook.ProtoReflect.Descriptor instead.
func (*Orderbook) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{8}
}

func (x *Orderbook) GetBids() []*OrderbookLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Orderbook) GetAsks() []*OrderbookLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *Orderbook) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetOrderbookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Orderbook             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderbookResponse) Reset() {
	*x = GetOrderbookResponse{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderbookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderbookResponse) ProtoMessage() {}

func (x *GetOrderbookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderbookResponse.ProtoReflect.Descriptor instead.
func (*GetOrderbookResponse) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderbookResponse) GetData() *Orderbook {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCandlestickRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument name (e.g. "BTC_USDT"). Required.
	InstrumentName string `protobuf:"bytes,1,opt,name=instrument_name,json=instrumentName,proto3" json:"instrument_name,omitempty"`
	// Timeframe: 1m, 5m, 15m, 30m, 1h, 4h, 6h, 12h, 1D, 7D, 14D, 1M.
	Timeframe     *string `protobuf:"bytes,2,opt,name=timeframe,proto3,oneof" json:"timeframe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandlestickRequest) Reset() {
	*x = GetCandlestickRequest{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandlestickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlestickRequest) ProtoMessage() {}

func (x *GetCandlestickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlestickRequest.ProtoReflect.Descriptor instead.
func (*GetCandlestickRequest) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{10}
}

func (x *GetCandlestickRequest) GetInstrumentName() string {
	if x != nil {
		return x.InstrumentName
	}
	return ""
}

func (x *GetCandlestickRequest) GetTimeframe() string {
	if x != nil && x.Timeframe != nil {
		return *x.Timeframe
	}
	return ""
}

type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open          string                 `protobuf:"bytes,2,opt,name=open,proto3" json:"open,omitempty"`
	High          string                 `protobuf:"bytes,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         string                 `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        string                 `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{11}
}

func (x *Candle) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Candle) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Candle) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Candle) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Candle) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *Candle) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

type GetCandlestickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Candle              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandlestickResponse) Reset() {
	*x = GetCandlestickResponse{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandlestickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlestickResponse) ProtoMessage() {}

func (x *GetCandlestickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlestickResponse.ProtoReflect.Descriptor instead.
func (*GetCandlestickResponse) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{12}
}

func (x *GetCandlestickResponse) GetData() []*Candle {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTradesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument name (e.g. "BTC_USDT"). Required.
	InstrumentName string `protobuf:"bytes,1,opt,name=instrument_name,json=instrumentName,proto3" json:"instrument_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTradesRequest) Reset() {
	*x = GetTradesRequest{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradesRequest) ProtoMessage() {}

func (x *GetTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradesRequest.ProtoReflect.Descriptor instead.
func (*GetTradesRequest) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{13}
}

func (x *GetTradesRequest) GetInstrumentName() string {
	if x != nil {
		return x.InstrumentName
	}
	return ""
}

type Trade struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TradeId        string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	InstrumentName string                 `protobuf:"bytes,2,opt,name=instrument_name,json=instrumentName,proto3" json:"instrument_name,omitempty"`
	Side           string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`
	Price          string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity       string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Timestamp      int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{14}
}

func (x *Trade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *Trade) GetInstrumentName() string {
	if x != nil {
		return x.InstrumentName
	}
	return ""
}

func (x *Trade) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Trade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Trade) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Trade) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Trade               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradesResponse) Reset() {
	*x = GetTradesResponse{}
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradesResponse) ProtoMessage() {}

func (x *GetTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradesResponse.ProtoReflect.Descriptor instead.
func (*GetTradesResponse) Descriptor() ([]byte, []int) {
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP(), []int{15}
}

func (x *GetTradesResponse) GetData() []*Trade {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_cryptodotcom_v1_cryptodotcom_proto protoreflect.FileDescriptor

const file_cryptodotcom_v1_cryptodotcom_proto_rawDesc = "" +
	"\n" +
	"\"cryptodotcom/v1/cryptodotcom.proto\x12\x0fcryptodotcom.v1\"\x17\n" +
	"\x15GetInstrumentsRequest\"\x8b\x02\n" +
	"\n" +
	"Instrument\x12'\n" +
	"\x0finstrument_name\x18\x01 \x01(\tR\x0einstrumentName\x12%\n" +
	"\x0equote_currency\x18\x02 \x01(\tR\rquoteCurrency\x12#\n" +
	"\rbase_currency\x18\x03 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0eprice_decimals\x18\x04 \x01(\tR\rpriceDecimals\x12+\n" +
	"\x11quantity_decimals\x18\x05 \x01(\tR\x10quantityDecimals\x124\n" +
	"\x16margin_trading_enabled\x18\x06 \x01(\bR\x14marginTradingEnabled\"I\n" +
	"\x16GetInstrumentsResponse\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.cryptodotcom.v1.InstrumentR\x04data\"U\n" +
	"\x11GetTickersRequest\x12,\n" +
	"\x0finstrument_name\x18\x01 \x01(\tH\x00R\x0einstrumentName\x88\x01\x01B\x12\n" +
	"\x10_instrument_name\"\xbb\x02\n" +
	"\x06Ticker\x12'\n" +
	"\x0finstrument_name\x18\x01 \x01(\tR\x0einstrumentName\x12\x12\n" +
	"\x04high\x18\x02 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x03 \x01(\tR\x03low\x12!\n" +
	"\flatest_trade\x18\x04 \x01(\tR\vlatestTrade\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\tR\x06volume\x12\x19\n" +
	"\bbest_bid\x18\x06 \x01(\tR\abestBid\x12\x19\n" +
	"\bbest_ask\x18\a \x01(\tR\abestAsk\x12!\n" +
	"\fprice_change\x18\b \x01(\tR\vpriceChange\x120\n" +
	"\x14price_change_percent\x18\t \x01(\tR\x12priceChangePercent\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\"A\n" +
	"\x12GetTickersResponse\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.cryptodotcom.v1.TickerR\x04data\"c\n" +
	"\x13GetOrderbookRequest\x12'\n" +
	"\x0finstrument_name\x18\x01 \x01(\tR\x0einstrumentName\x12\x19\n" +
	"\x05depth\x18\x02 \x01(\x05H\x00R\x05depth\x88\x01\x01B\b\n" +
	"\x06_depth\"X\n" +
	"\x0eOrderbookLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\x12\x14\n" +
	"\x05count\x18\x03 \x01(\tR\x05count\"\x93\x01\n" +
	"\tOrderbook\x123\n" +
	"\x04bids\x18\x01 \x03(\v2\x1f.cryptodotcom.v1.OrderbookLevelR\x04bids\x123\n" +
	"\x04asks\x18\x02 \x03(\v2\x1f.cryptodotcom.v1.OrderbookLevelR\x04asks\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"F\n" +
	"\x14GetOrderbookResponse\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.cryptodotcom.v1.OrderbookR\x04data\"q\n" +
	"\x15GetCandlestickRequest\x12'\n" +
	"\x0finstrument_name\x18\x01 \x01(\tR\x0einstrumentName\x12!\n" +
	"\ttimeframe\x18\x02 \x01(\tH\x00R\ttimeframe\x88\x01\x01B\f\n" +
	"\n" +
	"_timeframe\"\x8e\x01\n" +
	"\x06Candle\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04open\x18\x02 \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\tR\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\tR\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\tR\x06volume\"E\n" +
	"\x16GetCandlestickResponse\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.cryptodotcom.v1.CandleR\x04data\";\n" +
	"\x10GetTradesRequest\x12'\n" +
	"\x0finstrument_name\x18\x01 \x01(\tR\x0einstrumentName\"\xaf\x01\n" +
	"\x05Trade\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12'\n" +
	"\x0finstrument_name\x18\x02 \x01(\tR\x0einstrumentName\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"?\n" +
	"\x11GetTradesResponse\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.cryptodotcom.v1.TradeR\x04data2\xe3\x03\n" +
	"\x13CryptoDotComService\x12a\n" +
	"\x0eGetInstruments\x12&.cryptodotcom.v1.GetInstrumentsRequest\x1a'.cryptodotcom.v1.GetInstrumentsResponse\x12U\n" +
	"\n" +
	"GetTickers\x12\".cryptodotcom.v1.GetTickersRequest\x1a#.cryptodotcom.v1.GetTickersResponse\x12[\n" +
	"\fGetOrderbook\x12$.cryptodotcom.v1.GetOrderbookRequest\x1a%.cryptodotcom.v1.GetOrderbookResponse\x12a\n" +
	"\x0eGetCandlestick\x12&.cryptodotcom.v1.GetCandlestickRequest\x1a'.cryptodotcom.v1.GetCandlestickResponse\x12R\n" +
	"\tGetTrades\x12!.cryptodotcom.v1.GetTradesRequest\x1a\".cryptodotcom.v1.GetTradesResponseB\xe0\x01\n" +
	"\x13com.cryptodotcom.v1B\x11CryptodotcomProtoP\x01ZYgithub.com/jim-technologies/invariantaf/cryptodotcom/proto/cryptodotcom/v1;cryptodotcomv1\xa2\x02\x03CXX\xaa\x02\x0fCryptodotcom.V1\xca\x02\x0fCryptodotcom\\V1\xe2\x02\x1bCryptodotcom\\V1\\GPBMetadata\xea\x02\x10Cryptodotcom::V1b\x06proto3"

var (
	file_cryptodotcom_v1_cryptodotcom_proto_rawDescOnce sync.Once
	file_cryptodotcom_v1_cryptodotcom_proto_rawDescData []byte
)

func file_cryptodotcom_v1_cryptodotcom_proto_rawDescGZIP() []byte {
	file_cryptodotcom_v1_cryptodotcom_proto_rawDescOnce.Do(func() {
		file_cryptodotcom_v1_cryptodotcom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cryptodotcom_v1_cryptodotcom_proto_rawDesc), len(file_cryptodotcom_v1_cryptodotcom_proto_rawDesc)))
	})
	return file_cryptodotcom_v1_cryptodotcom_proto_rawDescData
}

var file_cryptodotcom_v1_cryptodotcom_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_cryptodotcom_v1_cryptodotcom_proto_goTypes = []any{
	(*GetInstrumentsRequest)(nil),  // 0: cryptodotcom.v1.GetInstrumentsRequest
	(*Instrument)(nil),             // 1: cryptodotcom.v1.Instrument
	(*GetInstrumentsResponse)(nil), // 2: cryptodotcom.v1.GetInstrumentsResponse
	(*GetTickersRequest)(nil),      // 3: cryptodotcom.v1.GetTickersRequest
	(*Ticker)(nil),                 // 4: cryptodotcom.v1.Ticker
	(*GetTickersResponse)(nil),     // 5: cryptodotcom.v1.GetTickersResponse
	(*GetOrderbookRequest)(nil),    // 6: cryptodotcom.v1.GetOrderbookRequest
	(*OrderbookLevel)(nil),         // 7: cryptodotcom.v1.OrderbookLevel
	(*Orderbook)(nil),              // 8: cryptodotcom.v1.Orderbook
	(*GetOrderbookResponse)(nil),   // 9: cryptodotcom.v1.GetOrderbookResponse
	(*GetCandlestickRequest)(nil),  // 10: cryptodotcom.v1.GetCandlestickRequest
	(*Candle)(nil),                 // 11: cryptodotcom.v1.Candle
	(*GetCandlestickResponse)(nil), // 12: cryptodotcom.v1.GetCandlestickResponse
	(*GetTradesRequest)(nil),       // 13: cryptodotcom.v1.GetTradesRequest
	(*Trade)(nil),                  // 14: cryptodotcom.v1.Trade
	(*GetTradesResponse)(nil),      // 15: cryptodotcom.v1.GetTradesResponse
}
var file_cryptodotcom_v1_cryptodotcom_proto_depIdxs = []int32{
	1,  // 0: cryptodotcom.v1.GetInstrumentsResponse.data:type_name -> cryptodotcom.v1.Instrument
	4,  // 1: cryptodotcom.v1.GetTickersResponse.data:type_name -> cryptodotcom.v1.Ticker
	7,  // 2: cryptodotcom.v1.Orderbook.bids:type_name -> cryptodotcom.v1.OrderbookLevel
	7,  // 3: cryptodotcom.v1.Orderbook.asks:type_name -> cryptodotcom.v1.OrderbookLevel
	8,  // 4: cryptodotcom.v1.GetOrderbookResponse.data:type_name -> cryptodotcom.v1.Orderbook
	11, // 5: cryptodotcom.v1.GetCandlestickResponse.data:type_name -> cryptodotcom.v1.Candle
	14, // 6: cryptodotcom.v1.GetTradesResponse.data:type_name -> cryptodotcom.v1.Trade
	0,  // 7: cryptodotcom.v1.CryptoDotComService.GetInstruments:input_type -> cryptodotcom.v1.GetInstrumentsRequest
	3,  // 8: cryptodotcom.v1.CryptoDotComService.GetTickers:input_type -> cryptodotcom.v1.GetTickersRequest
	6,  // 9: cryptodotcom.v1.CryptoDotComService.GetOrderbook:input_type -> cryptodotcom.v1.GetOrderbookRequest
	10, // 10: cryptodotcom.v1.CryptoDotComService.GetCandlestick:input_type -> cryptodotcom.v1.GetCandlestickRequest
	13, // 11: cryptodotcom.v1.CryptoDotComService.GetTrades:input_type -> cryptodotcom.v1.GetTradesRequest
	2,  // 12: cryptodotcom.v1.CryptoDotComService.GetInstruments:output_type -> cryptodotcom.v1.GetInstrumentsResponse
	5,  // 13: cryptodotcom.v1.CryptoDotComService.GetTickers:output_type -> cryptodotcom.v1.GetTickersResponse
	9,  // 14: cryptodotcom.v1.CryptoDotComService.GetOrderbook:output_type -> cryptodotcom.v1.GetOrderbookResponse
	12, // 15: cryptodotcom.v1.CryptoDotComService.GetCandlestick:output_type -> cryptodotcom.v1.GetCandlestickResponse
	15, // 16: cryptodotcom.v1.CryptoDotComService.GetTrades:output_type -> cryptodotcom.v1.GetTradesResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_cryptodotcom_v1_cryptodotcom_proto_init() }
func file_cryptodotcom_v1_cryptodotcom_proto_init() {
	if File_cryptodotcom_v1_cryptodotcom_proto != nil {
		return
	}
	file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[3].OneofWrappers = []any{}
	file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[6].OneofWrappers = []any{}
	file_cryptodotcom_v1_cryptodotcom_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cryptodotcom_v1_cryptodotcom_proto_rawDesc), len(file_cryptodotcom_v1_cryptodotcom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cryptodotcom_v1_cryptodotcom_proto_goTypes,
		DependencyIndexes: file_cryptodotcom_v1_cryptodotcom_proto_depIdxs,
		MessageInfos:      file_cryptodotcom_v1_cryptodotcom_proto_msgTypes,
	}.Build()
	File_cryptodotcom_v1_cryptodotcom_proto = out.File
	file_cryptodotcom_v1_cryptodotcom_proto_goTypes = nil
	file_cryptodotcom_v1_cryptodotcom_proto_depIdxs = nil
}
