// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drift/v1/drift.proto

package driftv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to list all markets.
type ListMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsRequest) Reset() {
	*x = ListMarketsRequest{}
	mi := &file_drift_v1_drift_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsRequest) ProtoMessage() {}

func (x *ListMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsRequest.ProtoReflect.Descriptor instead.
func (*ListMarketsRequest) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{0}
}

type ListMarketsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of markets (both perp and spot).
	Markets       []*Market `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsResponse) Reset() {
	*x = ListMarketsResponse{}
	mi := &file_drift_v1_drift_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsResponse) ProtoMessage() {}

func (x *ListMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsResponse.ProtoReflect.Descriptor instead.
func (*ListMarketsResponse) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{1}
}

func (x *ListMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

// Request to get candlestick data.
type GetCandlesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Market symbol (e.g. "SOL-PERP", "BTC-PERP"). Required.
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Candle resolution: "1", "5", "15", "60", "240", "D", "W", or "M". Required.
	Resolution string `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	// Start timestamp in seconds (Unix epoch). Optional.
	StartTs int64 `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	// End timestamp in seconds (Unix epoch). Optional.
	EndTs int64 `protobuf:"varint,4,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	// Maximum number of candles to return (default 100, max 1000). Optional.
	Limit         int64 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandlesRequest) Reset() {
	*x = GetCandlesRequest{}
	mi := &file_drift_v1_drift_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesRequest) ProtoMessage() {}

func (x *GetCandlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesRequest.ProtoReflect.Descriptor instead.
func (*GetCandlesRequest) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{2}
}

func (x *GetCandlesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetCandlesRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *GetCandlesRequest) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *GetCandlesRequest) GetEndTs() int64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *GetCandlesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCandlesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of candlestick bars.
	Candles       []*Candle `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandlesResponse) Reset() {
	*x = GetCandlesResponse{}
	mi := &file_drift_v1_drift_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesResponse) ProtoMessage() {}

func (x *GetCandlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesResponse.ProtoReflect.Descriptor instead.
func (*GetCandlesResponse) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{3}
}

func (x *GetCandlesResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

// Request to get recent trades.
type GetTradesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Market symbol (e.g. "SOL-PERP", "BTC-PERP"). Required.
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Pagination cursor from a previous response. Optional.
	Page string `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	// Maximum number of trades to return (default 20, max 50). Optional.
	Limit         int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradesRequest) Reset() {
	*x = GetTradesRequest{}
	mi := &file_drift_v1_drift_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradesRequest) ProtoMessage() {}

func (x *GetTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradesRequest.ProtoReflect.Descriptor instead.
func (*GetTradesRequest) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{4}
}

func (x *GetTradesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTradesRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *GetTradesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTradesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of trade records.
	Trades        []*Trade `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradesResponse) Reset() {
	*x = GetTradesResponse{}
	mi := &file_drift_v1_drift_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradesResponse) ProtoMessage() {}

func (x *GetTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradesResponse.ProtoReflect.Descriptor instead.
func (*GetTradesResponse) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{5}
}

func (x *GetTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// Request to get funding rate history.
type GetFundingRatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Market symbol (e.g. "SOL-PERP", "BTC-PERP"). Required.
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Pagination cursor from a previous response. Optional.
	Page string `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	// Maximum number of records to return (default 20, max 750). Optional.
	Limit         int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundingRatesRequest) Reset() {
	*x = GetFundingRatesRequest{}
	mi := &file_drift_v1_drift_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundingRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRatesRequest) ProtoMessage() {}

func (x *GetFundingRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRatesRequest.ProtoReflect.Descriptor instead.
func (*GetFundingRatesRequest) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{6}
}

func (x *GetFundingRatesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetFundingRatesRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *GetFundingRatesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFundingRatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of funding rate records.
	Records       []*FundingRateRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundingRatesResponse) Reset() {
	*x = GetFundingRatesResponse{}
	mi := &file_drift_v1_drift_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundingRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRatesResponse) ProtoMessage() {}

func (x *GetFundingRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRatesResponse.ProtoReflect.Descriptor instead.
func (*GetFundingRatesResponse) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{7}
}

func (x *GetFundingRatesResponse) GetRecords() []*FundingRateRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// Request to get aggregated funding rate stats.
type GetFundingRateStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundingRateStatsRequest) Reset() {
	*x = GetFundingRateStatsRequest{}
	mi := &file_drift_v1_drift_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundingRateStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRateStatsRequest) ProtoMessage() {}

func (x *GetFundingRateStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRateStatsRequest.ProtoReflect.Descriptor instead.
func (*GetFundingRateStatsRequest) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{8}
}

type GetFundingRateStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Funding rate statistics per market.
	Markets       []*FundingRateStats `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundingRateStatsResponse) Reset() {
	*x = GetFundingRateStatsResponse{}
	mi := &file_drift_v1_drift_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundingRateStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRateStatsResponse) ProtoMessage() {}

func (x *GetFundingRateStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRateStatsResponse.ProtoReflect.Descriptor instead.
func (*GetFundingRateStatsResponse) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{9}
}

func (x *GetFundingRateStatsResponse) GetMarkets() []*FundingRateStats {
	if x != nil {
		return x.Markets
	}
	return nil
}

// A Drift market with live stats.
type Market struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Market symbol (e.g. "SOL-PERP", "BTC-PERP", "SOL").
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Numeric market index on the Drift program.
	MarketIndex int64 `protobuf:"varint,2,opt,name=market_index,json=marketIndex,proto3" json:"market_index,omitempty"`
	// Market type: "perp" or "spot".
	MarketType string `protobuf:"bytes,3,opt,name=market_type,json=marketType,proto3" json:"market_type,omitempty"`
	// Base asset symbol (e.g. "SOL", "BTC").
	BaseAsset string `protobuf:"bytes,4,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	// Quote asset symbol (e.g. "USDC").
	QuoteAsset string `protobuf:"bytes,5,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	// Market status (e.g. "active").
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Current oracle price (USD).
	OraclePrice string `protobuf:"bytes,7,opt,name=oracle_price,json=oraclePrice,proto3" json:"oracle_price,omitempty"`
	// Current mark price (USD).
	MarkPrice string `protobuf:"bytes,8,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	// 24h base volume.
	BaseVolume string `protobuf:"bytes,9,opt,name=base_volume,json=baseVolume,proto3" json:"base_volume,omitempty"`
	// 24h quote volume (USD).
	QuoteVolume string `protobuf:"bytes,10,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`
	// Long open interest.
	OpenInterestLong string `protobuf:"bytes,11,opt,name=open_interest_long,json=openInterestLong,proto3" json:"open_interest_long,omitempty"`
	// Short open interest.
	OpenInterestShort string `protobuf:"bytes,12,opt,name=open_interest_short,json=openInterestShort,proto3" json:"open_interest_short,omitempty"`
	// Funding rate for longs.
	FundingRateLong string `protobuf:"bytes,13,opt,name=funding_rate_long,json=fundingRateLong,proto3" json:"funding_rate_long,omitempty"`
	// Funding rate for shorts.
	FundingRateShort string `protobuf:"bytes,14,opt,name=funding_rate_short,json=fundingRateShort,proto3" json:"funding_rate_short,omitempty"`
	// Average 24h funding rate.
	FundingRate_24H string `protobuf:"bytes,15,opt,name=funding_rate_24h,json=fundingRate24h,proto3" json:"funding_rate_24h,omitempty"`
	// Last fill price.
	Price string `protobuf:"bytes,16,opt,name=price,proto3" json:"price,omitempty"`
	// 24h price change (absolute).
	PriceChange_24H string `protobuf:"bytes,17,opt,name=price_change_24h,json=priceChange24h,proto3" json:"price_change_24h,omitempty"`
	// 24h price change (percentage).
	PriceChange_24HPercent string `protobuf:"bytes,18,opt,name=price_change_24h_percent,json=priceChange24hPercent,proto3" json:"price_change_24h_percent,omitempty"`
	// Maker fee rate (negative means rebate).
	MakerFee float64 `protobuf:"fixed64,19,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	// Taker fee rate.
	TakerFee      float64 `protobuf:"fixed64,20,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_drift_v1_drift_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{10}
}

func (x *Market) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Market) GetMarketIndex() int64 {
	if x != nil {
		return x.MarketIndex
	}
	return 0
}

func (x *Market) GetMarketType() string {
	if x != nil {
		return x.MarketType
	}
	return ""
}

func (x *Market) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *Market) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *Market) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Market) GetOraclePrice() string {
	if x != nil {
		return x.OraclePrice
	}
	return ""
}

func (x *Market) GetMarkPrice() string {
	if x != nil {
		return x.MarkPrice
	}
	return ""
}

func (x *Market) GetBaseVolume() string {
	if x != nil {
		return x.BaseVolume
	}
	return ""
}

func (x *Market) GetQuoteVolume() string {
	if x != nil {
		return x.QuoteVolume
	}
	return ""
}

func (x *Market) GetOpenInterestLong() string {
	if x != nil {
		return x.OpenInterestLong
	}
	return ""
}

func (x *Market) GetOpenInterestShort() string {
	if x != nil {
		return x.OpenInterestShort
	}
	return ""
}

func (x *Market) GetFundingRateLong() string {
	if x != nil {
		return x.FundingRateLong
	}
	return ""
}

func (x *Market) GetFundingRateShort() string {
	if x != nil {
		return x.FundingRateShort
	}
	return ""
}

func (x *Market) GetFundingRate_24H() string {
	if x != nil {
		return x.FundingRate_24H
	}
	return ""
}

func (x *Market) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Market) GetPriceChange_24H() string {
	if x != nil {
		return x.PriceChange_24H
	}
	return ""
}

func (x *Market) GetPriceChange_24HPercent() string {
	if x != nil {
		return x.PriceChange_24HPercent
	}
	return ""
}

func (x *Market) GetMakerFee() float64 {
	if x != nil {
		return x.MakerFee
	}
	return 0
}

func (x *Market) GetTakerFee() float64 {
	if x != nil {
		return x.TakerFee
	}
	return 0
}

// A single OHLCV candlestick bar.
type Candle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Candle open timestamp (Unix seconds).
	Ts int64 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	// Fill-based open price.
	FillOpen float64 `protobuf:"fixed64,2,opt,name=fill_open,json=fillOpen,proto3" json:"fill_open,omitempty"`
	// Fill-based high price.
	FillHigh float64 `protobuf:"fixed64,3,opt,name=fill_high,json=fillHigh,proto3" json:"fill_high,omitempty"`
	// Fill-based low price.
	FillLow float64 `protobuf:"fixed64,4,opt,name=fill_low,json=fillLow,proto3" json:"fill_low,omitempty"`
	// Fill-based close price.
	FillClose float64 `protobuf:"fixed64,5,opt,name=fill_close,json=fillClose,proto3" json:"fill_close,omitempty"`
	// Oracle-based open price.
	OracleOpen float64 `protobuf:"fixed64,6,opt,name=oracle_open,json=oracleOpen,proto3" json:"oracle_open,omitempty"`
	// Oracle-based high price.
	OracleHigh float64 `protobuf:"fixed64,7,opt,name=oracle_high,json=oracleHigh,proto3" json:"oracle_high,omitempty"`
	// Oracle-based low price.
	OracleLow float64 `protobuf:"fixed64,8,opt,name=oracle_low,json=oracleLow,proto3" json:"oracle_low,omitempty"`
	// Oracle-based close price.
	OracleClose float64 `protobuf:"fixed64,9,opt,name=oracle_close,json=oracleClose,proto3" json:"oracle_close,omitempty"`
	// Quote volume in USD.
	QuoteVolume float64 `protobuf:"fixed64,10,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`
	// Base volume in base asset units.
	BaseVolume    float64 `protobuf:"fixed64,11,opt,name=base_volume,json=baseVolume,proto3" json:"base_volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_drift_v1_drift_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{11}
}

func (x *Candle) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Candle) GetFillOpen() float64 {
	if x != nil {
		return x.FillOpen
	}
	return 0
}

func (x *Candle) GetFillHigh() float64 {
	if x != nil {
		return x.FillHigh
	}
	return 0
}

func (x *Candle) GetFillLow() float64 {
	if x != nil {
		return x.FillLow
	}
	return 0
}

func (x *Candle) GetFillClose() float64 {
	if x != nil {
		return x.FillClose
	}
	return 0
}

func (x *Candle) GetOracleOpen() float64 {
	if x != nil {
		return x.OracleOpen
	}
	return 0
}

func (x *Candle) GetOracleHigh() float64 {
	if x != nil {
		return x.OracleHigh
	}
	return 0
}

func (x *Candle) GetOracleLow() float64 {
	if x != nil {
		return x.OracleLow
	}
	return 0
}

func (x *Candle) GetOracleClose() float64 {
	if x != nil {
		return x.OracleClose
	}
	return 0
}

func (x *Candle) GetQuoteVolume() float64 {
	if x != nil {
		return x.QuoteVolume
	}
	return 0
}

func (x *Candle) GetBaseVolume() float64 {
	if x != nil {
		return x.BaseVolume
	}
	return 0
}

// A single trade/fill record.
type Trade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trade timestamp (Unix seconds).
	Ts int64 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	// Transaction signature on Solana.
	TxSig string `protobuf:"bytes,2,opt,name=tx_sig,json=txSig,proto3" json:"tx_sig,omitempty"`
	// Base asset amount filled.
	BaseAssetAmountFilled string `protobuf:"bytes,3,opt,name=base_asset_amount_filled,json=baseAssetAmountFilled,proto3" json:"base_asset_amount_filled,omitempty"`
	// Quote asset amount filled (USD).
	QuoteAssetAmountFilled string `protobuf:"bytes,4,opt,name=quote_asset_amount_filled,json=quoteAssetAmountFilled,proto3" json:"quote_asset_amount_filled,omitempty"`
	// Taker fee.
	TakerFee string `protobuf:"bytes,5,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	// Maker rebate.
	MakerRebate string `protobuf:"bytes,6,opt,name=maker_rebate,json=makerRebate,proto3" json:"maker_rebate,omitempty"`
	// Oracle price at the time of trade.
	OraclePrice string `protobuf:"bytes,7,opt,name=oracle_price,json=oraclePrice,proto3" json:"oracle_price,omitempty"`
	// Trade action (e.g. "fill").
	Action string `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	// Taker order direction ("long" or "short").
	TakerOrderDirection string `protobuf:"bytes,9,opt,name=taker_order_direction,json=takerOrderDirection,proto3" json:"taker_order_direction,omitempty"`
	// Maker order direction ("long" or "short").
	MakerOrderDirection string `protobuf:"bytes,10,opt,name=maker_order_direction,json=makerOrderDirection,proto3" json:"maker_order_direction,omitempty"`
	// Market symbol.
	Symbol        string `protobuf:"bytes,11,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_drift_v1_drift_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{12}
}

func (x *Trade) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Trade) GetTxSig() string {
	if x != nil {
		return x.TxSig
	}
	return ""
}

func (x *Trade) GetBaseAssetAmountFilled() string {
	if x != nil {
		return x.BaseAssetAmountFilled
	}
	return ""
}

func (x *Trade) GetQuoteAssetAmountFilled() string {
	if x != nil {
		return x.QuoteAssetAmountFilled
	}
	return ""
}

func (x *Trade) GetTakerFee() string {
	if x != nil {
		return x.TakerFee
	}
	return ""
}

func (x *Trade) GetMakerRebate() string {
	if x != nil {
		return x.MakerRebate
	}
	return ""
}

func (x *Trade) GetOraclePrice() string {
	if x != nil {
		return x.OraclePrice
	}
	return ""
}

func (x *Trade) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Trade) GetTakerOrderDirection() string {
	if x != nil {
		return x.TakerOrderDirection
	}
	return ""
}

func (x *Trade) GetMakerOrderDirection() string {
	if x != nil {
		return x.MakerOrderDirection
	}
	return ""
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// A single funding rate update record.
type FundingRateRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Record timestamp (Unix seconds).
	Ts int64 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	// Transaction signature on Solana.
	TxSig string `protobuf:"bytes,2,opt,name=tx_sig,json=txSig,proto3" json:"tx_sig,omitempty"`
	// Record ID.
	RecordId int64 `protobuf:"varint,3,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	// Market index.
	MarketIndex int64 `protobuf:"varint,4,opt,name=market_index,json=marketIndex,proto3" json:"market_index,omitempty"`
	// Market symbol.
	Symbol string `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Funding rate (combined).
	FundingRate string `protobuf:"bytes,6,opt,name=funding_rate,json=fundingRate,proto3" json:"funding_rate,omitempty"`
	// Funding rate for longs.
	FundingRateLong string `protobuf:"bytes,7,opt,name=funding_rate_long,json=fundingRateLong,proto3" json:"funding_rate_long,omitempty"`
	// Funding rate for shorts.
	FundingRateShort string `protobuf:"bytes,8,opt,name=funding_rate_short,json=fundingRateShort,proto3" json:"funding_rate_short,omitempty"`
	// Cumulative funding rate for longs.
	CumulativeFundingRateLong string `protobuf:"bytes,9,opt,name=cumulative_funding_rate_long,json=cumulativeFundingRateLong,proto3" json:"cumulative_funding_rate_long,omitempty"`
	// Cumulative funding rate for shorts.
	CumulativeFundingRateShort string `protobuf:"bytes,10,opt,name=cumulative_funding_rate_short,json=cumulativeFundingRateShort,proto3" json:"cumulative_funding_rate_short,omitempty"`
	// Oracle price TWAP.
	OraclePriceTwap string `protobuf:"bytes,11,opt,name=oracle_price_twap,json=oraclePriceTwap,proto3" json:"oracle_price_twap,omitempty"`
	// Mark price TWAP.
	MarkPriceTwap string `protobuf:"bytes,12,opt,name=mark_price_twap,json=markPriceTwap,proto3" json:"mark_price_twap,omitempty"`
	// Period revenue.
	PeriodRevenue string `protobuf:"bytes,13,opt,name=period_revenue,json=periodRevenue,proto3" json:"period_revenue,omitempty"`
	// Base asset amount with AMM.
	BaseAssetAmountWithAmm string `protobuf:"bytes,14,opt,name=base_asset_amount_with_amm,json=baseAssetAmountWithAmm,proto3" json:"base_asset_amount_with_amm,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FundingRateRecord) Reset() {
	*x = FundingRateRecord{}
	mi := &file_drift_v1_drift_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingRateRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingRateRecord) ProtoMessage() {}

func (x *FundingRateRecord) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingRateRecord.ProtoReflect.Descriptor instead.
func (*FundingRateRecord) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{13}
}

func (x *FundingRateRecord) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *FundingRateRecord) GetTxSig() string {
	if x != nil {
		return x.TxSig
	}
	return ""
}

func (x *FundingRateRecord) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *FundingRateRecord) GetMarketIndex() int64 {
	if x != nil {
		return x.MarketIndex
	}
	return 0
}

func (x *FundingRateRecord) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FundingRateRecord) GetFundingRate() string {
	if x != nil {
		return x.FundingRate
	}
	return ""
}

func (x *FundingRateRecord) GetFundingRateLong() string {
	if x != nil {
		return x.FundingRateLong
	}
	return ""
}

func (x *FundingRateRecord) GetFundingRateShort() string {
	if x != nil {
		return x.FundingRateShort
	}
	return ""
}

func (x *FundingRateRecord) GetCumulativeFundingRateLong() string {
	if x != nil {
		return x.CumulativeFundingRateLong
	}
	return ""
}

func (x *FundingRateRecord) GetCumulativeFundingRateShort() string {
	if x != nil {
		return x.CumulativeFundingRateShort
	}
	return ""
}

func (x *FundingRateRecord) GetOraclePriceTwap() string {
	if x != nil {
		return x.OraclePriceTwap
	}
	return ""
}

func (x *FundingRateRecord) GetMarkPriceTwap() string {
	if x != nil {
		return x.MarkPriceTwap
	}
	return ""
}

func (x *FundingRateRecord) GetPeriodRevenue() string {
	if x != nil {
		return x.PeriodRevenue
	}
	return ""
}

func (x *FundingRateRecord) GetBaseAssetAmountWithAmm() string {
	if x != nil {
		return x.BaseAssetAmountWithAmm
	}
	return ""
}

// Aggregated funding rate statistics for a market.
type FundingRateStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Market index.
	MarketIndex int64 `protobuf:"varint,1,opt,name=market_index,json=marketIndex,proto3" json:"market_index,omitempty"`
	// Market symbol (e.g. "SOL-PERP").
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Average annualized funding rate over 24 hours.
	Rate_24H string `protobuf:"bytes,3,opt,name=rate_24h,json=rate24h,proto3" json:"rate_24h,omitempty"`
	// Average annualized funding rate over 7 days.
	Rate_7D string `protobuf:"bytes,4,opt,name=rate_7d,json=rate7d,proto3" json:"rate_7d,omitempty"`
	// Average annualized funding rate over 30 days.
	Rate_30D string `protobuf:"bytes,5,opt,name=rate_30d,json=rate30d,proto3" json:"rate_30d,omitempty"`
	// Average annualized funding rate over 1 year.
	Rate_1Y       string `protobuf:"bytes,6,opt,name=rate_1y,json=rate1y,proto3" json:"rate_1y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundingRateStats) Reset() {
	*x = FundingRateStats{}
	mi := &file_drift_v1_drift_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingRateStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingRateStats) ProtoMessage() {}

func (x *FundingRateStats) ProtoReflect() protoreflect.Message {
	mi := &file_drift_v1_drift_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingRateStats.ProtoReflect.Descriptor instead.
func (*FundingRateStats) Descriptor() ([]byte, []int) {
	return file_drift_v1_drift_proto_rawDescGZIP(), []int{14}
}

func (x *FundingRateStats) GetMarketIndex() int64 {
	if x != nil {
		return x.MarketIndex
	}
	return 0
}

func (x *FundingRateStats) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FundingRateStats) GetRate_24H() string {
	if x != nil {
		return x.Rate_24H
	}
	return ""
}

func (x *FundingRateStats) GetRate_7D() string {
	if x != nil {
		return x.Rate_7D
	}
	return ""
}

func (x *FundingRateStats) GetRate_30D() string {
	if x != nil {
		return x.Rate_30D
	}
	return ""
}

func (x *FundingRateStats) GetRate_1Y() string {
	if x != nil {
		return x.Rate_1Y
	}
	return ""
}

var File_drift_v1_drift_proto protoreflect.FileDescriptor

const file_drift_v1_drift_proto_rawDesc = "" +
	"\n" +
	"\x14drift/v1/drift.proto\x12\bdrift.v1\"\x14\n" +
	"\x12ListMarketsRequest\"A\n" +
	"\x13ListMarketsResponse\x12*\n" +
	"\amarkets\x18\x01 \x03(\v2\x10.drift.v1.MarketR\amarkets\"\x93\x01\n" +
	"\x11GetCandlesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12\x19\n" +
	"\bstart_ts\x18\x03 \x01(\x03R\astartTs\x12\x15\n" +
	"\x06end_ts\x18\x04 \x01(\x03R\x05endTs\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\"@\n" +
	"\x12GetCandlesResponse\x12*\n" +
	"\acandles\x18\x01 \x03(\v2\x10.drift.v1.CandleR\acandles\"T\n" +
	"\x10GetTradesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04page\x18\x02 \x01(\tR\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"<\n" +
	"\x11GetTradesResponse\x12'\n" +
	"\x06trades\x18\x01 \x03(\v2\x0f.drift.v1.TradeR\x06trades\"Z\n" +
	"\x16GetFundingRatesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04page\x18\x02 \x01(\tR\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"P\n" +
	"\x17GetFundingRatesResponse\x125\n" +
	"\arecords\x18\x01 \x03(\v2\x1b.drift.v1.FundingRateRecordR\arecords\"\x1c\n" +
	"\x1aGetFundingRateStatsRequest\"S\n" +
	"\x1bGetFundingRateStatsResponse\x124\n" +
	"\amarkets\x18\x01 \x03(\v2\x1a.drift.v1.FundingRateStatsR\amarkets\"\xd7\x05\n" +
	"\x06Market\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\fmarket_index\x18\x02 \x01(\x03R\vmarketIndex\x12\x1f\n" +
	"\vmarket_type\x18\x03 \x01(\tR\n" +
	"marketType\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x04 \x01(\tR\tbaseAsset\x12\x1f\n" +
	"\vquote_asset\x18\x05 \x01(\tR\n" +
	"quoteAsset\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12!\n" +
	"\foracle_price\x18\a \x01(\tR\voraclePrice\x12\x1d\n" +
	"\n" +
	"mark_price\x18\b \x01(\tR\tmarkPrice\x12\x1f\n" +
	"\vbase_volume\x18\t \x01(\tR\n" +
	"baseVolume\x12!\n" +
	"\fquote_volume\x18\n" +
	" \x01(\tR\vquoteVolume\x12,\n" +
	"\x12open_interest_long\x18\v \x01(\tR\x10openInterestLong\x12.\n" +
	"\x13open_interest_short\x18\f \x01(\tR\x11openInterestShort\x12*\n" +
	"\x11funding_rate_long\x18\r \x01(\tR\x0ffundingRateLong\x12,\n" +
	"\x12funding_rate_short\x18\x0e \x01(\tR\x10fundingRateShort\x12(\n" +
	"\x10funding_rate_24h\x18\x0f \x01(\tR\x0efundingRate24h\x12\x14\n" +
	"\x05price\x18\x10 \x01(\tR\x05price\x12(\n" +
	"\x10price_change_24h\x18\x11 \x01(\tR\x0epriceChange24h\x127\n" +
	"\x18price_change_24h_percent\x18\x12 \x01(\tR\x15priceChange24hPercent\x12\x1b\n" +
	"\tmaker_fee\x18\x13 \x01(\x01R\bmakerFee\x12\x1b\n" +
	"\ttaker_fee\x18\x14 \x01(\x01R\btakerFee\"\xd4\x02\n" +
	"\x06Candle\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x1b\n" +
	"\tfill_open\x18\x02 \x01(\x01R\bfillOpen\x12\x1b\n" +
	"\tfill_high\x18\x03 \x01(\x01R\bfillHigh\x12\x19\n" +
	"\bfill_low\x18\x04 \x01(\x01R\afillLow\x12\x1d\n" +
	"\n" +
	"fill_close\x18\x05 \x01(\x01R\tfillClose\x12\x1f\n" +
	"\voracle_open\x18\x06 \x01(\x01R\n" +
	"oracleOpen\x12\x1f\n" +
	"\voracle_high\x18\a \x01(\x01R\n" +
	"oracleHigh\x12\x1d\n" +
	"\n" +
	"oracle_low\x18\b \x01(\x01R\toracleLow\x12!\n" +
	"\foracle_close\x18\t \x01(\x01R\voracleClose\x12!\n" +
	"\fquote_volume\x18\n" +
	" \x01(\x01R\vquoteVolume\x12\x1f\n" +
	"\vbase_volume\x18\v \x01(\x01R\n" +
	"baseVolume\"\x9d\x03\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x15\n" +
	"\x06tx_sig\x18\x02 \x01(\tR\x05txSig\x127\n" +
	"\x18base_asset_amount_filled\x18\x03 \x01(\tR\x15baseAssetAmountFilled\x129\n" +
	"\x19quote_asset_amount_filled\x18\x04 \x01(\tR\x16quoteAssetAmountFilled\x12\x1b\n" +
	"\ttaker_fee\x18\x05 \x01(\tR\btakerFee\x12!\n" +
	"\fmaker_rebate\x18\x06 \x01(\tR\vmakerRebate\x12!\n" +
	"\foracle_price\x18\a \x01(\tR\voraclePrice\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\x122\n" +
	"\x15taker_order_direction\x18\t \x01(\tR\x13takerOrderDirection\x122\n" +
	"\x15maker_order_direction\x18\n" +
	" \x01(\tR\x13makerOrderDirection\x12\x16\n" +
	"\x06symbol\x18\v \x01(\tR\x06symbol\"\xca\x04\n" +
	"\x11FundingRateRecord\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x15\n" +
	"\x06tx_sig\x18\x02 \x01(\tR\x05txSig\x12\x1b\n" +
	"\trecord_id\x18\x03 \x01(\x03R\brecordId\x12!\n" +
	"\fmarket_index\x18\x04 \x01(\x03R\vmarketIndex\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12!\n" +
	"\ffunding_rate\x18\x06 \x01(\tR\vfundingRate\x12*\n" +
	"\x11funding_rate_long\x18\a \x01(\tR\x0ffundingRateLong\x12,\n" +
	"\x12funding_rate_short\x18\b \x01(\tR\x10fundingRateShort\x12?\n" +
	"\x1ccumulative_funding_rate_long\x18\t \x01(\tR\x19cumulativeFundingRateLong\x12A\n" +
	"\x1dcumulative_funding_rate_short\x18\n" +
	" \x01(\tR\x1acumulativeFundingRateShort\x12*\n" +
	"\x11oracle_price_twap\x18\v \x01(\tR\x0foraclePriceTwap\x12&\n" +
	"\x0fmark_price_twap\x18\f \x01(\tR\rmarkPriceTwap\x12%\n" +
	"\x0eperiod_revenue\x18\r \x01(\tR\rperiodRevenue\x12:\n" +
	"\x1abase_asset_amount_with_amm\x18\x0e \x01(\tR\x16baseAssetAmountWithAmm\"\xb5\x01\n" +
	"\x10FundingRateStats\x12!\n" +
	"\fmarket_index\x18\x01 \x01(\x03R\vmarketIndex\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x19\n" +
	"\brate_24h\x18\x03 \x01(\tR\arate24h\x12\x17\n" +
	"\arate_7d\x18\x04 \x01(\tR\x06rate7d\x12\x19\n" +
	"\brate_30d\x18\x05 \x01(\tR\arate30d\x12\x17\n" +
	"\arate_1y\x18\x06 \x01(\tR\x06rate1y2\xa5\x03\n" +
	"\fDriftService\x12J\n" +
	"\vListMarkets\x12\x1c.drift.v1.ListMarketsRequest\x1a\x1d.drift.v1.ListMarketsResponse\x12G\n" +
	"\n" +
	"GetCandles\x12\x1b.drift.v1.GetCandlesRequest\x1a\x1c.drift.v1.GetCandlesResponse\x12D\n" +
	"\tGetTrades\x12\x1a.drift.v1.GetTradesRequest\x1a\x1b.drift.v1.GetTradesResponse\x12V\n" +
	"\x0fGetFundingRates\x12 .drift.v1.GetFundingRatesRequest\x1a!.drift.v1.GetFundingRatesResponse\x12b\n" +
	"\x13GetFundingRateStats\x12$.drift.v1.GetFundingRateStatsRequest\x1a%.drift.v1.GetFundingRateStatsResponseB\xa1\x01\n" +
	"\fcom.drift.v1B\n" +
	"DriftProtoP\x01ZDgithub.com/jim-technologies/invariantaf/drift/proto/drift/v1;driftv1\xa2\x02\x03DXX\xaa\x02\bDrift.V1\xca\x02\bDrift\\V1\xe2\x02\x14Drift\\V1\\GPBMetadata\xea\x02\tDrift::V1b\x06proto3"

var (
	file_drift_v1_drift_proto_rawDescOnce sync.Once
	file_drift_v1_drift_proto_rawDescData []byte
)

func file_drift_v1_drift_proto_rawDescGZIP() []byte {
	file_drift_v1_drift_proto_rawDescOnce.Do(func() {
		file_drift_v1_drift_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drift_v1_drift_proto_rawDesc), len(file_drift_v1_drift_proto_rawDesc)))
	})
	return file_drift_v1_drift_proto_rawDescData
}

var file_drift_v1_drift_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_drift_v1_drift_proto_goTypes = []any{
	(*ListMarketsRequest)(nil),          // 0: drift.v1.ListMarketsRequest
	(*ListMarketsResponse)(nil),         // 1: drift.v1.ListMarketsResponse
	(*GetCandlesRequest)(nil),           // 2: drift.v1.GetCandlesRequest
	(*GetCandlesResponse)(nil),          // 3: drift.v1.GetCandlesResponse
	(*GetTradesRequest)(nil),            // 4: drift.v1.GetTradesRequest
	(*GetTradesResponse)(nil),           // 5: drift.v1.GetTradesResponse
	(*GetFundingRatesRequest)(nil),      // 6: drift.v1.GetFundingRatesRequest
	(*GetFundingRatesResponse)(nil),     // 7: drift.v1.GetFundingRatesResponse
	(*GetFundingRateStatsRequest)(nil),  // 8: drift.v1.GetFundingRateStatsRequest
	(*GetFundingRateStatsResponse)(nil), // 9: drift.v1.GetFundingRateStatsResponse
	(*Market)(nil),                      // 10: drift.v1.Market
	(*Candle)(nil),                      // 11: drift.v1.Candle
	(*Trade)(nil),                       // 12: drift.v1.Trade
	(*FundingRateRecord)(nil),           // 13: drift.v1.FundingRateRecord
	(*FundingRateStats)(nil),            // 14: drift.v1.FundingRateStats
}
var file_drift_v1_drift_proto_depIdxs = []int32{
	10, // 0: drift.v1.ListMarketsResponse.markets:type_name -> drift.v1.Market
	11, // 1: drift.v1.GetCandlesResponse.candles:type_name -> drift.v1.Candle
	12, // 2: drift.v1.GetTradesResponse.trades:type_name -> drift.v1.Trade
	13, // 3: drift.v1.GetFundingRatesResponse.records:type_name -> drift.v1.FundingRateRecord
	14, // 4: drift.v1.GetFundingRateStatsResponse.markets:type_name -> drift.v1.FundingRateStats
	0,  // 5: drift.v1.DriftService.ListMarkets:input_type -> drift.v1.ListMarketsRequest
	2,  // 6: drift.v1.DriftService.GetCandles:input_type -> drift.v1.GetCandlesRequest
	4,  // 7: drift.v1.DriftService.GetTrades:input_type -> drift.v1.GetTradesRequest
	6,  // 8: drift.v1.DriftService.GetFundingRates:input_type -> drift.v1.GetFundingRatesRequest
	8,  // 9: drift.v1.DriftService.GetFundingRateStats:input_type -> drift.v1.GetFundingRateStatsRequest
	1,  // 10: drift.v1.DriftService.ListMarkets:output_type -> drift.v1.ListMarketsResponse
	3,  // 11: drift.v1.DriftService.GetCandles:output_type -> drift.v1.GetCandlesResponse
	5,  // 12: drift.v1.DriftService.GetTrades:output_type -> drift.v1.GetTradesResponse
	7,  // 13: drift.v1.DriftService.GetFundingRates:output_type -> drift.v1.GetFundingRatesResponse
	9,  // 14: drift.v1.DriftService.GetFundingRateStats:output_type -> drift.v1.GetFundingRateStatsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_drift_v1_drift_proto_init() }
func file_drift_v1_drift_proto_init() {
	if File_drift_v1_drift_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drift_v1_drift_proto_rawDesc), len(file_drift_v1_drift_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drift_v1_drift_proto_goTypes,
		DependencyIndexes: file_drift_v1_drift_proto_depIdxs,
		MessageInfos:      file_drift_v1_drift_proto_msgTypes,
	}.Build()
	File_drift_v1_drift_proto = out.File
	file_drift_v1_drift_proto_goTypes = nil
	file_drift_v1_drift_proto_depIdxs = nil
}
