// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: unsplash/v1/unsplash.proto

package unsplashpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Photo represents a single photo from the Unsplash API.
type Photo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique Unsplash identifier for this photo (e.g., "Dwu85P9SOIk").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The date this photo was created (ISO 8601 format).
	CreatedAt string `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The date this photo was last updated (ISO 8601 format).
	UpdatedAt string `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Width of the photo in pixels.
	Width int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	// Height of the photo in pixels.
	Height int32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	// A brief text description of the photo.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// An alternative text description for accessibility.
	AltDescription string `protobuf:"bytes,7,opt,name=alt_description,json=altDescription,proto3" json:"alt_description,omitempty"`
	// The photo's image URLs in various sizes.
	Urls *PhotoUrls `protobuf:"bytes,8,opt,name=urls,proto3" json:"urls,omitempty"`
	// Number of times this photo has been liked.
	Likes int32 `protobuf:"varint,9,opt,name=likes,proto3" json:"likes,omitempty"`
	// The photographer who uploaded this photo.
	User *User `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`
	// The photo's color as a hex string (e.g., "#6E633A").
	Color string `protobuf:"bytes,11,opt,name=color,proto3" json:"color,omitempty"`
	// Number of times this photo has been downloaded.
	Downloads int32 `protobuf:"varint,12,opt,name=downloads,proto3" json:"downloads,omitempty"`
	// Number of times this photo has been viewed.
	Views int32 `protobuf:"varint,13,opt,name=views,proto3" json:"views,omitempty"`
	// EXIF metadata (camera, lens, settings).
	Exif *Exif `protobuf:"bytes,14,opt,name=exif,proto3" json:"exif,omitempty"`
	// Location where the photo was taken.
	Location *Location `protobuf:"bytes,15,opt,name=location,proto3" json:"location,omitempty"`
	// Tags associated with the photo.
	Tags          []*Tag `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Photo) Reset() {
	*x = Photo{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{0}
}

func (x *Photo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Photo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Photo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Photo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Photo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Photo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Photo) GetAltDescription() string {
	if x != nil {
		return x.AltDescription
	}
	return ""
}

func (x *Photo) GetUrls() *PhotoUrls {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *Photo) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Photo) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Photo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Photo) GetDownloads() int32 {
	if x != nil {
		return x.Downloads
	}
	return 0
}

func (x *Photo) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *Photo) GetExif() *Exif {
	if x != nil {
		return x.Exif
	}
	return nil
}

func (x *Photo) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Photo) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// PhotoUrls contains URLs for various renditions of a photo.
type PhotoUrls struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw image URL with no size constraints. Append query params to resize.
	Raw string `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	// Full-resolution image URL.
	Full string `protobuf:"bytes,2,opt,name=full,proto3" json:"full,omitempty"`
	// Regular-size image URL (width 1080px).
	Regular string `protobuf:"bytes,3,opt,name=regular,proto3" json:"regular,omitempty"`
	// Small image URL (width 400px).
	Small string `protobuf:"bytes,4,opt,name=small,proto3" json:"small,omitempty"`
	// Thumbnail image URL (width 200px).
	Thumb         string `protobuf:"bytes,5,opt,name=thumb,proto3" json:"thumb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoUrls) Reset() {
	*x = PhotoUrls{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoUrls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoUrls) ProtoMessage() {}

func (x *PhotoUrls) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoUrls.ProtoReflect.Descriptor instead.
func (*PhotoUrls) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{1}
}

func (x *PhotoUrls) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *PhotoUrls) GetFull() string {
	if x != nil {
		return x.Full
	}
	return ""
}

func (x *PhotoUrls) GetRegular() string {
	if x != nil {
		return x.Regular
	}
	return ""
}

func (x *PhotoUrls) GetSmall() string {
	if x != nil {
		return x.Small
	}
	return ""
}

func (x *PhotoUrls) GetThumb() string {
	if x != nil {
		return x.Thumb
	}
	return ""
}

// Exif contains camera and exposure metadata for a photo.
type Exif struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Camera manufacturer (e.g., "Canon", "Nikon", "Sony").
	Make string `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	// Camera model (e.g., "EOS R5", "D850").
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Lens aperture (e.g., "f/2.8").
	Aperture string `protobuf:"bytes,3,opt,name=aperture,proto3" json:"aperture,omitempty"`
	// Exposure time (e.g., "1/250").
	ExposureTime string `protobuf:"bytes,4,opt,name=exposure_time,json=exposureTime,proto3" json:"exposure_time,omitempty"`
	// Focal length in mm (e.g., "85.0").
	FocalLength string `protobuf:"bytes,5,opt,name=focal_length,json=focalLength,proto3" json:"focal_length,omitempty"`
	// ISO sensitivity (e.g., 400).
	Iso           int32 `protobuf:"varint,6,opt,name=iso,proto3" json:"iso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exif) Reset() {
	*x = Exif{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exif) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exif) ProtoMessage() {}

func (x *Exif) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exif.ProtoReflect.Descriptor instead.
func (*Exif) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{2}
}

func (x *Exif) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Exif) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Exif) GetAperture() string {
	if x != nil {
		return x.Aperture
	}
	return ""
}

func (x *Exif) GetExposureTime() string {
	if x != nil {
		return x.ExposureTime
	}
	return ""
}

func (x *Exif) GetFocalLength() string {
	if x != nil {
		return x.FocalLength
	}
	return ""
}

func (x *Exif) GetIso() int32 {
	if x != nil {
		return x.Iso
	}
	return 0
}

// Location describes where a photo was taken.
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// City name (e.g., "Tokyo", "New York").
	City string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	// Country name (e.g., "Japan", "United States").
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	// GPS latitude coordinate.
	Latitude float64 `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// GPS longitude coordinate.
	Longitude float64 `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Full human-readable location name.
	Name          string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Tag is a keyword label associated with a photo.
type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tag title (e.g., "nature", "architecture", "portrait").
	Title         string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{4}
}

func (x *Tag) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// User represents an Unsplash photographer or curator.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique Unsplash user ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The user's username (URL-safe handle).
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// The user's display name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The user's bio/description.
	Bio string `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	// The user's geographic location.
	Location string `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// URL to the user's external portfolio website.
	PortfolioUrl string `protobuf:"bytes,6,opt,name=portfolio_url,json=portfolioUrl,proto3" json:"portfolio_url,omitempty"`
	// Total number of photos uploaded by this user.
	TotalPhotos int32 `protobuf:"varint,7,opt,name=total_photos,json=totalPhotos,proto3" json:"total_photos,omitempty"`
	// Total number of likes received across all photos.
	TotalLikes int32 `protobuf:"varint,8,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
	// Total number of collections curated by this user.
	TotalCollections int32 `protobuf:"varint,9,opt,name=total_collections,json=totalCollections,proto3" json:"total_collections,omitempty"`
	// URL to the user's small profile image.
	ProfileImageSmall string `protobuf:"bytes,10,opt,name=profile_image_small,json=profileImageSmall,proto3" json:"profile_image_small,omitempty"`
	// URL to the user's medium profile image.
	ProfileImageMedium string `protobuf:"bytes,11,opt,name=profile_image_medium,json=profileImageMedium,proto3" json:"profile_image_medium,omitempty"`
	// URL to the user's large profile image.
	ProfileImageLarge string `protobuf:"bytes,12,opt,name=profile_image_large,json=profileImageLarge,proto3" json:"profile_image_large,omitempty"`
	// Total number of downloads across all the user's photos.
	TotalDownloads int32 `protobuf:"varint,13,opt,name=total_downloads,json=totalDownloads,proto3" json:"total_downloads,omitempty"`
	// Total number of followers.
	FollowersCount int32 `protobuf:"varint,14,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	// Total number of users this user is following.
	FollowingCount int32 `protobuf:"varint,15,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *User) GetPortfolioUrl() string {
	if x != nil {
		return x.PortfolioUrl
	}
	return ""
}

func (x *User) GetTotalPhotos() int32 {
	if x != nil {
		return x.TotalPhotos
	}
	return 0
}

func (x *User) GetTotalLikes() int32 {
	if x != nil {
		return x.TotalLikes
	}
	return 0
}

func (x *User) GetTotalCollections() int32 {
	if x != nil {
		return x.TotalCollections
	}
	return 0
}

func (x *User) GetProfileImageSmall() string {
	if x != nil {
		return x.ProfileImageSmall
	}
	return ""
}

func (x *User) GetProfileImageMedium() string {
	if x != nil {
		return x.ProfileImageMedium
	}
	return ""
}

func (x *User) GetProfileImageLarge() string {
	if x != nil {
		return x.ProfileImageLarge
	}
	return ""
}

func (x *User) GetTotalDownloads() int32 {
	if x != nil {
		return x.TotalDownloads
	}
	return 0
}

func (x *User) GetFollowersCount() int32 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

func (x *User) GetFollowingCount() int32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

// Collection represents a curated set of photos on Unsplash.
type Collection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique numeric collection ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The collection title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The collection description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The date this collection was published (ISO 8601 format).
	PublishedAt string `protobuf:"bytes,4,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// The date this collection was last updated (ISO 8601 format).
	UpdatedAt string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Total number of photos in this collection.
	TotalPhotos int32 `protobuf:"varint,6,opt,name=total_photos,json=totalPhotos,proto3" json:"total_photos,omitempty"`
	// The cover photo for this collection.
	CoverPhoto *Photo `protobuf:"bytes,7,opt,name=cover_photo,json=coverPhoto,proto3" json:"cover_photo,omitempty"`
	// The user who curated this collection.
	User *User `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	// Tags associated with this collection.
	Tags          []*Tag `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{6}
}

func (x *Collection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Collection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Collection) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Collection) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Collection) GetTotalPhotos() int32 {
	if x != nil {
		return x.TotalPhotos
	}
	return 0
}

func (x *Collection) GetCoverPhoto() *Photo {
	if x != nil {
		return x.CoverPhoto
	}
	return nil
}

func (x *Collection) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Collection) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Request for SearchPhotos RPC.
type SearchPhotosRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The search query string (e.g., "sunset beach", "mountain landscape", "coffee shop").
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Page number for pagination (starts at 1). Defaults to 1.
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (1-30). Defaults to 10.
	PerPage int32 `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	// Sort order: "relevant" (default) or "latest".
	OrderBy string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Filter by photo orientation: "landscape", "portrait", or "squarish".
	Orientation string `protobuf:"bytes,5,opt,name=orientation,proto3" json:"orientation,omitempty"`
	// Filter by color tone: "black_and_white", "black", "white", "yellow",
	// "orange", "red", "purple", "magenta", "green", "teal", "blue".
	Color         string `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPhotosRequest) Reset() {
	*x = SearchPhotosRequest{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPhotosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPhotosRequest) ProtoMessage() {}

func (x *SearchPhotosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPhotosRequest.ProtoReflect.Descriptor instead.
func (*SearchPhotosRequest) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{7}
}

func (x *SearchPhotosRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPhotosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchPhotosRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *SearchPhotosRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *SearchPhotosRequest) GetOrientation() string {
	if x != nil {
		return x.Orientation
	}
	return ""
}

func (x *SearchPhotosRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// Response for SearchPhotos RPC.
type SearchPhotosResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of matching photos across all pages.
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Total number of pages available.
	TotalPages int32 `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	// The list of photos matching the search query.
	Results       []*Photo `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPhotosResponse) Reset() {
	*x = SearchPhotosResponse{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPhotosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPhotosResponse) ProtoMessage() {}

func (x *SearchPhotosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPhotosResponse.ProtoReflect.Descriptor instead.
func (*SearchPhotosResponse) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{8}
}

func (x *SearchPhotosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchPhotosResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *SearchPhotosResponse) GetResults() []*Photo {
	if x != nil {
		return x.Results
	}
	return nil
}

// Request for GetPhoto RPC.
type GetPhotoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Unsplash photo ID to look up (e.g., "Dwu85P9SOIk").
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhotoRequest) Reset() {
	*x = GetPhotoRequest{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotoRequest) ProtoMessage() {}

func (x *GetPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotoRequest.ProtoReflect.Descriptor instead.
func (*GetPhotoRequest) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{9}
}

func (x *GetPhotoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response for GetPhoto RPC.
type GetPhotoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested photo with full metadata.
	Photo         *Photo `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhotoResponse) Reset() {
	*x = GetPhotoResponse{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotoResponse) ProtoMessage() {}

func (x *GetPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotoResponse.ProtoReflect.Descriptor instead.
func (*GetPhotoResponse) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{10}
}

func (x *GetPhotoResponse) GetPhoto() *Photo {
	if x != nil {
		return x.Photo
	}
	return nil
}

// Request for GetRandomPhoto RPC.
type GetRandomPhotoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional search query to narrow random selection (e.g., "nature", "city").
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Number of random photos to return (1-30). Defaults to 1.
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Filter by photo orientation: "landscape", "portrait", or "squarish".
	Orientation string `protobuf:"bytes,3,opt,name=orientation,proto3" json:"orientation,omitempty"`
	// Comma-separated list of collection IDs to limit selection.
	Collections string `protobuf:"bytes,4,opt,name=collections,proto3" json:"collections,omitempty"`
	// Comma-separated list of topic IDs to limit selection.
	Topics        string `protobuf:"bytes,5,opt,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomPhotoRequest) Reset() {
	*x = GetRandomPhotoRequest{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomPhotoRequest) ProtoMessage() {}

func (x *GetRandomPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomPhotoRequest.ProtoReflect.Descriptor instead.
func (*GetRandomPhotoRequest) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{11}
}

func (x *GetRandomPhotoRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetRandomPhotoRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetRandomPhotoRequest) GetOrientation() string {
	if x != nil {
		return x.Orientation
	}
	return ""
}

func (x *GetRandomPhotoRequest) GetCollections() string {
	if x != nil {
		return x.Collections
	}
	return ""
}

func (x *GetRandomPhotoRequest) GetTopics() string {
	if x != nil {
		return x.Topics
	}
	return ""
}

// Response for GetRandomPhoto RPC.
type GetRandomPhotoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The randomly selected photo(s).
	Photos        []*Photo `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomPhotoResponse) Reset() {
	*x = GetRandomPhotoResponse{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomPhotoResponse) ProtoMessage() {}

func (x *GetRandomPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomPhotoResponse.ProtoReflect.Descriptor instead.
func (*GetRandomPhotoResponse) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{12}
}

func (x *GetRandomPhotoResponse) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

// Request for ListPhotos RPC.
type ListPhotosRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page number for pagination (starts at 1). Defaults to 1.
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (1-30). Defaults to 10.
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	// Sort order: "latest" (default), "oldest", or "popular".
	OrderBy       string `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPhotosRequest) Reset() {
	*x = ListPhotosRequest{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPhotosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhotosRequest) ProtoMessage() {}

func (x *ListPhotosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhotosRequest.ProtoReflect.Descriptor instead.
func (*ListPhotosRequest) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{13}
}

func (x *ListPhotosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPhotosRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListPhotosRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// Response for ListPhotos RPC.
type ListPhotosResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of editorial photos.
	Photos        []*Photo `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPhotosResponse) Reset() {
	*x = ListPhotosResponse{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPhotosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhotosResponse) ProtoMessage() {}

func (x *ListPhotosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhotosResponse.ProtoReflect.Descriptor instead.
func (*ListPhotosResponse) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{14}
}

func (x *ListPhotosResponse) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

// Request for SearchCollections RPC.
type SearchCollectionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The search query string (e.g., "travel", "minimal", "food photography").
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Page number for pagination (starts at 1). Defaults to 1.
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (1-30). Defaults to 10.
	PerPage       int32 `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCollectionsRequest) Reset() {
	*x = SearchCollectionsRequest{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCollectionsRequest) ProtoMessage() {}

func (x *SearchCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCollectionsRequest.ProtoReflect.Descriptor instead.
func (*SearchCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{15}
}

func (x *SearchCollectionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchCollectionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchCollectionsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

// Response for SearchCollections RPC.
type SearchCollectionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of matching collections across all pages.
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Total number of pages available.
	TotalPages int32 `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	// The list of collections matching the search query.
	Results       []*Collection `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCollectionsResponse) Reset() {
	*x = SearchCollectionsResponse{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCollectionsResponse) ProtoMessage() {}

func (x *SearchCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCollectionsResponse.ProtoReflect.Descriptor instead.
func (*SearchCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{16}
}

func (x *SearchCollectionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchCollectionsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *SearchCollectionsResponse) GetResults() []*Collection {
	if x != nil {
		return x.Results
	}
	return nil
}

// Request for GetCollection RPC.
type GetCollectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The numeric collection ID (e.g., "1234567").
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{17}
}

func (x *GetCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response for GetCollection RPC.
type GetCollectionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested collection with full metadata.
	Collection    *Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{18}
}

func (x *GetCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

// Request for GetCollectionPhotos RPC.
type GetCollectionPhotosRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The numeric collection ID (e.g., "1234567").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Page number for pagination (starts at 1). Defaults to 1.
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (1-30). Defaults to 10.
	PerPage       int32 `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionPhotosRequest) Reset() {
	*x = GetCollectionPhotosRequest{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionPhotosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionPhotosRequest) ProtoMessage() {}

func (x *GetCollectionPhotosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionPhotosRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionPhotosRequest) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{19}
}

func (x *GetCollectionPhotosRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCollectionPhotosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCollectionPhotosRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

// Response for GetCollectionPhotos RPC.
type GetCollectionPhotosResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of photos in the collection.
	Photos        []*Photo `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionPhotosResponse) Reset() {
	*x = GetCollectionPhotosResponse{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionPhotosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionPhotosResponse) ProtoMessage() {}

func (x *GetCollectionPhotosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionPhotosResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionPhotosResponse) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{20}
}

func (x *GetCollectionPhotosResponse) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

// Request for SearchUsers RPC.
type SearchUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The search query string (e.g., "landscape photographer", "portrait artist").
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Page number for pagination (starts at 1). Defaults to 1.
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (1-30). Defaults to 10.
	PerPage       int32 `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{21}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

// Response for SearchUsers RPC.
type SearchUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of matching users across all pages.
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Total number of pages available.
	TotalPages int32 `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	// The list of users matching the search query.
	Results       []*User `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{22}
}

func (x *SearchUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchUsersResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *SearchUsersResponse) GetResults() []*User {
	if x != nil {
		return x.Results
	}
	return nil
}

// Request for GetUser RPC.
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Unsplash username to look up (e.g., "johndoe", "unsplash").
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Response for GetUser RPC.
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested user profile with full metadata.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request for GetUserPhotos RPC.
type GetUserPhotosRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Unsplash username (e.g., "johndoe").
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Page number for pagination (starts at 1). Defaults to 1.
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (1-30). Defaults to 10.
	PerPage int32 `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	// Sort order: "latest" (default), "oldest", or "popular".
	OrderBy string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Filter by photo orientation: "landscape", "portrait", or "squarish".
	Orientation   string `protobuf:"bytes,5,opt,name=orientation,proto3" json:"orientation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPhotosRequest) Reset() {
	*x = GetUserPhotosRequest{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPhotosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPhotosRequest) ProtoMessage() {}

func (x *GetUserPhotosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPhotosRequest.ProtoReflect.Descriptor instead.
func (*GetUserPhotosRequest) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserPhotosRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserPhotosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserPhotosRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetUserPhotosRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GetUserPhotosRequest) GetOrientation() string {
	if x != nil {
		return x.Orientation
	}
	return ""
}

// Response for GetUserPhotos RPC.
type GetUserPhotosResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of photos by the user.
	Photos        []*Photo `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPhotosResponse) Reset() {
	*x = GetUserPhotosResponse{}
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPhotosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPhotosResponse) ProtoMessage() {}

func (x *GetUserPhotosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unsplash_v1_unsplash_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPhotosResponse.ProtoReflect.Descriptor instead.
func (*GetUserPhotosResponse) Descriptor() ([]byte, []int) {
	return file_unsplash_v1_unsplash_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserPhotosResponse) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

var File_unsplash_v1_unsplash_proto protoreflect.FileDescriptor

const file_unsplash_v1_unsplash_proto_rawDesc = "" +
	"\n" +
	"\x1aunsplash/v1/unsplash.proto\x12\vunsplash.v1\"\x81\x04\n" +
	"\x05Photo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12'\n" +
	"\x0falt_description\x18\a \x01(\tR\x0ealtDescription\x12*\n" +
	"\x04urls\x18\b \x01(\v2\x16.unsplash.v1.PhotoUrlsR\x04urls\x12\x14\n" +
	"\x05likes\x18\t \x01(\x05R\x05likes\x12%\n" +
	"\x04user\x18\n" +
	" \x01(\v2\x11.unsplash.v1.UserR\x04user\x12\x14\n" +
	"\x05color\x18\v \x01(\tR\x05color\x12\x1c\n" +
	"\tdownloads\x18\f \x01(\x05R\tdownloads\x12\x14\n" +
	"\x05views\x18\r \x01(\x05R\x05views\x12%\n" +
	"\x04exif\x18\x0e \x01(\v2\x11.unsplash.v1.ExifR\x04exif\x121\n" +
	"\blocation\x18\x0f \x01(\v2\x15.unsplash.v1.LocationR\blocation\x12$\n" +
	"\x04tags\x18\x10 \x03(\v2\x10.unsplash.v1.TagR\x04tags\"w\n" +
	"\tPhotoUrls\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\tR\x03raw\x12\x12\n" +
	"\x04full\x18\x02 \x01(\tR\x04full\x12\x18\n" +
	"\aregular\x18\x03 \x01(\tR\aregular\x12\x14\n" +
	"\x05small\x18\x04 \x01(\tR\x05small\x12\x14\n" +
	"\x05thumb\x18\x05 \x01(\tR\x05thumb\"\xa6\x01\n" +
	"\x04Exif\x12\x12\n" +
	"\x04make\x18\x01 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1a\n" +
	"\baperture\x18\x03 \x01(\tR\baperture\x12#\n" +
	"\rexposure_time\x18\x04 \x01(\tR\fexposureTime\x12!\n" +
	"\ffocal_length\x18\x05 \x01(\tR\vfocalLength\x12\x10\n" +
	"\x03iso\x18\x06 \x01(\x05R\x03iso\"\x86\x01\n" +
	"\bLocation\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\x1b\n" +
	"\x03Tag\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"\x97\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12#\n" +
	"\rportfolio_url\x18\x06 \x01(\tR\fportfolioUrl\x12!\n" +
	"\ftotal_photos\x18\a \x01(\x05R\vtotalPhotos\x12\x1f\n" +
	"\vtotal_likes\x18\b \x01(\x05R\n" +
	"totalLikes\x12+\n" +
	"\x11total_collections\x18\t \x01(\x05R\x10totalCollections\x12.\n" +
	"\x13profile_image_small\x18\n" +
	" \x01(\tR\x11profileImageSmall\x120\n" +
	"\x14profile_image_medium\x18\v \x01(\tR\x12profileImageMedium\x12.\n" +
	"\x13profile_image_large\x18\f \x01(\tR\x11profileImageLarge\x12'\n" +
	"\x0ftotal_downloads\x18\r \x01(\x05R\x0etotalDownloads\x12'\n" +
	"\x0ffollowers_count\x18\x0e \x01(\x05R\x0efollowersCount\x12'\n" +
	"\x0ffollowing_count\x18\x0f \x01(\x05R\x0efollowingCount\"\xbb\x02\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fpublished_at\x18\x04 \x01(\tR\vpublishedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12!\n" +
	"\ftotal_photos\x18\x06 \x01(\x05R\vtotalPhotos\x123\n" +
	"\vcover_photo\x18\a \x01(\v2\x12.unsplash.v1.PhotoR\n" +
	"coverPhoto\x12%\n" +
	"\x04user\x18\b \x01(\v2\x11.unsplash.v1.UserR\x04user\x12$\n" +
	"\x04tags\x18\t \x03(\v2\x10.unsplash.v1.TagR\x04tags\"\xad\x01\n" +
	"\x13SearchPhotosRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\x12 \n" +
	"\vorientation\x18\x05 \x01(\tR\vorientation\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\"{\n" +
	"\x14SearchPhotosResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12,\n" +
	"\aresults\x18\x03 \x03(\v2\x12.unsplash.v1.PhotoR\aresults\"!\n" +
	"\x0fGetPhotoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x10GetPhotoResponse\x12(\n" +
	"\x05photo\x18\x01 \x01(\v2\x12.unsplash.v1.PhotoR\x05photo\"\x9f\x01\n" +
	"\x15GetRandomPhotoRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12 \n" +
	"\vorientation\x18\x03 \x01(\tR\vorientation\x12 \n" +
	"\vcollections\x18\x04 \x01(\tR\vcollections\x12\x16\n" +
	"\x06topics\x18\x05 \x01(\tR\x06topics\"D\n" +
	"\x16GetRandomPhotoResponse\x12*\n" +
	"\x06photos\x18\x01 \x03(\v2\x12.unsplash.v1.PhotoR\x06photos\"]\n" +
	"\x11ListPhotosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\"@\n" +
	"\x12ListPhotosResponse\x12*\n" +
	"\x06photos\x18\x01 \x03(\v2\x12.unsplash.v1.PhotoR\x06photos\"_\n" +
	"\x18SearchCollectionsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"\x85\x01\n" +
	"\x19SearchCollectionsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x121\n" +
	"\aresults\x18\x03 \x03(\v2\x17.unsplash.v1.CollectionR\aresults\"&\n" +
	"\x14GetCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x15GetCollectionResponse\x127\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x17.unsplash.v1.CollectionR\n" +
	"collection\"[\n" +
	"\x1aGetCollectionPhotosRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"I\n" +
	"\x1bGetCollectionPhotosResponse\x12*\n" +
	"\x06photos\x18\x01 \x03(\v2\x12.unsplash.v1.PhotoR\x06photos\"Y\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"y\n" +
	"\x13SearchUsersResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12+\n" +
	"\aresults\x18\x03 \x03(\v2\x11.unsplash.v1.UserR\aresults\",\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"8\n" +
	"\x0fGetUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.unsplash.v1.UserR\x04user\"\x9e\x01\n" +
	"\x14GetUserPhotosRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\x12 \n" +
	"\vorientation\x18\x05 \x01(\tR\vorientation\"C\n" +
	"\x15GetUserPhotosResponse\x12*\n" +
	"\x06photos\x18\x01 \x03(\v2\x12.unsplash.v1.PhotoR\x06photos2\xef\x06\n" +
	"\x0fUnsplashService\x12S\n" +
	"\fSearchPhotos\x12 .unsplash.v1.SearchPhotosRequest\x1a!.unsplash.v1.SearchPhotosResponse\x12G\n" +
	"\bGetPhoto\x12\x1c.unsplash.v1.GetPhotoRequest\x1a\x1d.unsplash.v1.GetPhotoResponse\x12Y\n" +
	"\x0eGetRandomPhoto\x12\".unsplash.v1.GetRandomPhotoRequest\x1a#.unsplash.v1.GetRandomPhotoResponse\x12M\n" +
	"\n" +
	"ListPhotos\x12\x1e.unsplash.v1.ListPhotosRequest\x1a\x1f.unsplash.v1.ListPhotosResponse\x12b\n" +
	"\x11SearchCollections\x12%.unsplash.v1.SearchCollectionsRequest\x1a&.unsplash.v1.SearchCollectionsResponse\x12V\n" +
	"\rGetCollection\x12!.unsplash.v1.GetCollectionRequest\x1a\".unsplash.v1.GetCollectionResponse\x12h\n" +
	"\x13GetCollectionPhotos\x12'.unsplash.v1.GetCollectionPhotosRequest\x1a(.unsplash.v1.GetCollectionPhotosResponse\x12P\n" +
	"\vSearchUsers\x12\x1f.unsplash.v1.SearchUsersRequest\x1a .unsplash.v1.SearchUsersResponse\x12D\n" +
	"\aGetUser\x12\x1b.unsplash.v1.GetUserRequest\x1a\x1c.unsplash.v1.GetUserResponse\x12V\n" +
	"\rGetUserPhotos\x12!.unsplash.v1.GetUserPhotosRequest\x1a\".unsplash.v1.GetUserPhotosResponseB\xb6\x01\n" +
	"\x0fcom.unsplash.v1B\rUnsplashProtoP\x01ZGgithub.com/jim-technologies/invariantaf/unsplash/unsplash/v1;unsplashpb\xa2\x02\x03UXX\xaa\x02\vUnsplash.V1\xca\x02\vUnsplash\\V1\xe2\x02\x17Unsplash\\V1\\GPBMetadata\xea\x02\fUnsplash::V1b\x06proto3"

var (
	file_unsplash_v1_unsplash_proto_rawDescOnce sync.Once
	file_unsplash_v1_unsplash_proto_rawDescData []byte
)

func file_unsplash_v1_unsplash_proto_rawDescGZIP() []byte {
	file_unsplash_v1_unsplash_proto_rawDescOnce.Do(func() {
		file_unsplash_v1_unsplash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unsplash_v1_unsplash_proto_rawDesc), len(file_unsplash_v1_unsplash_proto_rawDesc)))
	})
	return file_unsplash_v1_unsplash_proto_rawDescData
}

var file_unsplash_v1_unsplash_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_unsplash_v1_unsplash_proto_goTypes = []any{
	(*Photo)(nil),                       // 0: unsplash.v1.Photo
	(*PhotoUrls)(nil),                   // 1: unsplash.v1.PhotoUrls
	(*Exif)(nil),                        // 2: unsplash.v1.Exif
	(*Location)(nil),                    // 3: unsplash.v1.Location
	(*Tag)(nil),                         // 4: unsplash.v1.Tag
	(*User)(nil),                        // 5: unsplash.v1.User
	(*Collection)(nil),                  // 6: unsplash.v1.Collection
	(*SearchPhotosRequest)(nil),         // 7: unsplash.v1.SearchPhotosRequest
	(*SearchPhotosResponse)(nil),        // 8: unsplash.v1.SearchPhotosResponse
	(*GetPhotoRequest)(nil),             // 9: unsplash.v1.GetPhotoRequest
	(*GetPhotoResponse)(nil),            // 10: unsplash.v1.GetPhotoResponse
	(*GetRandomPhotoRequest)(nil),       // 11: unsplash.v1.GetRandomPhotoRequest
	(*GetRandomPhotoResponse)(nil),      // 12: unsplash.v1.GetRandomPhotoResponse
	(*ListPhotosRequest)(nil),           // 13: unsplash.v1.ListPhotosRequest
	(*ListPhotosResponse)(nil),          // 14: unsplash.v1.ListPhotosResponse
	(*SearchCollectionsRequest)(nil),    // 15: unsplash.v1.SearchCollectionsRequest
	(*SearchCollectionsResponse)(nil),   // 16: unsplash.v1.SearchCollectionsResponse
	(*GetCollectionRequest)(nil),        // 17: unsplash.v1.GetCollectionRequest
	(*GetCollectionResponse)(nil),       // 18: unsplash.v1.GetCollectionResponse
	(*GetCollectionPhotosRequest)(nil),  // 19: unsplash.v1.GetCollectionPhotosRequest
	(*GetCollectionPhotosResponse)(nil), // 20: unsplash.v1.GetCollectionPhotosResponse
	(*SearchUsersRequest)(nil),          // 21: unsplash.v1.SearchUsersRequest
	(*SearchUsersResponse)(nil),         // 22: unsplash.v1.SearchUsersResponse
	(*GetUserRequest)(nil),              // 23: unsplash.v1.GetUserRequest
	(*GetUserResponse)(nil),             // 24: unsplash.v1.GetUserResponse
	(*GetUserPhotosRequest)(nil),        // 25: unsplash.v1.GetUserPhotosRequest
	(*GetUserPhotosResponse)(nil),       // 26: unsplash.v1.GetUserPhotosResponse
}
var file_unsplash_v1_unsplash_proto_depIdxs = []int32{
	1,  // 0: unsplash.v1.Photo.urls:type_name -> unsplash.v1.PhotoUrls
	5,  // 1: unsplash.v1.Photo.user:type_name -> unsplash.v1.User
	2,  // 2: unsplash.v1.Photo.exif:type_name -> unsplash.v1.Exif
	3,  // 3: unsplash.v1.Photo.location:type_name -> unsplash.v1.Location
	4,  // 4: unsplash.v1.Photo.tags:type_name -> unsplash.v1.Tag
	0,  // 5: unsplash.v1.Collection.cover_photo:type_name -> unsplash.v1.Photo
	5,  // 6: unsplash.v1.Collection.user:type_name -> unsplash.v1.User
	4,  // 7: unsplash.v1.Collection.tags:type_name -> unsplash.v1.Tag
	0,  // 8: unsplash.v1.SearchPhotosResponse.results:type_name -> unsplash.v1.Photo
	0,  // 9: unsplash.v1.GetPhotoResponse.photo:type_name -> unsplash.v1.Photo
	0,  // 10: unsplash.v1.GetRandomPhotoResponse.photos:type_name -> unsplash.v1.Photo
	0,  // 11: unsplash.v1.ListPhotosResponse.photos:type_name -> unsplash.v1.Photo
	6,  // 12: unsplash.v1.SearchCollectionsResponse.results:type_name -> unsplash.v1.Collection
	6,  // 13: unsplash.v1.GetCollectionResponse.collection:type_name -> unsplash.v1.Collection
	0,  // 14: unsplash.v1.GetCollectionPhotosResponse.photos:type_name -> unsplash.v1.Photo
	5,  // 15: unsplash.v1.SearchUsersResponse.results:type_name -> unsplash.v1.User
	5,  // 16: unsplash.v1.GetUserResponse.user:type_name -> unsplash.v1.User
	0,  // 17: unsplash.v1.GetUserPhotosResponse.photos:type_name -> unsplash.v1.Photo
	7,  // 18: unsplash.v1.UnsplashService.SearchPhotos:input_type -> unsplash.v1.SearchPhotosRequest
	9,  // 19: unsplash.v1.UnsplashService.GetPhoto:input_type -> unsplash.v1.GetPhotoRequest
	11, // 20: unsplash.v1.UnsplashService.GetRandomPhoto:input_type -> unsplash.v1.GetRandomPhotoRequest
	13, // 21: unsplash.v1.UnsplashService.ListPhotos:input_type -> unsplash.v1.ListPhotosRequest
	15, // 22: unsplash.v1.UnsplashService.SearchCollections:input_type -> unsplash.v1.SearchCollectionsRequest
	17, // 23: unsplash.v1.UnsplashService.GetCollection:input_type -> unsplash.v1.GetCollectionRequest
	19, // 24: unsplash.v1.UnsplashService.GetCollectionPhotos:input_type -> unsplash.v1.GetCollectionPhotosRequest
	21, // 25: unsplash.v1.UnsplashService.SearchUsers:input_type -> unsplash.v1.SearchUsersRequest
	23, // 26: unsplash.v1.UnsplashService.GetUser:input_type -> unsplash.v1.GetUserRequest
	25, // 27: unsplash.v1.UnsplashService.GetUserPhotos:input_type -> unsplash.v1.GetUserPhotosRequest
	8,  // 28: unsplash.v1.UnsplashService.SearchPhotos:output_type -> unsplash.v1.SearchPhotosResponse
	10, // 29: unsplash.v1.UnsplashService.GetPhoto:output_type -> unsplash.v1.GetPhotoResponse
	12, // 30: unsplash.v1.UnsplashService.GetRandomPhoto:output_type -> unsplash.v1.GetRandomPhotoResponse
	14, // 31: unsplash.v1.UnsplashService.ListPhotos:output_type -> unsplash.v1.ListPhotosResponse
	16, // 32: unsplash.v1.UnsplashService.SearchCollections:output_type -> unsplash.v1.SearchCollectionsResponse
	18, // 33: unsplash.v1.UnsplashService.GetCollection:output_type -> unsplash.v1.GetCollectionResponse
	20, // 34: unsplash.v1.UnsplashService.GetCollectionPhotos:output_type -> unsplash.v1.GetCollectionPhotosResponse
	22, // 35: unsplash.v1.UnsplashService.SearchUsers:output_type -> unsplash.v1.SearchUsersResponse
	24, // 36: unsplash.v1.UnsplashService.GetUser:output_type -> unsplash.v1.GetUserResponse
	26, // 37: unsplash.v1.UnsplashService.GetUserPhotos:output_type -> unsplash.v1.GetUserPhotosResponse
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_unsplash_v1_unsplash_proto_init() }
func file_unsplash_v1_unsplash_proto_init() {
	if File_unsplash_v1_unsplash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unsplash_v1_unsplash_proto_rawDesc), len(file_unsplash_v1_unsplash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unsplash_v1_unsplash_proto_goTypes,
		DependencyIndexes: file_unsplash_v1_unsplash_proto_depIdxs,
		MessageInfos:      file_unsplash_v1_unsplash_proto_msgTypes,
	}.Build()
	File_unsplash_v1_unsplash_proto = out.File
	file_unsplash_v1_unsplash_proto_goTypes = nil
	file_unsplash_v1_unsplash_proto_depIdxs = nil
}
