// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stackexchange/v1/stackexchange.proto

package stackexchangev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A question on a Stack Exchange site. Contains the question's metadata,
// content, and relationship to answers and tags.
type Question struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique numeric ID of the question.
	QuestionId int64 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	// The question title (plain text).
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The question body as HTML. Only present if the "withbody" filter is used.
	Body string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// A direct link to the question page on the Stack Exchange site.
	Link string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	// The question's score (upvotes minus downvotes).
	Score int32 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	// The total number of answers posted to this question.
	AnswerCount int32 `protobuf:"varint,6,opt,name=answer_count,json=answerCount,proto3" json:"answer_count,omitempty"`
	// The number of times this question has been viewed.
	ViewCount int32 `protobuf:"varint,7,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	// Whether this question has an accepted answer.
	IsAnswered bool `protobuf:"varint,8,opt,name=is_answered,json=isAnswered,proto3" json:"is_answered,omitempty"`
	// The tags applied to this question (e.g. ["python", "django", "orm"]).
	Tags []string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	// The question author's information.
	Owner *ShallowUser `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	// Creation time as Unix timestamp (seconds since epoch).
	CreationDate int64 `protobuf:"varint,11,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	// Last activity time as Unix timestamp.
	LastActivityDate int64 `protobuf:"varint,12,opt,name=last_activity_date,json=lastActivityDate,proto3" json:"last_activity_date,omitempty"`
	// The numeric ID of the accepted answer, if any.
	AcceptedAnswerId int64 `protobuf:"varint,13,opt,name=accepted_answer_id,json=acceptedAnswerId,proto3" json:"accepted_answer_id,omitempty"`
	// The number of times this question has been bookmarked/favorited.
	FavoriteCount int32 `protobuf:"varint,14,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *Question) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Question) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Question) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Question) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Question) GetAnswerCount() int32 {
	if x != nil {
		return x.AnswerCount
	}
	return 0
}

func (x *Question) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Question) GetIsAnswered() bool {
	if x != nil {
		return x.IsAnswered
	}
	return false
}

func (x *Question) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Question) GetOwner() *ShallowUser {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Question) GetCreationDate() int64 {
	if x != nil {
		return x.CreationDate
	}
	return 0
}

func (x *Question) GetLastActivityDate() int64 {
	if x != nil {
		return x.LastActivityDate
	}
	return 0
}

func (x *Question) GetAcceptedAnswerId() int64 {
	if x != nil {
		return x.AcceptedAnswerId
	}
	return 0
}

func (x *Question) GetFavoriteCount() int32 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

// An answer to a question on a Stack Exchange site.
type Answer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique numeric ID of the answer.
	AnswerId int64 `protobuf:"varint,1,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	// The numeric ID of the question this answer belongs to.
	QuestionId int64 `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	// The answer body as HTML. Only present if the "withbody" filter is used.
	Body string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// The answer's score (upvotes minus downvotes).
	Score int32 `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	// Whether this is the accepted answer for the question.
	IsAccepted bool `protobuf:"varint,5,opt,name=is_accepted,json=isAccepted,proto3" json:"is_accepted,omitempty"`
	// The answer author's information.
	Owner *ShallowUser `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	// Creation time as Unix timestamp (seconds since epoch).
	CreationDate int64 `protobuf:"varint,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	// Last activity time as Unix timestamp.
	LastActivityDate int64 `protobuf:"varint,8,opt,name=last_activity_date,json=lastActivityDate,proto3" json:"last_activity_date,omitempty"`
	// A direct link to the answer on the Stack Exchange site.
	Link          string `protobuf:"bytes,9,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{1}
}

func (x *Answer) GetAnswerId() int64 {
	if x != nil {
		return x.AnswerId
	}
	return 0
}

func (x *Answer) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *Answer) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Answer) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Answer) GetIsAccepted() bool {
	if x != nil {
		return x.IsAccepted
	}
	return false
}

func (x *Answer) GetOwner() *ShallowUser {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Answer) GetCreationDate() int64 {
	if x != nil {
		return x.CreationDate
	}
	return 0
}

func (x *Answer) GetLastActivityDate() int64 {
	if x != nil {
		return x.LastActivityDate
	}
	return 0
}

func (x *Answer) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

// A tag on a Stack Exchange site, representing a topic or technology.
type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tag name (e.g. "python", "javascript", "react").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The total number of questions tagged with this tag.
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Whether this tag has a wiki excerpt (brief description).
	HasSynonyms bool `protobuf:"varint,3,opt,name=has_synonyms,json=hasSynonyms,proto3" json:"has_synonyms,omitempty"`
	// Whether moderator-only. Most tags are not.
	IsModeratorOnly bool `protobuf:"varint,4,opt,name=is_moderator_only,json=isModeratorOnly,proto3" json:"is_moderator_only,omitempty"`
	// Whether this tag requires special privileges to use.
	IsRequired    bool `protobuf:"varint,5,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{2}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Tag) GetHasSynonyms() bool {
	if x != nil {
		return x.HasSynonyms
	}
	return false
}

func (x *Tag) GetIsModeratorOnly() bool {
	if x != nil {
		return x.IsModeratorOnly
	}
	return false
}

func (x *Tag) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

// A simplified user object returned inline with questions and answers.
// Contains enough information to identify the user without a full profile fetch.
type ShallowUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's numeric ID. Use this with GetUser to fetch the full profile.
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The user's display name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The user's current reputation score.
	Reputation int32 `protobuf:"varint,3,opt,name=reputation,proto3" json:"reputation,omitempty"`
	// URL to the user's profile image/avatar.
	ProfileImage string `protobuf:"bytes,4,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	// A direct link to the user's profile page.
	Link          string `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShallowUser) Reset() {
	*x = ShallowUser{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShallowUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShallowUser) ProtoMessage() {}

func (x *ShallowUser) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShallowUser.ProtoReflect.Descriptor instead.
func (*ShallowUser) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{3}
}

func (x *ShallowUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShallowUser) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ShallowUser) GetReputation() int32 {
	if x != nil {
		return x.Reputation
	}
	return 0
}

func (x *ShallowUser) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

func (x *ShallowUser) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

// A full user profile on a Stack Exchange site.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's unique numeric ID.
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The user's display name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The user's current reputation score.
	Reputation int32 `protobuf:"varint,3,opt,name=reputation,proto3" json:"reputation,omitempty"`
	// URL to the user's profile image/avatar.
	ProfileImage string `protobuf:"bytes,4,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	// A direct link to the user's profile page.
	Link string `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	// Account creation time as Unix timestamp (seconds since epoch).
	CreationDate int64 `protobuf:"varint,6,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	// Last access time as Unix timestamp.
	LastAccessDate int64 `protobuf:"varint,7,opt,name=last_access_date,json=lastAccessDate,proto3" json:"last_access_date,omitempty"`
	// The user's location (if provided).
	Location string `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	// The user's website URL (if provided).
	WebsiteUrl string `protobuf:"bytes,9,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	// The user's "about me" text (HTML).
	AboutMe string `protobuf:"bytes,10,opt,name=about_me,json=aboutMe,proto3" json:"about_me,omitempty"`
	// The number of questions the user has asked.
	QuestionCount int32 `protobuf:"varint,11,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	// The number of answers the user has posted.
	AnswerCount int32 `protobuf:"varint,12,opt,name=answer_count,json=answerCount,proto3" json:"answer_count,omitempty"`
	// Badge counts broken down by tier.
	BadgeCounts   *BadgeCounts `protobuf:"bytes,13,opt,name=badge_counts,json=badgeCounts,proto3" json:"badge_counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetReputation() int32 {
	if x != nil {
		return x.Reputation
	}
	return 0
}

func (x *User) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

func (x *User) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *User) GetCreationDate() int64 {
	if x != nil {
		return x.CreationDate
	}
	return 0
}

func (x *User) GetLastAccessDate() int64 {
	if x != nil {
		return x.LastAccessDate
	}
	return 0
}

func (x *User) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *User) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *User) GetAboutMe() string {
	if x != nil {
		return x.AboutMe
	}
	return ""
}

func (x *User) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *User) GetAnswerCount() int32 {
	if x != nil {
		return x.AnswerCount
	}
	return 0
}

func (x *User) GetBadgeCounts() *BadgeCounts {
	if x != nil {
		return x.BadgeCounts
	}
	return nil
}

// Counts of badges earned by a user, broken down by tier.
type BadgeCounts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of gold badges (highest tier, rarest).
	Gold int32 `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	// Number of silver badges (middle tier).
	Silver int32 `protobuf:"varint,2,opt,name=silver,proto3" json:"silver,omitempty"`
	// Number of bronze badges (lowest tier, most common).
	Bronze        int32 `protobuf:"varint,3,opt,name=bronze,proto3" json:"bronze,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadgeCounts) Reset() {
	*x = BadgeCounts{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadgeCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadgeCounts) ProtoMessage() {}

func (x *BadgeCounts) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadgeCounts.ProtoReflect.Descriptor instead.
func (*BadgeCounts) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{5}
}

func (x *BadgeCounts) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *BadgeCounts) GetSilver() int32 {
	if x != nil {
		return x.Silver
	}
	return 0
}

func (x *BadgeCounts) GetBronze() int32 {
	if x != nil {
		return x.Bronze
	}
	return 0
}

// A single reputation change event for a user.
type ReputationChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of reputation event (e.g. "post_upvoted", "answer_accepted").
	ReputationChangeType string `protobuf:"bytes,1,opt,name=reputation_change_type,json=reputationChangeType,proto3" json:"reputation_change_type,omitempty"`
	// The reputation change amount (positive for gains, negative for losses).
	ReputationChange int32 `protobuf:"varint,2,opt,name=reputation_change,json=reputationChange,proto3" json:"reputation_change,omitempty"`
	// The numeric ID of the post that caused the reputation change.
	PostId int64 `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	// The title of the post that caused the change.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// A direct link to the post.
	Link string `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	// When this reputation change occurred as Unix timestamp.
	OnDate        int64 `protobuf:"varint,6,opt,name=on_date,json=onDate,proto3" json:"on_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReputationChange) Reset() {
	*x = ReputationChange{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReputationChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReputationChange) ProtoMessage() {}

func (x *ReputationChange) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReputationChange.ProtoReflect.Descriptor instead.
func (*ReputationChange) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{6}
}

func (x *ReputationChange) GetReputationChangeType() string {
	if x != nil {
		return x.ReputationChangeType
	}
	return ""
}

func (x *ReputationChange) GetReputationChange() int32 {
	if x != nil {
		return x.ReputationChange
	}
	return 0
}

func (x *ReputationChange) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *ReputationChange) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReputationChange) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ReputationChange) GetOnDate() int64 {
	if x != nil {
		return x.OnDate
	}
	return 0
}

// Request to search questions by keyword.
type SearchQuestionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search term to look for in question titles. Required.
	Intitle string `protobuf:"bytes,1,opt,name=intitle,proto3" json:"intitle,omitempty"`
	// Restrict to questions with these tags (semicolon-delimited, e.g. "python;django").
	Tagged string `protobuf:"bytes,2,opt,name=tagged,proto3" json:"tagged,omitempty"`
	// Sort order: "activity", "votes", "creation", "relevance" (default "relevance").
	Sort string `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	// Page number for pagination (1-indexed, default 1).
	Page int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (default 10, max 100).
	Pagesize int32 `protobuf:"varint,5,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	// Stack Exchange site to search (default "stackoverflow"). Other examples:
	// "serverfault", "superuser", "askubuntu", "math", "gaming".
	Site string `protobuf:"bytes,6,opt,name=site,proto3" json:"site,omitempty"`
	// API filter name. Use "withbody" to include question body text.
	Filter        string `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuestionsRequest) Reset() {
	*x = SearchQuestionsRequest{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionsRequest) ProtoMessage() {}

func (x *SearchQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionsRequest.ProtoReflect.Descriptor instead.
func (*SearchQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{7}
}

func (x *SearchQuestionsRequest) GetIntitle() string {
	if x != nil {
		return x.Intitle
	}
	return ""
}

func (x *SearchQuestionsRequest) GetTagged() string {
	if x != nil {
		return x.Tagged
	}
	return ""
}

func (x *SearchQuestionsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchQuestionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchQuestionsRequest) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *SearchQuestionsRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *SearchQuestionsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type SearchQuestionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of matching questions.
	Items []*Question `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether there are more results available on subsequent pages.
	HasMore bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// The number of API requests remaining in your daily quota.
	QuotaRemaining int32 `protobuf:"varint,3,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchQuestionsResponse) Reset() {
	*x = SearchQuestionsResponse{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionsResponse) ProtoMessage() {}

func (x *SearchQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionsResponse.ProtoReflect.Descriptor instead.
func (*SearchQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{8}
}

func (x *SearchQuestionsResponse) GetItems() []*Question {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchQuestionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SearchQuestionsResponse) GetQuotaRemaining() int32 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

// Request to get a single question by ID.
type GetQuestionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The numeric question ID. Required.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Stack Exchange site (default "stackoverflow").
	Site string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	// API filter name. Use "withbody" to include question body text.
	Filter        string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{9}
}

func (x *GetQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetQuestionRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *GetQuestionRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type GetQuestionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested question. Null if not found.
	Question      *Question `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionResponse) Reset() {
	*x = GetQuestionResponse{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionResponse) ProtoMessage() {}

func (x *GetQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionResponse) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{10}
}

func (x *GetQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

// Request to get answers for a question.
type GetAnswersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The numeric question ID whose answers to fetch. Required.
	QuestionId int64 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	// Sort order: "activity", "votes" (default), "creation".
	Sort string `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	// Page number for pagination (1-indexed, default 1).
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (default 10, max 100).
	Pagesize int32 `protobuf:"varint,4,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	// Stack Exchange site (default "stackoverflow").
	Site string `protobuf:"bytes,5,opt,name=site,proto3" json:"site,omitempty"`
	// API filter name. Use "withbody" to include answer body text.
	Filter        string `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnswersRequest) Reset() {
	*x = GetAnswersRequest{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswersRequest) ProtoMessage() {}

func (x *GetAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswersRequest.ProtoReflect.Descriptor instead.
func (*GetAnswersRequest) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{11}
}

func (x *GetAnswersRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *GetAnswersRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetAnswersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAnswersRequest) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *GetAnswersRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *GetAnswersRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type GetAnswersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of answers for the question.
	Items []*Answer `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether there are more results available on subsequent pages.
	HasMore bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// The number of API requests remaining in your daily quota.
	QuotaRemaining int32 `protobuf:"varint,3,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAnswersResponse) Reset() {
	*x = GetAnswersResponse{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswersResponse) ProtoMessage() {}

func (x *GetAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswersResponse.ProtoReflect.Descriptor instead.
func (*GetAnswersResponse) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{12}
}

func (x *GetAnswersResponse) GetItems() []*Answer {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetAnswersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetAnswersResponse) GetQuotaRemaining() int32 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

// Request to get a user profile.
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The numeric user ID. Required.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Stack Exchange site (default "stackoverflow").
	Site          string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested user profile. Null if not found.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request to get popular tags.
type GetTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sort order: "popular" (default), "activity", "name".
	Sort string `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	// Page number for pagination (1-indexed, default 1).
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (default 10, max 100).
	Pagesize int32 `protobuf:"varint,3,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	// Filter tags containing this substring in their name.
	Inname string `protobuf:"bytes,4,opt,name=inname,proto3" json:"inname,omitempty"`
	// Stack Exchange site (default "stackoverflow").
	Site          string `protobuf:"bytes,5,opt,name=site,proto3" json:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsRequest) Reset() {
	*x = GetTagsRequest{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsRequest) ProtoMessage() {}

func (x *GetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTagsRequest) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{15}
}

func (x *GetTagsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetTagsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTagsRequest) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *GetTagsRequest) GetInname() string {
	if x != nil {
		return x.Inname
	}
	return ""
}

func (x *GetTagsRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type GetTagsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of tags.
	Items []*Tag `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether there are more results available on subsequent pages.
	HasMore bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// The number of API requests remaining in your daily quota.
	QuotaRemaining int32 `protobuf:"varint,3,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTagsResponse) Reset() {
	*x = GetTagsResponse{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsResponse) ProtoMessage() {}

func (x *GetTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsResponse.ProtoReflect.Descriptor instead.
func (*GetTagsResponse) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{16}
}

func (x *GetTagsResponse) GetItems() []*Tag {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetTagsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetTagsResponse) GetQuotaRemaining() int32 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

// Request to get top questions, optionally filtered by tag.
type GetTopQuestionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by tags (semicolon-delimited, e.g. "python;machine-learning").
	Tagged string `protobuf:"bytes,1,opt,name=tagged,proto3" json:"tagged,omitempty"`
	// Sort order: "activity", "votes", "creation", "hot" (default), "week", "month".
	Sort string `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	// Page number for pagination (1-indexed, default 1).
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (default 10, max 100).
	Pagesize int32 `protobuf:"varint,4,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	// Stack Exchange site (default "stackoverflow").
	Site string `protobuf:"bytes,5,opt,name=site,proto3" json:"site,omitempty"`
	// API filter name. Use "withbody" to include question body text.
	Filter        string `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopQuestionsRequest) Reset() {
	*x = GetTopQuestionsRequest{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopQuestionsRequest) ProtoMessage() {}

func (x *GetTopQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetTopQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{17}
}

func (x *GetTopQuestionsRequest) GetTagged() string {
	if x != nil {
		return x.Tagged
	}
	return ""
}

func (x *GetTopQuestionsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetTopQuestionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTopQuestionsRequest) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *GetTopQuestionsRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *GetTopQuestionsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type GetTopQuestionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of top questions.
	Items []*Question `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether there are more results available on subsequent pages.
	HasMore bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// The number of API requests remaining in your daily quota.
	QuotaRemaining int32 `protobuf:"varint,3,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTopQuestionsResponse) Reset() {
	*x = GetTopQuestionsResponse{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopQuestionsResponse) ProtoMessage() {}

func (x *GetTopQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetTopQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{18}
}

func (x *GetTopQuestionsResponse) GetItems() []*Question {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetTopQuestionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetTopQuestionsResponse) GetQuotaRemaining() int32 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

// Request for advanced search with multiple filters.
type SearchAdvancedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full-text search query (searches title and body). Use this for broad searches.
	Q string `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	// Search only in question titles.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Restrict to questions with these tags (semicolon-delimited).
	Tagged string `protobuf:"bytes,3,opt,name=tagged,proto3" json:"tagged,omitempty"`
	// Exclude questions with these tags (semicolon-delimited).
	Nottagged string `protobuf:"bytes,4,opt,name=nottagged,proto3" json:"nottagged,omitempty"`
	// Filter by accepted answer status: true = must have accepted answer,
	// false = must not have accepted answer. Omit to not filter.
	Accepted *bool `protobuf:"varint,5,opt,name=accepted,proto3,oneof" json:"accepted,omitempty"`
	// Minimum number of answers required.
	Answers int32 `protobuf:"varint,6,opt,name=answers,proto3" json:"answers,omitempty"`
	// Minimum view count required.
	Views int32 `protobuf:"varint,7,opt,name=views,proto3" json:"views,omitempty"`
	// Sort order: "activity", "votes", "creation", "relevance" (default "relevance").
	Sort string `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`
	// Page number for pagination (1-indexed, default 1).
	Page int32 `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (default 10, max 100).
	Pagesize int32 `protobuf:"varint,10,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	// Stack Exchange site (default "stackoverflow").
	Site string `protobuf:"bytes,11,opt,name=site,proto3" json:"site,omitempty"`
	// API filter name. Use "withbody" to include question body text.
	Filter        string `protobuf:"bytes,12,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAdvancedRequest) Reset() {
	*x = SearchAdvancedRequest{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAdvancedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAdvancedRequest) ProtoMessage() {}

func (x *SearchAdvancedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAdvancedRequest.ProtoReflect.Descriptor instead.
func (*SearchAdvancedRequest) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{19}
}

func (x *SearchAdvancedRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchAdvancedRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchAdvancedRequest) GetTagged() string {
	if x != nil {
		return x.Tagged
	}
	return ""
}

func (x *SearchAdvancedRequest) GetNottagged() string {
	if x != nil {
		return x.Nottagged
	}
	return ""
}

func (x *SearchAdvancedRequest) GetAccepted() bool {
	if x != nil && x.Accepted != nil {
		return *x.Accepted
	}
	return false
}

func (x *SearchAdvancedRequest) GetAnswers() int32 {
	if x != nil {
		return x.Answers
	}
	return 0
}

func (x *SearchAdvancedRequest) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *SearchAdvancedRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchAdvancedRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchAdvancedRequest) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *SearchAdvancedRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *SearchAdvancedRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type SearchAdvancedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of matching questions.
	Items []*Question `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether there are more results available on subsequent pages.
	HasMore bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// The number of API requests remaining in your daily quota.
	QuotaRemaining int32 `protobuf:"varint,3,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchAdvancedResponse) Reset() {
	*x = SearchAdvancedResponse{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAdvancedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAdvancedResponse) ProtoMessage() {}

func (x *SearchAdvancedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAdvancedResponse.ProtoReflect.Descriptor instead.
func (*SearchAdvancedResponse) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{20}
}

func (x *SearchAdvancedResponse) GetItems() []*Question {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchAdvancedResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SearchAdvancedResponse) GetQuotaRemaining() int32 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

// Request to get a user's reputation change history.
type GetUserReputationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The numeric user ID. Required.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Page number for pagination (1-indexed, default 1).
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (default 10, max 100).
	Pagesize int32 `protobuf:"varint,3,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	// Stack Exchange site (default "stackoverflow").
	Site          string `protobuf:"bytes,4,opt,name=site,proto3" json:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReputationRequest) Reset() {
	*x = GetUserReputationRequest{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReputationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReputationRequest) ProtoMessage() {}

func (x *GetUserReputationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReputationRequest.ProtoReflect.Descriptor instead.
func (*GetUserReputationRequest) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserReputationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserReputationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserReputationRequest) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *GetUserReputationRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type GetUserReputationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of reputation change events.
	Items []*ReputationChange `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether there are more results available on subsequent pages.
	HasMore bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// The number of API requests remaining in your daily quota.
	QuotaRemaining int32 `protobuf:"varint,3,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserReputationResponse) Reset() {
	*x = GetUserReputationResponse{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReputationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReputationResponse) ProtoMessage() {}

func (x *GetUserReputationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReputationResponse.ProtoReflect.Descriptor instead.
func (*GetUserReputationResponse) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserReputationResponse) GetItems() []*ReputationChange {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetUserReputationResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetUserReputationResponse) GetQuotaRemaining() int32 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

// Request to find similar questions by title.
type GetSimilarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The title string to find similar questions for. Required.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Restrict to questions with these tags (semicolon-delimited).
	Tagged string `protobuf:"bytes,2,opt,name=tagged,proto3" json:"tagged,omitempty"`
	// Exclude questions with these tags (semicolon-delimited).
	Nottagged string `protobuf:"bytes,3,opt,name=nottagged,proto3" json:"nottagged,omitempty"`
	// Sort order: "activity", "votes", "creation", "relevance" (default "relevance").
	Sort string `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	// Page number for pagination (1-indexed, default 1).
	Page int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (default 10, max 100).
	Pagesize int32 `protobuf:"varint,6,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	// Stack Exchange site (default "stackoverflow").
	Site string `protobuf:"bytes,7,opt,name=site,proto3" json:"site,omitempty"`
	// API filter name. Use "withbody" to include question body text.
	Filter        string `protobuf:"bytes,8,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarRequest) Reset() {
	*x = GetSimilarRequest{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarRequest) ProtoMessage() {}

func (x *GetSimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarRequest.ProtoReflect.Descriptor instead.
func (*GetSimilarRequest) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{23}
}

func (x *GetSimilarRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetSimilarRequest) GetTagged() string {
	if x != nil {
		return x.Tagged
	}
	return ""
}

func (x *GetSimilarRequest) GetNottagged() string {
	if x != nil {
		return x.Nottagged
	}
	return ""
}

func (x *GetSimilarRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetSimilarRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSimilarRequest) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *GetSimilarRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *GetSimilarRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type GetSimilarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of similar questions.
	Items []*Question `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether there are more results available on subsequent pages.
	HasMore bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// The number of API requests remaining in your daily quota.
	QuotaRemaining int32 `protobuf:"varint,3,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSimilarResponse) Reset() {
	*x = GetSimilarResponse{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarResponse) ProtoMessage() {}

func (x *GetSimilarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarResponse.ProtoReflect.Descriptor instead.
func (*GetSimilarResponse) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{24}
}

func (x *GetSimilarResponse) GetItems() []*Question {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetSimilarResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetSimilarResponse) GetQuotaRemaining() int32 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

// Request to get unanswered questions.
type GetUnansweredRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by tags (semicolon-delimited, e.g. "go;concurrency").
	Tagged string `protobuf:"bytes,1,opt,name=tagged,proto3" json:"tagged,omitempty"`
	// Sort order: "activity", "votes", "creation" (default "activity").
	Sort string `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	// Page number for pagination (1-indexed, default 1).
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Number of results per page (default 10, max 100).
	Pagesize int32 `protobuf:"varint,4,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	// Stack Exchange site (default "stackoverflow").
	Site string `protobuf:"bytes,5,opt,name=site,proto3" json:"site,omitempty"`
	// API filter name. Use "withbody" to include question body text.
	Filter        string `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnansweredRequest) Reset() {
	*x = GetUnansweredRequest{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnansweredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnansweredRequest) ProtoMessage() {}

func (x *GetUnansweredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnansweredRequest.ProtoReflect.Descriptor instead.
func (*GetUnansweredRequest) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{25}
}

func (x *GetUnansweredRequest) GetTagged() string {
	if x != nil {
		return x.Tagged
	}
	return ""
}

func (x *GetUnansweredRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetUnansweredRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUnansweredRequest) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *GetUnansweredRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *GetUnansweredRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type GetUnansweredResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of unanswered questions.
	Items []*Question `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether there are more results available on subsequent pages.
	HasMore bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// The number of API requests remaining in your daily quota.
	QuotaRemaining int32 `protobuf:"varint,3,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUnansweredResponse) Reset() {
	*x = GetUnansweredResponse{}
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnansweredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnansweredResponse) ProtoMessage() {}

func (x *GetUnansweredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_v1_stackexchange_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnansweredResponse.ProtoReflect.Descriptor instead.
func (*GetUnansweredResponse) Descriptor() ([]byte, []int) {
	return file_stackexchange_v1_stackexchange_proto_rawDescGZIP(), []int{26}
}

func (x *GetUnansweredResponse) GetItems() []*Question {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetUnansweredResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetUnansweredResponse) GetQuotaRemaining() int32 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

var File_stackexchange_v1_stackexchange_proto protoreflect.FileDescriptor

const file_stackexchange_v1_stackexchange_proto_rawDesc = "" +
	"\n" +
	"$stackexchange/v1/stackexchange.proto\x12\x10stackexchange.v1\"\xd3\x03\n" +
	"\bQuestion\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12!\n" +
	"\fanswer_count\x18\x06 \x01(\x05R\vanswerCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\a \x01(\x05R\tviewCount\x12\x1f\n" +
	"\vis_answered\x18\b \x01(\bR\n" +
	"isAnswered\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x123\n" +
	"\x05owner\x18\n" +
	" \x01(\v2\x1d.stackexchange.v1.ShallowUserR\x05owner\x12#\n" +
	"\rcreation_date\x18\v \x01(\x03R\fcreationDate\x12,\n" +
	"\x12last_activity_date\x18\f \x01(\x03R\x10lastActivityDate\x12,\n" +
	"\x12accepted_answer_id\x18\r \x01(\x03R\x10acceptedAnswerId\x12%\n" +
	"\x0efavorite_count\x18\x0e \x01(\x05R\rfavoriteCount\"\xad\x02\n" +
	"\x06Answer\x12\x1b\n" +
	"\tanswer_id\x18\x01 \x01(\x03R\banswerId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x1f\n" +
	"\vis_accepted\x18\x05 \x01(\bR\n" +
	"isAccepted\x123\n" +
	"\x05owner\x18\x06 \x01(\v2\x1d.stackexchange.v1.ShallowUserR\x05owner\x12#\n" +
	"\rcreation_date\x18\a \x01(\x03R\fcreationDate\x12,\n" +
	"\x12last_activity_date\x18\b \x01(\x03R\x10lastActivityDate\x12\x12\n" +
	"\x04link\x18\t \x01(\tR\x04link\"\x9f\x01\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12!\n" +
	"\fhas_synonyms\x18\x03 \x01(\bR\vhasSynonyms\x12*\n" +
	"\x11is_moderator_only\x18\x04 \x01(\bR\x0fisModeratorOnly\x12\x1f\n" +
	"\vis_required\x18\x05 \x01(\bR\n" +
	"isRequired\"\xa2\x01\n" +
	"\vShallowUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1e\n" +
	"\n" +
	"reputation\x18\x03 \x01(\x05R\n" +
	"reputation\x12#\n" +
	"\rprofile_image\x18\x04 \x01(\tR\fprofileImage\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\"\xce\x03\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1e\n" +
	"\n" +
	"reputation\x18\x03 \x01(\x05R\n" +
	"reputation\x12#\n" +
	"\rprofile_image\x18\x04 \x01(\tR\fprofileImage\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12#\n" +
	"\rcreation_date\x18\x06 \x01(\x03R\fcreationDate\x12(\n" +
	"\x10last_access_date\x18\a \x01(\x03R\x0elastAccessDate\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x1f\n" +
	"\vwebsite_url\x18\t \x01(\tR\n" +
	"websiteUrl\x12\x19\n" +
	"\babout_me\x18\n" +
	" \x01(\tR\aaboutMe\x12%\n" +
	"\x0equestion_count\x18\v \x01(\x05R\rquestionCount\x12!\n" +
	"\fanswer_count\x18\f \x01(\x05R\vanswerCount\x12@\n" +
	"\fbadge_counts\x18\r \x01(\v2\x1d.stackexchange.v1.BadgeCountsR\vbadgeCounts\"Q\n" +
	"\vBadgeCounts\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x05R\x04gold\x12\x16\n" +
	"\x06silver\x18\x02 \x01(\x05R\x06silver\x12\x16\n" +
	"\x06bronze\x18\x03 \x01(\x05R\x06bronze\"\xd1\x01\n" +
	"\x10ReputationChange\x124\n" +
	"\x16reputation_change_type\x18\x01 \x01(\tR\x14reputationChangeType\x12+\n" +
	"\x11reputation_change\x18\x02 \x01(\x05R\x10reputationChange\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\x03R\x06postId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12\x17\n" +
	"\aon_date\x18\x06 \x01(\x03R\x06onDate\"\xba\x01\n" +
	"\x16SearchQuestionsRequest\x12\x18\n" +
	"\aintitle\x18\x01 \x01(\tR\aintitle\x12\x16\n" +
	"\x06tagged\x18\x02 \x01(\tR\x06tagged\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpagesize\x18\x05 \x01(\x05R\bpagesize\x12\x12\n" +
	"\x04site\x18\x06 \x01(\tR\x04site\x12\x16\n" +
	"\x06filter\x18\a \x01(\tR\x06filter\"\x8f\x01\n" +
	"\x17SearchQuestionsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.stackexchange.v1.QuestionR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12'\n" +
	"\x0fquota_remaining\x18\x03 \x01(\x05R\x0equotaRemaining\"P\n" +
	"\x12GetQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04site\x18\x02 \x01(\tR\x04site\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"M\n" +
	"\x13GetQuestionResponse\x126\n" +
	"\bquestion\x18\x01 \x01(\v2\x1a.stackexchange.v1.QuestionR\bquestion\"\xa4\x01\n" +
	"\x11GetAnswersRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpagesize\x18\x04 \x01(\x05R\bpagesize\x12\x12\n" +
	"\x04site\x18\x05 \x01(\tR\x04site\x12\x16\n" +
	"\x06filter\x18\x06 \x01(\tR\x06filter\"\x88\x01\n" +
	"\x12GetAnswersResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.stackexchange.v1.AnswerR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12'\n" +
	"\x0fquota_remaining\x18\x03 \x01(\x05R\x0equotaRemaining\"4\n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04site\x18\x02 \x01(\tR\x04site\"=\n" +
	"\x0fGetUserResponse\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x16.stackexchange.v1.UserR\x04user\"\x80\x01\n" +
	"\x0eGetTagsRequest\x12\x12\n" +
	"\x04sort\x18\x01 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpagesize\x18\x03 \x01(\x05R\bpagesize\x12\x16\n" +
	"\x06inname\x18\x04 \x01(\tR\x06inname\x12\x12\n" +
	"\x04site\x18\x05 \x01(\tR\x04site\"\x82\x01\n" +
	"\x0fGetTagsResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.stackexchange.v1.TagR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12'\n" +
	"\x0fquota_remaining\x18\x03 \x01(\x05R\x0equotaRemaining\"\xa0\x01\n" +
	"\x16GetTopQuestionsRequest\x12\x16\n" +
	"\x06tagged\x18\x01 \x01(\tR\x06tagged\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpagesize\x18\x04 \x01(\x05R\bpagesize\x12\x12\n" +
	"\x04site\x18\x05 \x01(\tR\x04site\x12\x16\n" +
	"\x06filter\x18\x06 \x01(\tR\x06filter\"\x8f\x01\n" +
	"\x17GetTopQuestionsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.stackexchange.v1.QuestionR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12'\n" +
	"\x0fquota_remaining\x18\x03 \x01(\x05R\x0equotaRemaining\"\xbf\x02\n" +
	"\x15SearchAdvancedRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06tagged\x18\x03 \x01(\tR\x06tagged\x12\x1c\n" +
	"\tnottagged\x18\x04 \x01(\tR\tnottagged\x12\x1f\n" +
	"\baccepted\x18\x05 \x01(\bH\x00R\baccepted\x88\x01\x01\x12\x18\n" +
	"\aanswers\x18\x06 \x01(\x05R\aanswers\x12\x14\n" +
	"\x05views\x18\a \x01(\x05R\x05views\x12\x12\n" +
	"\x04sort\x18\b \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\t \x01(\x05R\x04page\x12\x1a\n" +
	"\bpagesize\x18\n" +
	" \x01(\x05R\bpagesize\x12\x12\n" +
	"\x04site\x18\v \x01(\tR\x04site\x12\x16\n" +
	"\x06filter\x18\f \x01(\tR\x06filterB\v\n" +
	"\t_accepted\"\x8e\x01\n" +
	"\x16SearchAdvancedResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.stackexchange.v1.QuestionR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12'\n" +
	"\x0fquota_remaining\x18\x03 \x01(\x05R\x0equotaRemaining\"n\n" +
	"\x18GetUserReputationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpagesize\x18\x03 \x01(\x05R\bpagesize\x12\x12\n" +
	"\x04site\x18\x04 \x01(\tR\x04site\"\x99\x01\n" +
	"\x19GetUserReputationResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".stackexchange.v1.ReputationChangeR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12'\n" +
	"\x0fquota_remaining\x18\x03 \x01(\x05R\x0equotaRemaining\"\xcf\x01\n" +
	"\x11GetSimilarRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06tagged\x18\x02 \x01(\tR\x06tagged\x12\x1c\n" +
	"\tnottagged\x18\x03 \x01(\tR\tnottagged\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpagesize\x18\x06 \x01(\x05R\bpagesize\x12\x12\n" +
	"\x04site\x18\a \x01(\tR\x04site\x12\x16\n" +
	"\x06filter\x18\b \x01(\tR\x06filter\"\x8a\x01\n" +
	"\x12GetSimilarResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.stackexchange.v1.QuestionR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12'\n" +
	"\x0fquota_remaining\x18\x03 \x01(\x05R\x0equotaRemaining\"\x9e\x01\n" +
	"\x14GetUnansweredRequest\x12\x16\n" +
	"\x06tagged\x18\x01 \x01(\tR\x06tagged\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpagesize\x18\x04 \x01(\x05R\bpagesize\x12\x12\n" +
	"\x04site\x18\x05 \x01(\tR\x04site\x12\x16\n" +
	"\x06filter\x18\x06 \x01(\tR\x06filter\"\x8d\x01\n" +
	"\x15GetUnansweredResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.stackexchange.v1.QuestionR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12'\n" +
	"\x0fquota_remaining\x18\x03 \x01(\x05R\x0equotaRemaining2\xc9\a\n" +
	"\x14StackExchangeService\x12f\n" +
	"\x0fSearchQuestions\x12(.stackexchange.v1.SearchQuestionsRequest\x1a).stackexchange.v1.SearchQuestionsResponse\x12Z\n" +
	"\vGetQuestion\x12$.stackexchange.v1.GetQuestionRequest\x1a%.stackexchange.v1.GetQuestionResponse\x12W\n" +
	"\n" +
	"GetAnswers\x12#.stackexchange.v1.GetAnswersRequest\x1a$.stackexchange.v1.GetAnswersResponse\x12N\n" +
	"\aGetUser\x12 .stackexchange.v1.GetUserRequest\x1a!.stackexchange.v1.GetUserResponse\x12N\n" +
	"\aGetTags\x12 .stackexchange.v1.GetTagsRequest\x1a!.stackexchange.v1.GetTagsResponse\x12f\n" +
	"\x0fGetTopQuestions\x12(.stackexchange.v1.GetTopQuestionsRequest\x1a).stackexchange.v1.GetTopQuestionsResponse\x12c\n" +
	"\x0eSearchAdvanced\x12'.stackexchange.v1.SearchAdvancedRequest\x1a(.stackexchange.v1.SearchAdvancedResponse\x12l\n" +
	"\x11GetUserReputation\x12*.stackexchange.v1.GetUserReputationRequest\x1a+.stackexchange.v1.GetUserReputationResponse\x12W\n" +
	"\n" +
	"GetSimilar\x12#.stackexchange.v1.GetSimilarRequest\x1a$.stackexchange.v1.GetSimilarResponse\x12`\n" +
	"\rGetUnanswered\x12&.stackexchange.v1.GetUnansweredRequest\x1a'.stackexchange.v1.GetUnansweredResponseB\xe9\x01\n" +
	"\x14com.stackexchange.v1B\x12StackexchangeProtoP\x01Z\\github.com/jim-technologies/invariantaf/stackexchange/proto/stackexchange/v1;stackexchangev1\xa2\x02\x03SXX\xaa\x02\x10Stackexchange.V1\xca\x02\x10Stackexchange\\V1\xe2\x02\x1cStackexchange\\V1\\GPBMetadata\xea\x02\x11Stackexchange::V1b\x06proto3"

var (
	file_stackexchange_v1_stackexchange_proto_rawDescOnce sync.Once
	file_stackexchange_v1_stackexchange_proto_rawDescData []byte
)

func file_stackexchange_v1_stackexchange_proto_rawDescGZIP() []byte {
	file_stackexchange_v1_stackexchange_proto_rawDescOnce.Do(func() {
		file_stackexchange_v1_stackexchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stackexchange_v1_stackexchange_proto_rawDesc), len(file_stackexchange_v1_stackexchange_proto_rawDesc)))
	})
	return file_stackexchange_v1_stackexchange_proto_rawDescData
}

var file_stackexchange_v1_stackexchange_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_stackexchange_v1_stackexchange_proto_goTypes = []any{
	(*Question)(nil),                  // 0: stackexchange.v1.Question
	(*Answer)(nil),                    // 1: stackexchange.v1.Answer
	(*Tag)(nil),                       // 2: stackexchange.v1.Tag
	(*ShallowUser)(nil),               // 3: stackexchange.v1.ShallowUser
	(*User)(nil),                      // 4: stackexchange.v1.User
	(*BadgeCounts)(nil),               // 5: stackexchange.v1.BadgeCounts
	(*ReputationChange)(nil),          // 6: stackexchange.v1.ReputationChange
	(*SearchQuestionsRequest)(nil),    // 7: stackexchange.v1.SearchQuestionsRequest
	(*SearchQuestionsResponse)(nil),   // 8: stackexchange.v1.SearchQuestionsResponse
	(*GetQuestionRequest)(nil),        // 9: stackexchange.v1.GetQuestionRequest
	(*GetQuestionResponse)(nil),       // 10: stackexchange.v1.GetQuestionResponse
	(*GetAnswersRequest)(nil),         // 11: stackexchange.v1.GetAnswersRequest
	(*GetAnswersResponse)(nil),        // 12: stackexchange.v1.GetAnswersResponse
	(*GetUserRequest)(nil),            // 13: stackexchange.v1.GetUserRequest
	(*GetUserResponse)(nil),           // 14: stackexchange.v1.GetUserResponse
	(*GetTagsRequest)(nil),            // 15: stackexchange.v1.GetTagsRequest
	(*GetTagsResponse)(nil),           // 16: stackexchange.v1.GetTagsResponse
	(*GetTopQuestionsRequest)(nil),    // 17: stackexchange.v1.GetTopQuestionsRequest
	(*GetTopQuestionsResponse)(nil),   // 18: stackexchange.v1.GetTopQuestionsResponse
	(*SearchAdvancedRequest)(nil),     // 19: stackexchange.v1.SearchAdvancedRequest
	(*SearchAdvancedResponse)(nil),    // 20: stackexchange.v1.SearchAdvancedResponse
	(*GetUserReputationRequest)(nil),  // 21: stackexchange.v1.GetUserReputationRequest
	(*GetUserReputationResponse)(nil), // 22: stackexchange.v1.GetUserReputationResponse
	(*GetSimilarRequest)(nil),         // 23: stackexchange.v1.GetSimilarRequest
	(*GetSimilarResponse)(nil),        // 24: stackexchange.v1.GetSimilarResponse
	(*GetUnansweredRequest)(nil),      // 25: stackexchange.v1.GetUnansweredRequest
	(*GetUnansweredResponse)(nil),     // 26: stackexchange.v1.GetUnansweredResponse
}
var file_stackexchange_v1_stackexchange_proto_depIdxs = []int32{
	3,  // 0: stackexchange.v1.Question.owner:type_name -> stackexchange.v1.ShallowUser
	3,  // 1: stackexchange.v1.Answer.owner:type_name -> stackexchange.v1.ShallowUser
	5,  // 2: stackexchange.v1.User.badge_counts:type_name -> stackexchange.v1.BadgeCounts
	0,  // 3: stackexchange.v1.SearchQuestionsResponse.items:type_name -> stackexchange.v1.Question
	0,  // 4: stackexchange.v1.GetQuestionResponse.question:type_name -> stackexchange.v1.Question
	1,  // 5: stackexchange.v1.GetAnswersResponse.items:type_name -> stackexchange.v1.Answer
	4,  // 6: stackexchange.v1.GetUserResponse.user:type_name -> stackexchange.v1.User
	2,  // 7: stackexchange.v1.GetTagsResponse.items:type_name -> stackexchange.v1.Tag
	0,  // 8: stackexchange.v1.GetTopQuestionsResponse.items:type_name -> stackexchange.v1.Question
	0,  // 9: stackexchange.v1.SearchAdvancedResponse.items:type_name -> stackexchange.v1.Question
	6,  // 10: stackexchange.v1.GetUserReputationResponse.items:type_name -> stackexchange.v1.ReputationChange
	0,  // 11: stackexchange.v1.GetSimilarResponse.items:type_name -> stackexchange.v1.Question
	0,  // 12: stackexchange.v1.GetUnansweredResponse.items:type_name -> stackexchange.v1.Question
	7,  // 13: stackexchange.v1.StackExchangeService.SearchQuestions:input_type -> stackexchange.v1.SearchQuestionsRequest
	9,  // 14: stackexchange.v1.StackExchangeService.GetQuestion:input_type -> stackexchange.v1.GetQuestionRequest
	11, // 15: stackexchange.v1.StackExchangeService.GetAnswers:input_type -> stackexchange.v1.GetAnswersRequest
	13, // 16: stackexchange.v1.StackExchangeService.GetUser:input_type -> stackexchange.v1.GetUserRequest
	15, // 17: stackexchange.v1.StackExchangeService.GetTags:input_type -> stackexchange.v1.GetTagsRequest
	17, // 18: stackexchange.v1.StackExchangeService.GetTopQuestions:input_type -> stackexchange.v1.GetTopQuestionsRequest
	19, // 19: stackexchange.v1.StackExchangeService.SearchAdvanced:input_type -> stackexchange.v1.SearchAdvancedRequest
	21, // 20: stackexchange.v1.StackExchangeService.GetUserReputation:input_type -> stackexchange.v1.GetUserReputationRequest
	23, // 21: stackexchange.v1.StackExchangeService.GetSimilar:input_type -> stackexchange.v1.GetSimilarRequest
	25, // 22: stackexchange.v1.StackExchangeService.GetUnanswered:input_type -> stackexchange.v1.GetUnansweredRequest
	8,  // 23: stackexchange.v1.StackExchangeService.SearchQuestions:output_type -> stackexchange.v1.SearchQuestionsResponse
	10, // 24: stackexchange.v1.StackExchangeService.GetQuestion:output_type -> stackexchange.v1.GetQuestionResponse
	12, // 25: stackexchange.v1.StackExchangeService.GetAnswers:output_type -> stackexchange.v1.GetAnswersResponse
	14, // 26: stackexchange.v1.StackExchangeService.GetUser:output_type -> stackexchange.v1.GetUserResponse
	16, // 27: stackexchange.v1.StackExchangeService.GetTags:output_type -> stackexchange.v1.GetTagsResponse
	18, // 28: stackexchange.v1.StackExchangeService.GetTopQuestions:output_type -> stackexchange.v1.GetTopQuestionsResponse
	20, // 29: stackexchange.v1.StackExchangeService.SearchAdvanced:output_type -> stackexchange.v1.SearchAdvancedResponse
	22, // 30: stackexchange.v1.StackExchangeService.GetUserReputation:output_type -> stackexchange.v1.GetUserReputationResponse
	24, // 31: stackexchange.v1.StackExchangeService.GetSimilar:output_type -> stackexchange.v1.GetSimilarResponse
	26, // 32: stackexchange.v1.StackExchangeService.GetUnanswered:output_type -> stackexchange.v1.GetUnansweredResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_stackexchange_v1_stackexchange_proto_init() }
func file_stackexchange_v1_stackexchange_proto_init() {
	if File_stackexchange_v1_stackexchange_proto != nil {
		return
	}
	file_stackexchange_v1_stackexchange_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stackexchange_v1_stackexchange_proto_rawDesc), len(file_stackexchange_v1_stackexchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stackexchange_v1_stackexchange_proto_goTypes,
		DependencyIndexes: file_stackexchange_v1_stackexchange_proto_depIdxs,
		MessageInfos:      file_stackexchange_v1_stackexchange_proto_msgTypes,
	}.Build()
	File_stackexchange_v1_stackexchange_proto = out.File
	file_stackexchange_v1_stackexchange_proto_goTypes = nil
	file_stackexchange_v1_stackexchange_proto_depIdxs = nil
}
