// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bravesearch/v1/bravesearch.proto

package bravesearchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for web search.
type WebSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The search query string. Required.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Number of results to return (default 10, max 20).
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Zero-based offset for pagination.
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Country code to bias results (e.g. "US", "GB", "DE").
	Country string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	// Search language code (e.g. "en", "fr", "de").
	SearchLang string `protobuf:"bytes,5,opt,name=search_lang,json=searchLang,proto3" json:"search_lang,omitempty"`
	// Freshness filter: "pd" (past day), "pw" (past week), "pm" (past month).
	Freshness     string `protobuf:"bytes,6,opt,name=freshness,proto3" json:"freshness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSearchRequest) Reset() {
	*x = WebSearchRequest{}
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSearchRequest) ProtoMessage() {}

func (x *WebSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSearchRequest.ProtoReflect.Descriptor instead.
func (*WebSearchRequest) Descriptor() ([]byte, []int) {
	return file_bravesearch_v1_bravesearch_proto_rawDescGZIP(), []int{0}
}

func (x *WebSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *WebSearchRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *WebSearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WebSearchRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *WebSearchRequest) GetSearchLang() string {
	if x != nil {
		return x.SearchLang
	}
	return ""
}

func (x *WebSearchRequest) GetFreshness() string {
	if x != nil {
		return x.Freshness
	}
	return ""
}

type WebSearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The web search results.
	Results []*WebResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Total estimated number of results.
	TotalCount    int64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSearchResponse) Reset() {
	*x = WebSearchResponse{}
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSearchResponse) ProtoMessage() {}

func (x *WebSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSearchResponse.ProtoReflect.Descriptor instead.
func (*WebSearchResponse) Descriptor() ([]byte, []int) {
	return file_bravesearch_v1_bravesearch_proto_rawDescGZIP(), []int{1}
}

func (x *WebSearchResponse) GetResults() []*WebResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *WebSearchResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Request for news search.
type NewsSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The search query string. Required.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Number of results to return (default 10, max 20).
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Country code to bias results (e.g. "US", "GB", "DE").
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	// Freshness filter: "pd" (past day), "pw" (past week), "pm" (past month).
	Freshness     string `protobuf:"bytes,4,opt,name=freshness,proto3" json:"freshness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsSearchRequest) Reset() {
	*x = NewsSearchRequest{}
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsSearchRequest) ProtoMessage() {}

func (x *NewsSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsSearchRequest.ProtoReflect.Descriptor instead.
func (*NewsSearchRequest) Descriptor() ([]byte, []int) {
	return file_bravesearch_v1_bravesearch_proto_rawDescGZIP(), []int{2}
}

func (x *NewsSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *NewsSearchRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *NewsSearchRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *NewsSearchRequest) GetFreshness() string {
	if x != nil {
		return x.Freshness
	}
	return ""
}

type NewsSearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The news search results.
	Results       []*NewsResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsSearchResponse) Reset() {
	*x = NewsSearchResponse{}
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsSearchResponse) ProtoMessage() {}

func (x *NewsSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsSearchResponse.ProtoReflect.Descriptor instead.
func (*NewsSearchResponse) Descriptor() ([]byte, []int) {
	return file_bravesearch_v1_bravesearch_proto_rawDescGZIP(), []int{3}
}

func (x *NewsSearchResponse) GetResults() []*NewsResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// Request for image search.
type ImageSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The search query string. Required.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Number of results to return (default 10, max 20).
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Country code to bias results (e.g. "US", "GB", "DE").
	Country       string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSearchRequest) Reset() {
	*x = ImageSearchRequest{}
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSearchRequest) ProtoMessage() {}

func (x *ImageSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSearchRequest.ProtoReflect.Descriptor instead.
func (*ImageSearchRequest) Descriptor() ([]byte, []int) {
	return file_bravesearch_v1_bravesearch_proto_rawDescGZIP(), []int{4}
}

func (x *ImageSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ImageSearchRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ImageSearchRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type ImageSearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The image search results.
	Results       []*ImageResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSearchResponse) Reset() {
	*x = ImageSearchResponse{}
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSearchResponse) ProtoMessage() {}

func (x *ImageSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSearchResponse.ProtoReflect.Descriptor instead.
func (*ImageSearchResponse) Descriptor() ([]byte, []int) {
	return file_bravesearch_v1_bravesearch_proto_rawDescGZIP(), []int{5}
}

func (x *ImageSearchResponse) GetResults() []*ImageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// A single web search result.
type WebResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result title.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Result URL.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Result description/snippet.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Page age (e.g. "2 hours ago").
	PageAge string `protobuf:"bytes,4,opt,name=page_age,json=pageAge,proto3" json:"page_age,omitempty"`
	// Language of the result.
	Language      string `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebResult) Reset() {
	*x = WebResult{}
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebResult) ProtoMessage() {}

func (x *WebResult) ProtoReflect() protoreflect.Message {
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebResult.ProtoReflect.Descriptor instead.
func (*WebResult) Descriptor() ([]byte, []int) {
	return file_bravesearch_v1_bravesearch_proto_rawDescGZIP(), []int{6}
}

func (x *WebResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WebResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WebResult) GetPageAge() string {
	if x != nil {
		return x.PageAge
	}
	return ""
}

func (x *WebResult) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// A single news search result.
type NewsResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Article title.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Article URL.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Article description/snippet.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Publication date (ISO 8601).
	Age string `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	// Source name.
	Source        string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsResult) Reset() {
	*x = NewsResult{}
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsResult) ProtoMessage() {}

func (x *NewsResult) ProtoReflect() protoreflect.Message {
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsResult.ProtoReflect.Descriptor instead.
func (*NewsResult) Descriptor() ([]byte, []int) {
	return file_bravesearch_v1_bravesearch_proto_rawDescGZIP(), []int{7}
}

func (x *NewsResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NewsResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NewsResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NewsResult) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *NewsResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// A single image search result.
type ImageResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image title.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Direct image URL.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Source page URL.
	SourceUrl string `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	// Image width in pixels.
	Width int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	// Image height in pixels.
	Height int32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	// Thumbnail URL.
	ThumbnailUrl  string `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageResult) Reset() {
	*x = ImageResult{}
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResult) ProtoMessage() {}

func (x *ImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_bravesearch_v1_bravesearch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResult.ProtoReflect.Descriptor instead.
func (*ImageResult) Descriptor() ([]byte, []int) {
	return file_bravesearch_v1_bravesearch_proto_rawDescGZIP(), []int{8}
}

func (x *ImageResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImageResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageResult) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *ImageResult) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageResult) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageResult) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

var File_bravesearch_v1_bravesearch_proto protoreflect.FileDescriptor

const file_bravesearch_v1_bravesearch_proto_rawDesc = "" +
	"\n" +
	" bravesearch/v1/bravesearch.proto\x12\x0ebravesearch.v1\"\xaf\x01\n" +
	"\x10WebSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1f\n" +
	"\vsearch_lang\x18\x05 \x01(\tR\n" +
	"searchLang\x12\x1c\n" +
	"\tfreshness\x18\x06 \x01(\tR\tfreshness\"i\n" +
	"\x11WebSearchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.bravesearch.v1.WebResultR\aresults\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"w\n" +
	"\x11NewsSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1c\n" +
	"\tfreshness\x18\x04 \x01(\tR\tfreshness\"J\n" +
	"\x12NewsSearchResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.bravesearch.v1.NewsResultR\aresults\"Z\n" +
	"\x12ImageSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\"L\n" +
	"\x13ImageSearchResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.bravesearch.v1.ImageResultR\aresults\"\x8c\x01\n" +
	"\tWebResult\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bpage_age\x18\x04 \x01(\tR\apageAge\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"\x80\x01\n" +
	"\n" +
	"NewsResult\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03age\x18\x04 \x01(\tR\x03age\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\xa7\x01\n" +
	"\vImageResult\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"source_url\x18\x03 \x01(\tR\tsourceUrl\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl2\x93\x02\n" +
	"\x12BraveSearchService\x12P\n" +
	"\tWebSearch\x12 .bravesearch.v1.WebSearchRequest\x1a!.bravesearch.v1.WebSearchResponse\x12S\n" +
	"\n" +
	"NewsSearch\x12!.bravesearch.v1.NewsSearchRequest\x1a\".bravesearch.v1.NewsSearchResponse\x12V\n" +
	"\vImageSearch\x12\".bravesearch.v1.ImageSearchRequest\x1a#.bravesearch.v1.ImageSearchResponseB\xd7\x01\n" +
	"\x12com.bravesearch.v1B\x10BravesearchProtoP\x01ZVgithub.com/jim-technologies/invariantaf/bravesearch/proto/bravesearch/v1;bravesearchv1\xa2\x02\x03BXX\xaa\x02\x0eBravesearch.V1\xca\x02\x0eBravesearch\\V1\xe2\x02\x1aBravesearch\\V1\\GPBMetadata\xea\x02\x0fBravesearch::V1b\x06proto3"

var (
	file_bravesearch_v1_bravesearch_proto_rawDescOnce sync.Once
	file_bravesearch_v1_bravesearch_proto_rawDescData []byte
)

func file_bravesearch_v1_bravesearch_proto_rawDescGZIP() []byte {
	file_bravesearch_v1_bravesearch_proto_rawDescOnce.Do(func() {
		file_bravesearch_v1_bravesearch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bravesearch_v1_bravesearch_proto_rawDesc), len(file_bravesearch_v1_bravesearch_proto_rawDesc)))
	})
	return file_bravesearch_v1_bravesearch_proto_rawDescData
}

var file_bravesearch_v1_bravesearch_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bravesearch_v1_bravesearch_proto_goTypes = []any{
	(*WebSearchRequest)(nil),    // 0: bravesearch.v1.WebSearchRequest
	(*WebSearchResponse)(nil),   // 1: bravesearch.v1.WebSearchResponse
	(*NewsSearchRequest)(nil),   // 2: bravesearch.v1.NewsSearchRequest
	(*NewsSearchResponse)(nil),  // 3: bravesearch.v1.NewsSearchResponse
	(*ImageSearchRequest)(nil),  // 4: bravesearch.v1.ImageSearchRequest
	(*ImageSearchResponse)(nil), // 5: bravesearch.v1.ImageSearchResponse
	(*WebResult)(nil),           // 6: bravesearch.v1.WebResult
	(*NewsResult)(nil),          // 7: bravesearch.v1.NewsResult
	(*ImageResult)(nil),         // 8: bravesearch.v1.ImageResult
}
var file_bravesearch_v1_bravesearch_proto_depIdxs = []int32{
	6, // 0: bravesearch.v1.WebSearchResponse.results:type_name -> bravesearch.v1.WebResult
	7, // 1: bravesearch.v1.NewsSearchResponse.results:type_name -> bravesearch.v1.NewsResult
	8, // 2: bravesearch.v1.ImageSearchResponse.results:type_name -> bravesearch.v1.ImageResult
	0, // 3: bravesearch.v1.BraveSearchService.WebSearch:input_type -> bravesearch.v1.WebSearchRequest
	2, // 4: bravesearch.v1.BraveSearchService.NewsSearch:input_type -> bravesearch.v1.NewsSearchRequest
	4, // 5: bravesearch.v1.BraveSearchService.ImageSearch:input_type -> bravesearch.v1.ImageSearchRequest
	1, // 6: bravesearch.v1.BraveSearchService.WebSearch:output_type -> bravesearch.v1.WebSearchResponse
	3, // 7: bravesearch.v1.BraveSearchService.NewsSearch:output_type -> bravesearch.v1.NewsSearchResponse
	5, // 8: bravesearch.v1.BraveSearchService.ImageSearch:output_type -> bravesearch.v1.ImageSearchResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bravesearch_v1_bravesearch_proto_init() }
func file_bravesearch_v1_bravesearch_proto_init() {
	if File_bravesearch_v1_bravesearch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bravesearch_v1_bravesearch_proto_rawDesc), len(file_bravesearch_v1_bravesearch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bravesearch_v1_bravesearch_proto_goTypes,
		DependencyIndexes: file_bravesearch_v1_bravesearch_proto_depIdxs,
		MessageInfos:      file_bravesearch_v1_bravesearch_proto_msgTypes,
	}.Build()
	File_bravesearch_v1_bravesearch_proto = out.File
	file_bravesearch_v1_bravesearch_proto_goTypes = nil
	file_bravesearch_v1_bravesearch_proto_depIdxs = nil
}
