// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dockerhub/v1/dockerhub.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to search Docker Hub repositories.
type SearchRepositoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The search query string. Searches repository names and descriptions.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Maximum number of results to return per page. Default is 25.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page number for pagination (1-based). Default is 1.
	Page          int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRepositoriesRequest) Reset() {
	*x = SearchRepositoriesRequest{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRepositoriesRequest) ProtoMessage() {}

func (x *SearchRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*SearchRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRepositoriesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRepositoriesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRepositoriesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Response containing search results.
type SearchRepositoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of matching repositories.
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// List of matching repositories.
	Results       []*RepositorySearchResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRepositoriesResponse) Reset() {
	*x = SearchRepositoriesResponse{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRepositoriesResponse) ProtoMessage() {}

func (x *SearchRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*SearchRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRepositoriesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchRepositoriesResponse) GetResults() []*RepositorySearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// A repository returned from a search query.
type RepositorySearchResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full repository name including namespace (e.g. "library/nginx").
	RepoName string `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	// Short description of the repository.
	ShortDescription string `protobuf:"bytes,2,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	// Number of stars the repository has received.
	StarCount int32 `protobuf:"varint,3,opt,name=star_count,json=starCount,proto3" json:"star_count,omitempty"`
	// Total number of times the image has been pulled.
	PullCount int64 `protobuf:"varint,4,opt,name=pull_count,json=pullCount,proto3" json:"pull_count,omitempty"`
	// Whether this is a Docker Official Image.
	IsOfficial bool `protobuf:"varint,5,opt,name=is_official,json=isOfficial,proto3" json:"is_official,omitempty"`
	// Whether this repository uses automated builds.
	IsAutomated   bool `protobuf:"varint,6,opt,name=is_automated,json=isAutomated,proto3" json:"is_automated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositorySearchResult) Reset() {
	*x = RepositorySearchResult{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositorySearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositorySearchResult) ProtoMessage() {}

func (x *RepositorySearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositorySearchResult.ProtoReflect.Descriptor instead.
func (*RepositorySearchResult) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{2}
}

func (x *RepositorySearchResult) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *RepositorySearchResult) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *RepositorySearchResult) GetStarCount() int32 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

func (x *RepositorySearchResult) GetPullCount() int64 {
	if x != nil {
		return x.PullCount
	}
	return 0
}

func (x *RepositorySearchResult) GetIsOfficial() bool {
	if x != nil {
		return x.IsOfficial
	}
	return false
}

func (x *RepositorySearchResult) GetIsAutomated() bool {
	if x != nil {
		return x.IsAutomated
	}
	return false
}

// Request to get a specific repository.
type GetRepositoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace (e.g. "library" for official images, or a username/org).
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The repository name (e.g. "nginx").
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryRequest) Reset() {
	*x = GetRepositoryRequest{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryRequest) ProtoMessage() {}

func (x *GetRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{3}
}

func (x *GetRepositoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRepositoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response with repository details.
type GetRepositoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace of the repository.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The repository name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Full description (may contain markdown).
	FullDescription string `protobuf:"bytes,3,opt,name=full_description,json=fullDescription,proto3" json:"full_description,omitempty"`
	// Short description.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Number of stars.
	StarCount int32 `protobuf:"varint,5,opt,name=star_count,json=starCount,proto3" json:"star_count,omitempty"`
	// Total pull count.
	PullCount int64 `protobuf:"varint,6,opt,name=pull_count,json=pullCount,proto3" json:"pull_count,omitempty"`
	// ISO 8601 timestamp of last update.
	LastUpdated string `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// Whether this is a Docker Official Image.
	IsOfficial bool `protobuf:"varint,8,opt,name=is_official,json=isOfficial,proto3" json:"is_official,omitempty"`
	// Whether this repository uses automated builds.
	IsAutomated bool `protobuf:"varint,9,opt,name=is_automated,json=isAutomated,proto3" json:"is_automated,omitempty"`
	// Repository status (e.g. active).
	Status        int32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryResponse) Reset() {
	*x = GetRepositoryResponse{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryResponse) ProtoMessage() {}

func (x *GetRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{4}
}

func (x *GetRepositoryResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRepositoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRepositoryResponse) GetFullDescription() string {
	if x != nil {
		return x.FullDescription
	}
	return ""
}

func (x *GetRepositoryResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetRepositoryResponse) GetStarCount() int32 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

func (x *GetRepositoryResponse) GetPullCount() int64 {
	if x != nil {
		return x.PullCount
	}
	return 0
}

func (x *GetRepositoryResponse) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *GetRepositoryResponse) GetIsOfficial() bool {
	if x != nil {
		return x.IsOfficial
	}
	return false
}

func (x *GetRepositoryResponse) GetIsAutomated() bool {
	if x != nil {
		return x.IsAutomated
	}
	return false
}

func (x *GetRepositoryResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// Request to list tags for a repository.
type GetTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace (e.g. "library").
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The repository name (e.g. "nginx").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Maximum number of tags to return per page. Default is 25.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page number for pagination (1-based). Default is 1.
	Page          int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsRequest) Reset() {
	*x = GetTagsRequest{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsRequest) ProtoMessage() {}

func (x *GetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTagsRequest) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{5}
}

func (x *GetTagsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetTagsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTagsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTagsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Response with a list of tags.
type GetTagsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of tags.
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// List of tags.
	Results []*Tag `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// URL for the next page of results, if any.
	Next string `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	// URL for the previous page of results, if any.
	Previous      string `protobuf:"bytes,4,opt,name=previous,proto3" json:"previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsResponse) Reset() {
	*x = GetTagsResponse{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsResponse) ProtoMessage() {}

func (x *GetTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsResponse.ProtoReflect.Descriptor instead.
func (*GetTagsResponse) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{6}
}

func (x *GetTagsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetTagsResponse) GetResults() []*Tag {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetTagsResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *GetTagsResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

// A tag for a Docker image.
type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tag name (e.g. "latest", "1.25", "alpine").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Full compressed size in bytes.
	FullSize int64 `protobuf:"varint,2,opt,name=full_size,json=fullSize,proto3" json:"full_size,omitempty"`
	// ISO 8601 timestamp of when this tag was last updated.
	LastUpdated string `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// Content digest (e.g. "sha256:abc123...").
	Digest        string `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{7}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetFullSize() int64 {
	if x != nil {
		return x.FullSize
	}
	return 0
}

func (x *Tag) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *Tag) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// Request to get a specific tag.
type GetTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace (e.g. "library").
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The repository name (e.g. "nginx").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The tag name (e.g. "latest").
	Tag           string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagRequest) Reset() {
	*x = GetTagRequest{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagRequest) ProtoMessage() {}

func (x *GetTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagRequest.ProtoReflect.Descriptor instead.
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{8}
}

func (x *GetTagRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// Response with tag details.
type GetTagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tag name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Full compressed size in bytes.
	FullSize int64 `protobuf:"varint,2,opt,name=full_size,json=fullSize,proto3" json:"full_size,omitempty"`
	// ISO 8601 timestamp of when this tag was last updated.
	LastUpdated string `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// Content digest.
	Digest        string `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagResponse) Reset() {
	*x = GetTagResponse{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagResponse) ProtoMessage() {}

func (x *GetTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagResponse.ProtoReflect.Descriptor instead.
func (*GetTagResponse) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{9}
}

func (x *GetTagResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTagResponse) GetFullSize() int64 {
	if x != nil {
		return x.FullSize
	}
	return 0
}

func (x *GetTagResponse) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *GetTagResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// Request to list repositories in a namespace.
type GetNamespaceRepositoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace to list repositories for (e.g. "library", "bitnami").
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Maximum number of results per page. Default is 25.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page number for pagination (1-based). Default is 1.
	Page          int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceRepositoriesRequest) Reset() {
	*x = GetNamespaceRepositoriesRequest{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceRepositoriesRequest) ProtoMessage() {}

func (x *GetNamespaceRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*GetNamespaceRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{10}
}

func (x *GetNamespaceRepositoriesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetNamespaceRepositoriesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetNamespaceRepositoriesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Response with repositories in the namespace.
type GetNamespaceRepositoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of repositories in the namespace.
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// List of repositories.
	Results []*NamespaceRepository `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// URL for the next page of results, if any.
	Next string `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	// URL for the previous page of results, if any.
	Previous      string `protobuf:"bytes,4,opt,name=previous,proto3" json:"previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceRepositoriesResponse) Reset() {
	*x = GetNamespaceRepositoriesResponse{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceRepositoriesResponse) ProtoMessage() {}

func (x *GetNamespaceRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*GetNamespaceRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{11}
}

func (x *GetNamespaceRepositoriesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetNamespaceRepositoriesResponse) GetResults() []*NamespaceRepository {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetNamespaceRepositoriesResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *GetNamespaceRepositoriesResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

// A repository within a namespace.
type NamespaceRepository struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repository name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The namespace.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Short description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Number of stars.
	StarCount int32 `protobuf:"varint,4,opt,name=star_count,json=starCount,proto3" json:"star_count,omitempty"`
	// Total pull count.
	PullCount int64 `protobuf:"varint,5,opt,name=pull_count,json=pullCount,proto3" json:"pull_count,omitempty"`
	// ISO 8601 timestamp of last update.
	LastUpdated string `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// Whether this is a Docker Official Image.
	IsOfficial    bool `protobuf:"varint,7,opt,name=is_official,json=isOfficial,proto3" json:"is_official,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceRepository) Reset() {
	*x = NamespaceRepository{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceRepository) ProtoMessage() {}

func (x *NamespaceRepository) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceRepository.ProtoReflect.Descriptor instead.
func (*NamespaceRepository) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{12}
}

func (x *NamespaceRepository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespaceRepository) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespaceRepository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NamespaceRepository) GetStarCount() int32 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

func (x *NamespaceRepository) GetPullCount() int64 {
	if x != nil {
		return x.PullCount
	}
	return 0
}

func (x *NamespaceRepository) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *NamespaceRepository) GetIsOfficial() bool {
	if x != nil {
		return x.IsOfficial
	}
	return false
}

// Request to get top (most popular) official images.
type GetTopImagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of results per page. Default is 25.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page number for pagination (1-based). Default is 1.
	Page          int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopImagesRequest) Reset() {
	*x = GetTopImagesRequest{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopImagesRequest) ProtoMessage() {}

func (x *GetTopImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopImagesRequest.ProtoReflect.Descriptor instead.
func (*GetTopImagesRequest) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{13}
}

func (x *GetTopImagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTopImagesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Response with top official images.
type GetTopImagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of official images.
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// List of official image repositories.
	Results []*NamespaceRepository `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// URL for the next page of results, if any.
	Next string `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	// URL for the previous page of results, if any.
	Previous      string `protobuf:"bytes,4,opt,name=previous,proto3" json:"previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopImagesResponse) Reset() {
	*x = GetTopImagesResponse{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopImagesResponse) ProtoMessage() {}

func (x *GetTopImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopImagesResponse.ProtoReflect.Descriptor instead.
func (*GetTopImagesResponse) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{14}
}

func (x *GetTopImagesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetTopImagesResponse) GetResults() []*NamespaceRepository {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetTopImagesResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *GetTopImagesResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

// Request to get build history for a repository.
type GetBuildHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace (e.g. "library").
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The repository name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Maximum number of results per page. Default is 25.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page number for pagination (1-based). Default is 1.
	Page          int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildHistoryRequest) Reset() {
	*x = GetBuildHistoryRequest{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildHistoryRequest) ProtoMessage() {}

func (x *GetBuildHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetBuildHistoryRequest) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{15}
}

func (x *GetBuildHistoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetBuildHistoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBuildHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetBuildHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Response with build history.
type GetBuildHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of build records.
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// List of build records.
	Results       []*BuildRecord `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildHistoryResponse) Reset() {
	*x = GetBuildHistoryResponse{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildHistoryResponse) ProtoMessage() {}

func (x *GetBuildHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetBuildHistoryResponse) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{16}
}

func (x *GetBuildHistoryResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetBuildHistoryResponse) GetResults() []*BuildRecord {
	if x != nil {
		return x.Results
	}
	return nil
}

// A single automated build record.
type BuildRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Build ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Build status (e.g. "Success", "Error").
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// ISO 8601 timestamp of build creation.
	CreatedDate string `protobuf:"bytes,3,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	// ISO 8601 timestamp of last update.
	LastUpdated string `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// Docker tag built (e.g. "latest").
	BuildTag      string `protobuf:"bytes,5,opt,name=build_tag,json=buildTag,proto3" json:"build_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRecord) Reset() {
	*x = BuildRecord{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRecord) ProtoMessage() {}

func (x *BuildRecord) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRecord.ProtoReflect.Descriptor instead.
func (*BuildRecord) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{17}
}

func (x *BuildRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuildRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BuildRecord) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *BuildRecord) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *BuildRecord) GetBuildTag() string {
	if x != nil {
		return x.BuildTag
	}
	return ""
}

// Request to get Dockerfile content.
type GetDockerfileContentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace (e.g. "library").
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The repository name.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDockerfileContentRequest) Reset() {
	*x = GetDockerfileContentRequest{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDockerfileContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerfileContentRequest) ProtoMessage() {}

func (x *GetDockerfileContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerfileContentRequest.ProtoReflect.Descriptor instead.
func (*GetDockerfileContentRequest) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{18}
}

func (x *GetDockerfileContentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetDockerfileContentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response with Dockerfile content.
type GetDockerfileContentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw Dockerfile text content.
	Contents      string `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDockerfileContentResponse) Reset() {
	*x = GetDockerfileContentResponse{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDockerfileContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerfileContentResponse) ProtoMessage() {}

func (x *GetDockerfileContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerfileContentResponse.ProtoReflect.Descriptor instead.
func (*GetDockerfileContentResponse) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{19}
}

func (x *GetDockerfileContentResponse) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

// Request to get Docker Hub categories.
type GetCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{20}
}

// Response with Docker Hub categories.
type GetCategoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of categories.
	Categories    []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{21}
}

func (x *GetCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

// A Docker Hub content category.
type Category struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Category name (e.g. "Databases", "Web Servers").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL-friendly slug for the category.
	Slug          string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{22}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// Request to get Docker extensions.
type GetExtensionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of results per page. Default is 25.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page number for pagination (1-based). Default is 1.
	Page          int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtensionsRequest) Reset() {
	*x = GetExtensionsRequest{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtensionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtensionsRequest) ProtoMessage() {}

func (x *GetExtensionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtensionsRequest.ProtoReflect.Descriptor instead.
func (*GetExtensionsRequest) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{23}
}

func (x *GetExtensionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetExtensionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Response with Docker extensions.
type GetExtensionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of extensions.
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// List of extensions.
	Results       []*Extension `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtensionsResponse) Reset() {
	*x = GetExtensionsResponse{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtensionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtensionsResponse) ProtoMessage() {}

func (x *GetExtensionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtensionsResponse.ProtoReflect.Descriptor instead.
func (*GetExtensionsResponse) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{24}
}

func (x *GetExtensionsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetExtensionsResponse) GetResults() []*Extension {
	if x != nil {
		return x.Results
	}
	return nil
}

// A Docker Desktop extension.
type Extension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Extension name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL-friendly slug.
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	// Extension description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Publisher name.
	Publisher string `protobuf:"bytes,4,opt,name=publisher,proto3" json:"publisher,omitempty"`
	// ISO 8601 timestamp of creation.
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ISO 8601 timestamp of last update.
	UpdatedAt     string `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extension) Reset() {
	*x = Extension{}
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_dockerhub_v1_dockerhub_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_dockerhub_v1_dockerhub_proto_rawDescGZIP(), []int{25}
}

func (x *Extension) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Extension) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Extension) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Extension) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Extension) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Extension) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_dockerhub_v1_dockerhub_proto protoreflect.FileDescriptor

const file_dockerhub_v1_dockerhub_proto_rawDesc = "" +
	"\n" +
	"\x1cdockerhub/v1/dockerhub.proto\x12\fdockerhub.v1\"b\n" +
	"\x19SearchRepositoriesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"r\n" +
	"\x1aSearchRepositoriesResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12>\n" +
	"\aresults\x18\x02 \x03(\v2$.dockerhub.v1.RepositorySearchResultR\aresults\"\xe4\x01\n" +
	"\x16RepositorySearchResult\x12\x1b\n" +
	"\trepo_name\x18\x01 \x01(\tR\brepoName\x12+\n" +
	"\x11short_description\x18\x02 \x01(\tR\x10shortDescription\x12\x1d\n" +
	"\n" +
	"star_count\x18\x03 \x01(\x05R\tstarCount\x12\x1d\n" +
	"\n" +
	"pull_count\x18\x04 \x01(\x03R\tpullCount\x12\x1f\n" +
	"\vis_official\x18\x05 \x01(\bR\n" +
	"isOfficial\x12!\n" +
	"\fis_automated\x18\x06 \x01(\bR\visAutomated\"H\n" +
	"\x14GetRepositoryRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xd3\x02\n" +
	"\x15GetRepositoryResponse\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10full_description\x18\x03 \x01(\tR\x0ffullDescription\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"star_count\x18\x05 \x01(\x05R\tstarCount\x12\x1d\n" +
	"\n" +
	"pull_count\x18\x06 \x01(\x03R\tpullCount\x12!\n" +
	"\flast_updated\x18\a \x01(\tR\vlastUpdated\x12\x1f\n" +
	"\vis_official\x18\b \x01(\bR\n" +
	"isOfficial\x12!\n" +
	"\fis_automated\x18\t \x01(\bR\visAutomated\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"s\n" +
	"\x0eGetTagsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\"\x84\x01\n" +
	"\x0fGetTagsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12+\n" +
	"\aresults\x18\x02 \x03(\v2\x11.dockerhub.v1.TagR\aresults\x12\x12\n" +
	"\x04next\x18\x03 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x04 \x01(\tR\bprevious\"q\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_size\x18\x02 \x01(\x03R\bfullSize\x12!\n" +
	"\flast_updated\x18\x03 \x01(\tR\vlastUpdated\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"S\n" +
	"\rGetTagRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\"|\n" +
	"\x0eGetTagResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_size\x18\x02 \x01(\x03R\bfullSize\x12!\n" +
	"\flast_updated\x18\x03 \x01(\tR\vlastUpdated\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"p\n" +
	"\x1fGetNamespaceRepositoriesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"\xa5\x01\n" +
	" GetNamespaceRepositoriesResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12;\n" +
	"\aresults\x18\x02 \x03(\v2!.dockerhub.v1.NamespaceRepositoryR\aresults\x12\x12\n" +
	"\x04next\x18\x03 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x04 \x01(\tR\bprevious\"\xeb\x01\n" +
	"\x13NamespaceRepository\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"star_count\x18\x04 \x01(\x05R\tstarCount\x12\x1d\n" +
	"\n" +
	"pull_count\x18\x05 \x01(\x03R\tpullCount\x12!\n" +
	"\flast_updated\x18\x06 \x01(\tR\vlastUpdated\x12\x1f\n" +
	"\vis_official\x18\a \x01(\bR\n" +
	"isOfficial\"F\n" +
	"\x13GetTopImagesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"\x99\x01\n" +
	"\x14GetTopImagesResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12;\n" +
	"\aresults\x18\x02 \x03(\v2!.dockerhub.v1.NamespaceRepositoryR\aresults\x12\x12\n" +
	"\x04next\x18\x03 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x04 \x01(\tR\bprevious\"{\n" +
	"\x16GetBuildHistoryRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\"d\n" +
	"\x17GetBuildHistoryResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x123\n" +
	"\aresults\x18\x02 \x03(\v2\x19.dockerhub.v1.BuildRecordR\aresults\"\x98\x01\n" +
	"\vBuildRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcreated_date\x18\x03 \x01(\tR\vcreatedDate\x12!\n" +
	"\flast_updated\x18\x04 \x01(\tR\vlastUpdated\x12\x1b\n" +
	"\tbuild_tag\x18\x05 \x01(\tR\bbuildTag\"O\n" +
	"\x1bGetDockerfileContentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\":\n" +
	"\x1cGetDockerfileContentResponse\x12\x1a\n" +
	"\bcontents\x18\x01 \x01(\tR\bcontents\"\x16\n" +
	"\x14GetCategoriesRequest\"O\n" +
	"\x15GetCategoriesResponse\x126\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x16.dockerhub.v1.CategoryR\n" +
	"categories\"2\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"G\n" +
	"\x14GetExtensionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"`\n" +
	"\x15GetExtensionsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.dockerhub.v1.ExtensionR\aresults\"\xb1\x01\n" +
	"\tExtension\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tpublisher\x18\x04 \x01(\tR\tpublisher\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt2\xb7\a\n" +
	"\x10DockerHubService\x12g\n" +
	"\x12SearchRepositories\x12'.dockerhub.v1.SearchRepositoriesRequest\x1a(.dockerhub.v1.SearchRepositoriesResponse\x12X\n" +
	"\rGetRepository\x12\".dockerhub.v1.GetRepositoryRequest\x1a#.dockerhub.v1.GetRepositoryResponse\x12F\n" +
	"\aGetTags\x12\x1c.dockerhub.v1.GetTagsRequest\x1a\x1d.dockerhub.v1.GetTagsResponse\x12C\n" +
	"\x06GetTag\x12\x1b.dockerhub.v1.GetTagRequest\x1a\x1c.dockerhub.v1.GetTagResponse\x12y\n" +
	"\x18GetNamespaceRepositories\x12-.dockerhub.v1.GetNamespaceRepositoriesRequest\x1a..dockerhub.v1.GetNamespaceRepositoriesResponse\x12U\n" +
	"\fGetTopImages\x12!.dockerhub.v1.GetTopImagesRequest\x1a\".dockerhub.v1.GetTopImagesResponse\x12^\n" +
	"\x0fGetBuildHistory\x12$.dockerhub.v1.GetBuildHistoryRequest\x1a%.dockerhub.v1.GetBuildHistoryResponse\x12m\n" +
	"\x14GetDockerfileContent\x12).dockerhub.v1.GetDockerfileContentRequest\x1a*.dockerhub.v1.GetDockerfileContentResponse\x12X\n" +
	"\rGetCategories\x12\".dockerhub.v1.GetCategoriesRequest\x1a#.dockerhub.v1.GetCategoriesResponse\x12X\n" +
	"\rGetExtensions\x12\".dockerhub.v1.GetExtensionsRequest\x1a#.dockerhub.v1.GetExtensionsResponseB\xb3\x01\n" +
	"\x10com.dockerhub.v1B\x0eDockerhubProtoP\x01Z>github.com/jim-technologies/invariantaf/dockerhub/dockerhub/v1\xa2\x02\x03DXX\xaa\x02\fDockerhub.V1\xca\x02\fDockerhub\\V1\xe2\x02\x18Dockerhub\\V1\\GPBMetadata\xea\x02\rDockerhub::V1b\x06proto3"

var (
	file_dockerhub_v1_dockerhub_proto_rawDescOnce sync.Once
	file_dockerhub_v1_dockerhub_proto_rawDescData []byte
)

func file_dockerhub_v1_dockerhub_proto_rawDescGZIP() []byte {
	file_dockerhub_v1_dockerhub_proto_rawDescOnce.Do(func() {
		file_dockerhub_v1_dockerhub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dockerhub_v1_dockerhub_proto_rawDesc), len(file_dockerhub_v1_dockerhub_proto_rawDesc)))
	})
	return file_dockerhub_v1_dockerhub_proto_rawDescData
}

var file_dockerhub_v1_dockerhub_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_dockerhub_v1_dockerhub_proto_goTypes = []any{
	(*SearchRepositoriesRequest)(nil),        // 0: dockerhub.v1.SearchRepositoriesRequest
	(*SearchRepositoriesResponse)(nil),       // 1: dockerhub.v1.SearchRepositoriesResponse
	(*RepositorySearchResult)(nil),           // 2: dockerhub.v1.RepositorySearchResult
	(*GetRepositoryRequest)(nil),             // 3: dockerhub.v1.GetRepositoryRequest
	(*GetRepositoryResponse)(nil),            // 4: dockerhub.v1.GetRepositoryResponse
	(*GetTagsRequest)(nil),                   // 5: dockerhub.v1.GetTagsRequest
	(*GetTagsResponse)(nil),                  // 6: dockerhub.v1.GetTagsResponse
	(*Tag)(nil),                              // 7: dockerhub.v1.Tag
	(*GetTagRequest)(nil),                    // 8: dockerhub.v1.GetTagRequest
	(*GetTagResponse)(nil),                   // 9: dockerhub.v1.GetTagResponse
	(*GetNamespaceRepositoriesRequest)(nil),  // 10: dockerhub.v1.GetNamespaceRepositoriesRequest
	(*GetNamespaceRepositoriesResponse)(nil), // 11: dockerhub.v1.GetNamespaceRepositoriesResponse
	(*NamespaceRepository)(nil),              // 12: dockerhub.v1.NamespaceRepository
	(*GetTopImagesRequest)(nil),              // 13: dockerhub.v1.GetTopImagesRequest
	(*GetTopImagesResponse)(nil),             // 14: dockerhub.v1.GetTopImagesResponse
	(*GetBuildHistoryRequest)(nil),           // 15: dockerhub.v1.GetBuildHistoryRequest
	(*GetBuildHistoryResponse)(nil),          // 16: dockerhub.v1.GetBuildHistoryResponse
	(*BuildRecord)(nil),                      // 17: dockerhub.v1.BuildRecord
	(*GetDockerfileContentRequest)(nil),      // 18: dockerhub.v1.GetDockerfileContentRequest
	(*GetDockerfileContentResponse)(nil),     // 19: dockerhub.v1.GetDockerfileContentResponse
	(*GetCategoriesRequest)(nil),             // 20: dockerhub.v1.GetCategoriesRequest
	(*GetCategoriesResponse)(nil),            // 21: dockerhub.v1.GetCategoriesResponse
	(*Category)(nil),                         // 22: dockerhub.v1.Category
	(*GetExtensionsRequest)(nil),             // 23: dockerhub.v1.GetExtensionsRequest
	(*GetExtensionsResponse)(nil),            // 24: dockerhub.v1.GetExtensionsResponse
	(*Extension)(nil),                        // 25: dockerhub.v1.Extension
}
var file_dockerhub_v1_dockerhub_proto_depIdxs = []int32{
	2,  // 0: dockerhub.v1.SearchRepositoriesResponse.results:type_name -> dockerhub.v1.RepositorySearchResult
	7,  // 1: dockerhub.v1.GetTagsResponse.results:type_name -> dockerhub.v1.Tag
	12, // 2: dockerhub.v1.GetNamespaceRepositoriesResponse.results:type_name -> dockerhub.v1.NamespaceRepository
	12, // 3: dockerhub.v1.GetTopImagesResponse.results:type_name -> dockerhub.v1.NamespaceRepository
	17, // 4: dockerhub.v1.GetBuildHistoryResponse.results:type_name -> dockerhub.v1.BuildRecord
	22, // 5: dockerhub.v1.GetCategoriesResponse.categories:type_name -> dockerhub.v1.Category
	25, // 6: dockerhub.v1.GetExtensionsResponse.results:type_name -> dockerhub.v1.Extension
	0,  // 7: dockerhub.v1.DockerHubService.SearchRepositories:input_type -> dockerhub.v1.SearchRepositoriesRequest
	3,  // 8: dockerhub.v1.DockerHubService.GetRepository:input_type -> dockerhub.v1.GetRepositoryRequest
	5,  // 9: dockerhub.v1.DockerHubService.GetTags:input_type -> dockerhub.v1.GetTagsRequest
	8,  // 10: dockerhub.v1.DockerHubService.GetTag:input_type -> dockerhub.v1.GetTagRequest
	10, // 11: dockerhub.v1.DockerHubService.GetNamespaceRepositories:input_type -> dockerhub.v1.GetNamespaceRepositoriesRequest
	13, // 12: dockerhub.v1.DockerHubService.GetTopImages:input_type -> dockerhub.v1.GetTopImagesRequest
	15, // 13: dockerhub.v1.DockerHubService.GetBuildHistory:input_type -> dockerhub.v1.GetBuildHistoryRequest
	18, // 14: dockerhub.v1.DockerHubService.GetDockerfileContent:input_type -> dockerhub.v1.GetDockerfileContentRequest
	20, // 15: dockerhub.v1.DockerHubService.GetCategories:input_type -> dockerhub.v1.GetCategoriesRequest
	23, // 16: dockerhub.v1.DockerHubService.GetExtensions:input_type -> dockerhub.v1.GetExtensionsRequest
	1,  // 17: dockerhub.v1.DockerHubService.SearchRepositories:output_type -> dockerhub.v1.SearchRepositoriesResponse
	4,  // 18: dockerhub.v1.DockerHubService.GetRepository:output_type -> dockerhub.v1.GetRepositoryResponse
	6,  // 19: dockerhub.v1.DockerHubService.GetTags:output_type -> dockerhub.v1.GetTagsResponse
	9,  // 20: dockerhub.v1.DockerHubService.GetTag:output_type -> dockerhub.v1.GetTagResponse
	11, // 21: dockerhub.v1.DockerHubService.GetNamespaceRepositories:output_type -> dockerhub.v1.GetNamespaceRepositoriesResponse
	14, // 22: dockerhub.v1.DockerHubService.GetTopImages:output_type -> dockerhub.v1.GetTopImagesResponse
	16, // 23: dockerhub.v1.DockerHubService.GetBuildHistory:output_type -> dockerhub.v1.GetBuildHistoryResponse
	19, // 24: dockerhub.v1.DockerHubService.GetDockerfileContent:output_type -> dockerhub.v1.GetDockerfileContentResponse
	21, // 25: dockerhub.v1.DockerHubService.GetCategories:output_type -> dockerhub.v1.GetCategoriesResponse
	24, // 26: dockerhub.v1.DockerHubService.GetExtensions:output_type -> dockerhub.v1.GetExtensionsResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_dockerhub_v1_dockerhub_proto_init() }
func file_dockerhub_v1_dockerhub_proto_init() {
	if File_dockerhub_v1_dockerhub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dockerhub_v1_dockerhub_proto_rawDesc), len(file_dockerhub_v1_dockerhub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dockerhub_v1_dockerhub_proto_goTypes,
		DependencyIndexes: file_dockerhub_v1_dockerhub_proto_depIdxs,
		MessageInfos:      file_dockerhub_v1_dockerhub_proto_msgTypes,
	}.Build()
	File_dockerhub_v1_dockerhub_proto = out.File
	file_dockerhub_v1_dockerhub_proto_goTypes = nil
	file_dockerhub_v1_dockerhub_proto_depIdxs = nil
}
